# Auto-generated by Composio CLI. Do not modify manually..

class _21RISK:
    """Map of Composio's _21RISK toolkit."""

    slug: str = "_21risk"

    class tools:
        GET_COMPLIANCE = "_21RISK_GET_COMPLIANCE"
        GET_ITEMS = "_21RISK_GET_ITEMS"
        GET_REPORTS = "_21RISK_GET_REPORTS"
        GET_SITES = "_21RISK_GET_SITES"
        GET_ITEMS_PER_MONTH = "_21RISK_GET_ITEMS_PER_MONTH"
        GET_RISKMODEL_CATEGORIES = "_21RISK_GET_RISKMODEL_CATEGORIES"
        GET_RISK_MODELS = "_21RISK_GET_RISK_MODELS"
        GET_ORGANIZATIONS = "_21RISK_GET_ORGANIZATIONS"
        GET_PROPERTIES = "_21RISK_GET_PROPERTIES"

    class triggers:
        pass
