# Auto-generated by Composio CLI. Do not modify manually..

class ABYSSALE:
    """Map of Composio's ABYSSALE toolkit."""

    slug: str = "abyssale"

    class tools:
        GET_DESIGNS = "ABYSSALE_GET_DESIGNS"
        AUTHENTICATION_TEST = "ABYSSALE_AUTHENTICATION_TEST"
        CREATE_PROJECT = "ABYSSALE_CREATE_PROJECT"
        GET_FONTS = "ABYSSALE_GET_FONTS"

    class triggers:
        pass
