# Auto-generated by Composio CLI. Do not modify manually..

class AEROLEADS:
    """Map of Composio's AEROLEADS toolkit."""

    slug: str = "aeroleads"

    class tools:
        GET_DETAILS_FROM_LINKEDIN_URL = "AEROLEADS_GET_DETAILS_FROM_LINKEDIN_URL"

    class triggers:
        pass
