# Auto-generated by Composio CLI. Do not modify manually..

class AGENTQL:
    """Map of Composio's AGENTQL toolkit."""

    slug: str = "agentql"

    class tools:
        GET_USAGE = "AGENTQL_GET_USAGE"
        CREATE_REMOTE_BROWSER_SESSION = "AGENTQL_CREATE_REMOTE_BROWSER_SESSION"
        QUERY_DATA = "AGENTQL_QUERY_DATA"

    class triggers:
        pass
