# Auto-generated by Composio CLI. Do not modify manually..

class ALTOVIZ:
    """Map of Composio's ALTOVIZ toolkit."""

    slug: str = "altoviz"

    class tools:
        GET_CLASSIFICATIONS = "ALTOVIZ_GET_CLASSIFICATIONS"
        DELETE_PRODUCT = "ALTOVIZ_DELETE_PRODUCT"
        FIND_PRODUCT = "ALTOVIZ_FIND_PRODUCT"
        GET_VATS = "ALTOVIZ_GET_VATS"
        GET_UNITS = "ALTOVIZ_GET_UNITS"
        FIND_CONTACT = "ALTOVIZ_FIND_CONTACT"
        CREATE_PRODUCT = "ALTOVIZ_CREATE_PRODUCT"
        FIND_CUSTOMER = "ALTOVIZ_FIND_CUSTOMER"
        UPDATE_CUSTOMER = "ALTOVIZ_UPDATE_CUSTOMER"

    class triggers:
        pass
