# Auto-generated by Composio CLI. Do not modify manually..

class AMCARDS:
    """Map of Composio's AMCARDS toolkit."""

    slug: str = "amcards"

    class tools:
        GET_CONTACTS = "AMCARDS_GET_CONTACTS"
        GET_CARDS = "AMCARDS_GET_CARDS"

    class triggers:
        pass
