# Auto-generated by Composio CLI. Do not modify manually..

class ASCORA:
    """Map of Composio's ASCORA toolkit."""

    slug: str = "ascora"

    class tools:
        GET_CUSTOMERS = "ASCORA_GET_CUSTOMERS"
        CREATE_QUOTATION = "ASCORA_CREATE_QUOTATION"
        DELETE_CUSTOMER = "ASCORA_DELETE_CUSTOMER"
        GET_JOBS = "ASCORA_GET_JOBS"

    class triggers:
        pass
