# Auto-generated by Composio CLI. Do not modify manually..

class AUTOBOUND:
    """Map of Composio's AUTOBOUND toolkit."""

    slug: str = "autobound"

    class tools:
        GENERATE_INSIGHTS = "AUTOBOUND_GENERATE_INSIGHTS"
        GENERATE_PERSONALIZED_CONTENT = "AUTOBOUND_GENERATE_PERSONALIZED_CONTENT"

    class triggers:
        pass
