# Auto-generated by Composio CLI. Do not modify manually..

class BEACONCHAIN:
    """Map of Composio's BEACONCHAIN toolkit."""

    slug: str = "beaconchain"

    class tools:
        GET_VALIDATOR = "BEACONCHAIN_GET_VALIDATOR"
        GET_NODE_HEALTH = "BEACONCHAIN_GET_NODE_HEALTH"

    class triggers:
        pass
