# Auto-generated by Composio CLI. Do not modify manually..

class BESTBUY:
    """Map of Composio's BESTBUY toolkit."""

    slug: str = "bestbuy"

    class tools:
        GET_STORES = "BESTBUY_GET_STORES"
        GET_PRODUCT_DETAILS = "BESTBUY_GET_PRODUCT_DETAILS"
        GET_CATEGORIES = "BESTBUY_GET_CATEGORIES"
        GET_STORE_DETAILS = "BESTBUY_GET_STORE_DETAILS"
        GET_REVIEW_DETAILS = "BESTBUY_GET_REVIEW_DETAILS"
        GET_REVIEWS = "BESTBUY_GET_REVIEWS"
        GET_CATEGORY_DETAILS = "BESTBUY_GET_CATEGORY_DETAILS"
        GET_PRODUCTS = "BESTBUY_GET_PRODUCTS"

    class triggers:
        pass
