# Auto-generated by Composio CLI. Do not modify manually..

class BIGMAILER:
    """Map of Composio's BIGMAILER toolkit."""

    slug: str = "bigmailer"

    class tools:
        CREATE_TRANSACTIONAL_CAMPAIGN = "BIGMAILER_CREATE_TRANSACTIONAL_CAMPAIGN"
        GET_USER_INFO = "BIGMAILER_GET_USER_INFO"
        LIST_ALL_BRANDS = "BIGMAILER_LIST_ALL_BRANDS"

    class triggers:
        pass
