# Auto-generated by Composio CLI. Do not modify manually..

class BLACKBAUD:
    """Map of Composio's BLACKBAUD toolkit."""

    slug: str = "blackbaud"

    class tools:
        GET_PAYMENT_TRANSACTION = "BLACKBAUD_GET_PAYMENT_TRANSACTION"
        GET_MEMBERSHIP_DETAILS = "BLACKBAUD_GET_MEMBERSHIP_DETAILS"
        ONE_ROSTER_O_AUTH2_BASE_API = "BLACKBAUD_ONE_ROSTER_O_AUTH2_BASE_API"
        ADD_GIFTS_TO_BATCH = "BLACKBAUD_ADD_GIFTS_TO_BATCH"
        GET_GIFT_BY_ID = "BLACKBAUD_GET_GIFT_BY_ID"

    class triggers:
        pass
