# Auto-generated by Composio CLI. Do not modify manually..

class BONSAI:
    """Map of Composio's BONSAI toolkit."""

    slug: str = "bonsai"

    class tools:
        LIST_SPACES = "BONSAI_LIST_SPACES"
        GET_SPACE_DETAILS = "BONSAI_GET_SPACE_DETAILS"
        GET_CLUSTER_DETAILS = "BONSAI_GET_CLUSTER_DETAILS"

    class triggers:
        pass
