# Auto-generated by Composio CLI. Do not modify manually..

class BUILDKITE:
    """Map of Composio's BUILDKITE toolkit."""

    slug: str = "buildkite"

    class tools:
        GET_CURRENT_ACCESS_TOKEN = "BUILDKITE_GET_CURRENT_ACCESS_TOKEN"
        LIST_PIPELINE_AGENTS = "BUILDKITE_LIST_PIPELINE_AGENTS"
        GET_META = "BUILDKITE_GET_META"

    class triggers:
        pass
