# Auto-generated by Composio CLI. Do not modify manually..

class CERTIFIER:
    """Map of Composio's CERTIFIER toolkit."""

    slug: str = "certifier"

    class tools:
        LIST_CREDENTIALS = "CERTIFIER_LIST_CREDENTIALS"
        SEND_CREDENTIAL = "CERTIFIER_SEND_CREDENTIAL"
        LIST_CREDENTIAL_INTERACTIONS = "CERTIFIER_LIST_CREDENTIAL_INTERACTIONS"
        LIST_DESIGNS = "CERTIFIER_LIST_DESIGNS"
        CREATE_ISSUE_SEND_CREDENTIAL = "CERTIFIER_CREATE_ISSUE_SEND_CREDENTIAL"
        LIST_GROUPS = "CERTIFIER_LIST_GROUPS"

    class triggers:
        pass
