# Auto-generated by Composio CLI. Do not modify manually..

class CHATFAI:
    """Map of Composio's CHATFAI toolkit."""

    slug: str = "chatfai"

    class tools:
        GET_PUBLIC_CHARACTER_BY_ID = "CHATFAI_GET_PUBLIC_CHARACTER_BY_ID"

    class triggers:
        pass
