# Auto-generated by Composio CLI. Do not modify manually..

class CHATWORK:
    """Map of Composio's CHATWORK toolkit."""

    slug: str = "chatwork"

    class tools:
        GET_ROOMS = "CHATWORK_GET_ROOMS"
        GET_ROOM_MEMBERS = "CHATWORK_GET_ROOM_MEMBERS"
        GET_FILE = "CHATWORK_GET_FILE"
        UPLOAD_FILE = "CHATWORK_UPLOAD_FILE"
        GET_CHATWORK_CONTACTS = "CHATWORK_GET_CHATWORK_CONTACTS"
        DELETE_MESSAGE = "CHATWORK_DELETE_MESSAGE"
        GET_MY_STATUS = "CHATWORK_GET_MY_STATUS"
        GET_ROOM_MESSAGES = "CHATWORK_GET_ROOM_MESSAGES"

    class triggers:
        pass
