# Auto-generated by Composio CLI. Do not modify manually..

class CODA:
    """Map of Composio's CODA toolkit."""

    slug: str = "coda"

    class tools:
        LIST_THE_VERSIONS_FOR_A_PACK = "CODA_LIST_THE_VERSIONS_FOR_A_PACK"
        GET_INFO_ABOUT_A_DOC = "CODA_GET_INFO_ABOUT_A_DOC"
        RETRIEVE_THE_OAUTH_CONFIGURATION_OF_THE_PACK = "CODA_RETRIEVE_THE_OAUTH_CONFIGURATION_OF_THE_PACK"
        CREATE_A_PAGE = "CODA_CREATE_A_PAGE"
        SEARCH_ROW = "CODA_SEARCH_ROW"
        UPDATE_PACK = "CODA_UPDATE_PACK"
        LIST_THE_PACK_LISTINGS_ACCESSIBLE_TO_A_USER = "CODA_LIST_THE_PACK_LISTINGS_ACCESSIBLE_TO_A_USER"
        TRIGGER_AUTOMATION = "CODA_TRIGGER_AUTOMATION"
        PACK_ASSET_UPLOAD_COMPLETE = "CODA_PACK_ASSET_UPLOAD_COMPLETE"
        ADD_A_PERMISSION_FOR_PACK = "CODA_ADD_A_PERMISSION_FOR_PACK"
        UPLOAD_PACK_SOURCE_CODE = "CODA_UPLOAD_PACK_SOURCE_CODE"
        UPDATES_A_CUSTOM_DOMAIN = "CODA_UPDATES_A_CUSTOM_DOMAIN"
        CREATE_PACK = "CODA_CREATE_PACK"
        GET_ANALYTICS_LAST_UPDATED_DAY = "CODA_GET_ANALYTICS_LAST_UPDATED_DAY"
        SEARCH_DOCS = "CODA_SEARCH_DOCS"
        DELETE_A_MAKER_FOR_PACK = "CODA_DELETE_A_MAKER_FOR_PACK"
        DELETE_A_PAGE = "CODA_DELETE_A_PAGE"
        LIST_CONTROLS = "CODA_LIST_CONTROLS"
        GET_A_CONTROL = "CODA_GET_A_CONTROL"
        LIST_DOC_ANALYTICS = "CODA_LIST_DOC_ANALYTICS"
        GETS_CUSTOM_DOC_DOMAINS_PROVIDERS = "CODA_GETS_CUSTOM_DOC_DOMAINS_PROVIDERS"
        ADD_A_CATEGORY_FOR_PACK = "CODA_ADD_A_CATEGORY_FOR_PACK"
        LIST_CUSTOM_DOC_DOMAINS = "CODA_LIST_CUSTOM_DOC_DOMAINS"
        BEGIN_CONTENT_EXPORT = "CODA_BEGIN_CONTENT_EXPORT"
        DELETE_PACK = "CODA_DELETE_PACK"
        UPDATE_AN_EXISTING_PACK_RELEASE = "CODA_UPDATE_AN_EXISTING_PACK_RELEASE"
        DELETE_DOC = "CODA_DELETE_DOC"
        LIST_COLUMNS = "CODA_LIST_COLUMNS"
        LIST_FORMULAS = "CODA_LIST_FORMULAS"
        CREATE_DOC = "CODA_CREATE_DOC"
        LIST_PERMISSIONS = "CODA_LIST_PERMISSIONS"
        LIST_WORKSPACE_USERS = "CODA_LIST_WORKSPACE_USERS"
        GET_A_SINGLE_PACK = "CODA_GET_A_SINGLE_PACK"
        LIST_AVAILABLE_DOCS = "CODA_LIST_AVAILABLE_DOCS"
        PUSH_A_BUTTON = "CODA_PUSH_A_BUTTON"
        PUBLISH_DOC = "CODA_PUBLISH_DOC"
        GET_A_COLUMN = "CODA_GET_A_COLUMN"
        UPSERT_ROWS = "CODA_UPSERT_ROWS"
        GET_MUTATION_STATUS = "CODA_GET_MUTATION_STATUS"
        GET_THE_DIFFERENCE_BETWEEN_TWO_PACK_VERSIONS = "CODA_GET_THE_DIFFERENCE_BETWEEN_TWO_PACK_VERSIONS"
        LIST_TABLES = "CODA_LIST_TABLES"
        DELETE_A_PERMISSION_FOR_PACK = "CODA_DELETE_A_PERMISSION_FOR_PACK"
        UNPUBLISH_DOC = "CODA_UNPUBLISH_DOC"
        RETRIEVE_THE_LOGS_OF_A_INGESTION = "CODA_RETRIEVE_THE_LOGS_OF_A_INGESTION"
        GET_USER_INFO = "CODA_GET_USER_INFO"
        GETS_THE_JSON_SCHEMA_FOR_PACK_CONFIGURATION = "CODA_GETS_THE_JSON_SCHEMA_FOR_PACK_CONFIGURATION"
        DELETES_A_CUSTOM_DOMAIN = "CODA_DELETES_A_CUSTOM_DOMAIN"
        GET_DOC_CATEGORIES = "CODA_GET_DOC_CATEGORIES"
        ADD_A_MAKER_FOR_PACK = "CODA_ADD_A_MAKER_FOR_PACK"
        LIST_FEATURED_DOCS_FOR_A_PACK = "CODA_LIST_FEATURED_DOCS_FOR_A_PACK"
        RESOLVE_BROWSER_LINK = "CODA_RESOLVE_BROWSER_LINK"
        LIST_PERMISSIONS_FOR_A_PACK = "CODA_LIST_PERMISSIONS_FOR_A_PACK"
        GET_DETAILED_LISTING_INFORMATION_FOR_A_PACK = "CODA_GET_DETAILED_LISTING_INFORMATION_FOR_A_PACK"
        CONTENT_EXPORT_STATUS = "CODA_CONTENT_EXPORT_STATUS"
        PATCH_THE_SYSTEM_CONNECTION_CREDENTIALS_OF_THE_PACK = "CODA_PATCH_THE_SYSTEM_CONNECTION_CREDENTIALS_OF_THE_PACK"
        FETCH_GROUPED_LOGS_BY_PACK_ORG_ROOT_INGESTION_ID = "CODA_FETCH_GROUPED_LOGS_BY_PACK_ORG_ROOT_INGESTION_ID"
        GET_PACK_ANALYTICS_SUMMARY = "CODA_GET_PACK_ANALYTICS_SUMMARY"
        GET_ACL_SETTINGS = "CODA_GET_ACL_SETTINGS"
        RETRIEVE_THE_LOGS_OF_A_PACK = "CODA_RETRIEVE_THE_LOGS_OF_A_PACK"
        FETCH_INGESTION_EXECUTIONS_FOR_PACK = "CODA_FETCH_INGESTION_EXECUTIONS_FOR_PACK"
        REGISTER_PACK_VERSION = "CODA_REGISTER_PACK_VERSION"
        LIST_PACKS = "CODA_LIST_PACKS"
        LIST_PACK_FORMULA_ANALYTICS = "CODA_LIST_PACK_FORMULA_ANALYTICS"
        GET_A_PAGE = "CODA_GET_A_PAGE"
        UPDATE_DOC = "CODA_UPDATE_DOC"
        GET_A_ROW = "CODA_GET_A_ROW"
        LIST_PAGES = "CODA_LIST_PAGES"
        COPY_DOC = "CODA_COPY_DOC"
        PACK_VERSION_UPLOAD_COMPLETE = "CODA_PACK_VERSION_UPLOAD_COMPLETE"
        SET_THE_OAUTH_CONFIGURATIONS_OF_THE_PACK = "CODA_SET_THE_OAUTH_CONFIGURATIONS_OF_THE_PACK"
        DELETE_ROW = "CODA_DELETE_ROW"
        PACK_SOURCE_CODE_UPLOAD_COMPLETE = "CODA_PACK_SOURCE_CODE_UPLOAD_COMPLETE"
        ADD_PERMISSION = "CODA_ADD_PERMISSION"
        DELETE_A_CATEGORY_FOR_PACK = "CODA_DELETE_A_CATEGORY_FOR_PACK"
        LIST_PACK_ANALYTICS = "CODA_LIST_PACK_ANALYTICS"
        GET_SHARING_METADATA = "CODA_GET_SHARING_METADATA"
        UPDATE_FEATURED_DOCS_FOR_A_PACK = "CODA_UPDATE_FEATURED_DOCS_FOR_A_PACK"
        GET_A_FORMULA = "CODA_GET_A_FORMULA"
        GET_DOC_ANALYTICS_SUMMARY = "CODA_GET_DOC_ANALYTICS_SUMMARY"
        GET_THE_SOURCE_CODE_FOR_A_PACK_VERSION = "CODA_GET_THE_SOURCE_CODE_FOR_A_PACK_VERSION"
        ADD_CUSTOM_DOMAIN = "CODA_ADD_CUSTOM_DOMAIN"
        LIST_CATEGORIES_FOR_PACK = "CODA_LIST_CATEGORIES_FOR_PACK"
        LIST_WORKSPACE_ROLES = "CODA_LIST_WORKSPACE_ROLES"
        UPDATE_A_PAGE = "CODA_UPDATE_A_PAGE"
        DELETE_PERMISSION = "CODA_DELETE_PERMISSION"
        RETRIEVE_THE_INFORMATION_FOR_A_SPECIFIC_LOG = "CODA_RETRIEVE_THE_INFORMATION_FOR_A_SPECIFIC_LOG"
        UPDATE_ACL_SETTINGS = "CODA_UPDATE_ACL_SETTINGS"
        LIST_PAGE_ANALYTICS = "CODA_LIST_PAGE_ANALYTICS"
        LIST_MAKERS_FOR_PACK = "CODA_LIST_MAKERS_FOR_PACK"
        LIST_THE_RELEASES_FOR_A_PACK = "CODA_LIST_THE_RELEASES_FOR_A_PACK"
        GET_A_TABLE = "CODA_GET_A_TABLE"
        UPDATES_USER_ROLE = "CODA_UPDATES_USER_ROLE"
        DELETE_MULTIPLE_ROWS = "CODA_DELETE_MULTIPLE_ROWS"
        LIST_TABLE_ROWS = "CODA_LIST_TABLE_ROWS"
        CREATE_A_NEW_PACK_RELEASE = "CODA_CREATE_A_NEW_PACK_RELEASE"
        GET_THE_NEXT_VALID_VERSION_FOR_A_PACK = "CODA_GET_THE_NEXT_VALID_VERSION_FOR_A_PACK"
        UPLOAD_A_PACK_ASSET = "CODA_UPLOAD_A_PACK_ASSET"
        SET_THE_SYSTEM_CONNECTION_CREDENTIALS_OF_THE_PACK = "CODA_SET_THE_SYSTEM_CONNECTION_CREDENTIALS_OF_THE_PACK"
        SEARCH_PRINCIPALS = "CODA_SEARCH_PRINCIPALS"
        RETRIEVE_THE_SYSTEM_CONNECTION_METADATA_OF_THE_PACK = "CODA_RETRIEVE_THE_SYSTEM_CONNECTION_METADATA_OF_THE_PACK"
        RETRIEVE_THE_GROUPED_LOGS_OF_A_PACK = "CODA_RETRIEVE_THE_GROUPED_LOGS_OF_A_PACK"

    class triggers:
        DOCUMENT_DELETED = {
          "config": {
            "properties": {
              "folderId": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Show only docs belonging to the given folder.",
                "title": "Folder Id"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "isOwner": {
                "anyOf": [{
                    "type": "boolean"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Show only docs owned by the user.",
                "title": "Is Owner"
              },
              "isPublished": {
                "anyOf": [{
                    "type": "boolean"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Show only published docs.",
                "title": "Is Published"
              },
              "isStarred": {
                "anyOf": [{
                    "type": "boolean"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "If true, returns docs that are starred. If false, returns docs that are not starred.",
                "title": "Is Starred"
              },
              "limit": {
                "default": 25,
                "description": "Maximum number of items to retrieve in a single poll (1-100).",
                "examples": [25],
                "title": "Limit",
                "type": "integer"
              },
              "workspaceId": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Show only docs belonging to the given workspace.",
                "title": "Workspace Id"
              }
            },
            "title": "CodaDocDeletedConfig",
            "type": "object"
          },
          "description": "Triggers when a Coda document is deleted.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - This trigger will detect when Coda documents are deleted.\n    - You can filter documents by owner, workspace, published status, and more.\n    - The trigger will only detect deletions for documents that the authenticated user has access to.\n    - Note: The trigger will establish a baseline of existing documents on first run and only report deletions thereafter.\n    ",
          "name": "Coda Document Deleted Trigger",
          "payload": {
            "$defs": {
              "CodaDocDeletedSchema": {
                "description": "Schema for deleted document information returned as result",
                "properties": {
                  "createdAt": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The creation timestamp of the document",
                    "title": "Created At"
                  },
                  "deleted_at": {
                    "description": "The timestamp when the document was detected as deleted",
                    "title": "Deleted At",
                    "type": "string"
                  },
                  "folderId": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the folder that contained the document",
                    "title": "Folder ID"
                  },
                  "id": {
                    "description": "The ID of the deleted document",
                    "title": "Document ID",
                    "type": "string"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the deleted document",
                    "title": "Document Name"
                  },
                  "owner": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The email of the document owner",
                    "title": "Owner Email"
                  },
                  "ownerName": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the document owner",
                    "title": "Owner Name"
                  },
                  "workspaceId": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the workspace that contained the document",
                    "title": "Workspace ID"
                  }
                },
                "required": ["id", "deleted_at"],
                "title": "CodaDocDeletedSchema",
                "type": "object"
              }
            },
            "description": "Payload for document deletion events",
            "properties": {
              "document": {
                "additionalProperties": False,
                "description": "The document that was deleted",
                "properties": {
                  "createdAt": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The creation timestamp of the document",
                    "title": "Created At"
                  },
                  "deleted_at": {
                    "description": "The timestamp when the document was detected as deleted",
                    "title": "Deleted At",
                    "type": "string"
                  },
                  "folderId": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the folder that contained the document",
                    "title": "Folder Id"
                  },
                  "id": {
                    "description": "The ID of the deleted document",
                    "title": "Id",
                    "type": "string"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the deleted document",
                    "title": "Name"
                  },
                  "owner": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The email of the document owner",
                    "title": "Owner"
                  },
                  "ownerName": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the document owner",
                    "title": "Owner Name"
                  },
                  "workspaceId": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the workspace that contained the document",
                    "title": "Workspace Id"
                  }
                },
                "required": ["id", "deleted_at"],
                "title": "Document",
                "type": "object"
              },
              "event_type": {
                "description": "Type of event",
                "title": "Event Type",
                "type": "string"
              }
            },
            "required": ["event_type", "document"],
            "title": "CodaDocDeletedPayload",
            "type": "object"
          },
          "slug": "CODA_DOCUMENT_DELETED",
          "type": "poll"
        }
        NEW_CODA_DOCUMENT = {
          "config": {
            "properties": {
              "folderId": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Show only docs belonging to the given folder.",
                "title": "Folder Id"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "isOwner": {
                "anyOf": [{
                    "type": "boolean"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Show only docs owned by the user.",
                "title": "Is Owner"
              },
              "isPublished": {
                "anyOf": [{
                    "type": "boolean"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Show only published docs.",
                "title": "Is Published"
              },
              "isStarred": {
                "anyOf": [{
                    "type": "boolean"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "If true, returns docs that are starred. If false, returns docs that are not starred.",
                "title": "Is Starred"
              },
              "limit": {
                "default": 25,
                "description": "Maximum number of items to retrieve in a single poll (1-100).",
                "examples": [25],
                "title": "Limit",
                "type": "integer"
              },
              "workspaceId": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Show only docs belonging to the given workspace.",
                "title": "Workspace Id"
              }
            },
            "title": "NewCodeDocumentConfig",
            "type": "object"
          },
          "description": "Triggers when a new Coda document is created.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - This trigger will detect new Coda documents as they are created.\n    - You can filter documents by owner, workspace, published status, and more.\n    - The trigger will only detect documents that the authenticated user has access to.\n    - Note: The trigger will establish a baseline of existing documents on first run and only report new documents thereafter.\n    ",
          "name": "New Coda Document Trigger",
          "payload": {
            "properties": {
              "browserLink": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The browser link to the document",
                "title": "Browser Link"
              },
              "createdAt": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The creation timestamp of the document",
                "title": "Created At"
              },
              "folderId": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the folder containing the document",
                "title": "Folder Id"
              },
              "href": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The URL of the document",
                "title": "Href"
              },
              "id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the document",
                "title": "Id"
              },
              "name": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The name of the document",
                "title": "Name"
              },
              "owner": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The email of the document owner",
                "title": "Owner"
              },
              "ownerName": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The name of the document owner",
                "title": "Owner Name"
              },
              "type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The type of the document",
                "title": "Type"
              },
              "updatedAt": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The last update timestamp of the document",
                "title": "Updated At"
              },
              "workspaceId": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the workspace containing the document",
                "title": "Workspace Id"
              }
            },
            "title": "NewCodeDocumentPayload",
            "type": "object"
          },
          "slug": "CODA_NEW_CODA_DOCUMENT",
          "type": "poll"
        }
        NEW_CODA_PAGE = {
          "config": {
            "properties": {
              "docId": {
                "description": "ID of the Coda document to monitor for new pages.",
                "examples": ["doc-abcd1234"],
                "title": "Doc Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "limit": {
                "default": 25,
                "description": "Maximum number of pages to retrieve in a single poll (1-100).",
                "examples": [25],
                "title": "Limit",
                "type": "integer"
              }
            },
            "required": ["docId"],
            "title": "CodaNewPageConfig",
            "type": "object"
          },
          "description": "Triggers when a new page is added to a Coda document.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - You need the Coda document ID (docId) to monitor for new pages.\n    - The document ID can be found in the URL of your Coda document after \"doc/\".\n    - Ensure you have proper access permissions to the document.\n    ",
          "name": "New Coda Page Trigger",
          "payload": {
            "$defs": {
              "CodaPageSchema": {
                "properties": {
                  "browserLink": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The browser link to the page",
                    "title": "Browser Link"
                  },
                  "created_at": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The creation timestamp of the page",
                    "title": "Created At"
                  },
                  "href": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The URL of the page",
                    "title": "Page URL"
                  },
                  "id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the page",
                    "title": "Page ID"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the page",
                    "title": "Page Name"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the page",
                    "title": "Page Type"
                  }
                },
                "title": "CodaPageSchema",
                "type": "object"
              }
            },
            "description": "Payload for page events",
            "properties": {
              "event_type": {
                "description": "Type of event",
                "title": "Event Type",
                "type": "string"
              },
              "page": {
                "additionalProperties": False,
                "description": "The page that triggered the event",
                "properties": {
                  "browserLink": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The browser link to the page",
                    "title": "Browser Link"
                  },
                  "created_at": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The creation timestamp of the page",
                    "title": "Created At"
                  },
                  "href": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The URL of the page",
                    "title": "Href"
                  },
                  "id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the page",
                    "title": "Id"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the page",
                    "title": "Name"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the page",
                    "title": "Type"
                  }
                },
                "title": "Page",
                "type": "object"
              }
            },
            "required": ["event_type", "page"],
            "title": "CodaNewPagePayload",
            "type": "object"
          },
          "slug": "CODA_NEW_CODA_PAGE",
          "type": "poll"
        }
        SPECIFIC_CODA_PAGE_UPDATED = {
          "config": {
            "properties": {
              "docId": {
                "description": "ID of the Coda document containing the page to monitor.",
                "examples": ["doc-abcd1234"],
                "title": "Doc Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "pageIdOrName": {
                "description": "ID or name of the specific page to monitor for updates.",
                "examples": ["canvas-XYZ123", "My Page Name"],
                "title": "Page Id Or Name",
                "type": "string"
              }
            },
            "required": ["docId", "pageIdOrName"],
            "title": "CodaPageUpdateConfig",
            "type": "object"
          },
          "description": "Triggers when a specific page within a Coda document is updated.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - You need the Coda document ID (docId) that contains the page to monitor.\n    - You need the page ID or name (pageIdOrName) to monitor for updates.\n    - The document ID can be found in the URL of your Coda document after \"doc/\".\n    - The page ID can be found in the page's URL or via the Coda API.\n    - If using a page name, be aware that if multiple pages have the same name, an arbitrary one will be selected.\n    - Ensure you have proper access permissions to the document and page.\n    ",
          "name": "Specific Coda Page Updated Trigger",
          "payload": {
            "$defs": {
              "CodaPageUpdateSchema": {
                "properties": {
                  "browserLink": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The browser link to the page",
                    "title": "Browser Link"
                  },
                  "href": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The URL of the page",
                    "title": "Page URL"
                  },
                  "id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the page",
                    "title": "Page ID"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the page",
                    "title": "Page Name"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the page",
                    "title": "Page Type"
                  },
                  "updated_at": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The update timestamp of the page",
                    "title": "Updated At"
                  },
                  "updated_by": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "User who updated the page",
                    "title": "Updated By"
                  }
                },
                "title": "CodaPageUpdateSchema",
                "type": "object"
              }
            },
            "description": "Payload for page update events",
            "properties": {
              "event_type": {
                "description": "Type of event",
                "title": "Event Type",
                "type": "string"
              },
              "page": {
                "additionalProperties": False,
                "description": "The page that was updated",
                "properties": {
                  "browserLink": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The browser link to the page",
                    "title": "Browser Link"
                  },
                  "href": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The URL of the page",
                    "title": "Href"
                  },
                  "id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the page",
                    "title": "Id"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the page",
                    "title": "Name"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the page",
                    "title": "Type"
                  },
                  "updated_at": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The update timestamp of the page",
                    "title": "Updated At"
                  },
                  "updated_by": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "User who updated the page",
                    "title": "Updated By"
                  }
                },
                "title": "Page",
                "type": "object"
              }
            },
            "required": ["event_type", "page"],
            "title": "CodaPageUpdatePayload",
            "type": "object"
          },
          "slug": "CODA_SPECIFIC_CODA_PAGE_UPDATED",
          "type": "poll"
        }
