# Auto-generated by Composio CLI. Do not modify manually..

class CODEINTERPRETER:
    """Map of Composio's CODEINTERPRETER toolkit."""

    slug: str = "codeinterpreter"

    class tools:
        CREATE_SANDBOX = "CODEINTERPRETER_CREATE_SANDBOX"
        GET_FILE_CMD = "CODEINTERPRETER_GET_FILE_CMD"
        RUN_TERMINAL_CMD = "CODEINTERPRETER_RUN_TERMINAL_CMD"
        UPLOAD_FILE_CMD = "CODEINTERPRETER_UPLOAD_FILE_CMD"
        EXECUTE_CODE = "CODEINTERPRETER_EXECUTE_CODE"

    class triggers:
        pass
