# Auto-generated by Composio CLI. Do not modify manually..

class COMMCARE:
    """Map of Composio's COMMCARE toolkit."""

    slug: str = "commcare"

    class tools:
        SUBMIT_FORM = "COMMCARE_SUBMIT_FORM"
        LIST_REPORTS = "COMMCARE_LIST_REPORTS"
        CREATE_WEB_USER_INVITATION = "COMMCARE_CREATE_WEB_USER_INVITATION"
        CREATE_LOOKUP_TABLE = "COMMCARE_CREATE_LOOKUP_TABLE"
        SINGLE_SIGN_ON = "COMMCARE_SINGLE_SIGN_ON"
        SUBMIT_FORM_ODK_COMPATIBLE = "COMMCARE_SUBMIT_FORM_ODK_COMPATIBLE"

    class triggers:
        pass
