# Auto-generated by Composio CLI. Do not modify manually..

class CULTS:
    """Map of Composio's CULTS toolkit."""

    slug: str = "cults"

    class tools:
        GET_APPROVED_ORIGINS = "CULTS_GET_APPROVED_ORIGINS"
        GRAPH_QL_POST = "CULTS_GRAPH_QL_POST"
        SHARE_ON_CREATE_FR = "CULTS_SHARE_ON_CREATE_FR"

    class triggers:
        pass
