# Auto-generated by Composio CLI. Do not modify manually..

class CURRENTS_API:
    """Map of Composio's CURRENTS_API toolkit."""

    slug: str = "currents_api"

    class tools:
        USER_USAGE_REPORT_GET = "CURRENTS_API_USER_USAGE_REPORT_GET"
        ACTIVITIES_WATCH = "CURRENTS_API_ACTIVITIES_WATCH"
        USERS_LIST = "CURRENTS_API_USERS_LIST"
        ACTIVITIES_LIST = "CURRENTS_API_ACTIVITIES_LIST"
        ENTITY_USAGE_REPORTS_GET = "CURRENTS_API_ENTITY_USAGE_REPORTS_GET"

    class triggers:
        pass
