# Auto-generated by Composio CLI. Do not modify manually..

class CURRENCYSCOOP:
    """Map of Composio's CURRENCYSCOOP toolkit."""

    slug: str = "currencyscoop"

    class tools:
        GET_TIMESERIES_RATES = "CURRENCYSCOOP_GET_TIMESERIES_RATES"
        GET_CURRENCIES = "CURRENCYSCOOP_GET_CURRENCIES"
        GET_HISTORICAL_RATES = "CURRENCYSCOOP_GET_HISTORICAL_RATES"
        CONVERT_CURRENCY = "CURRENCYSCOOP_CONVERT_CURRENCY"
        GET_LATEST_RATES = "CURRENCYSCOOP_GET_LATEST_RATES"

    class triggers:
        pass
