# Auto-generated by Composio CLI. Do not modify manually..

class DISCORD:
    """Map of Composio's DISCORD toolkit."""

    slug: str = "discord"

    class tools:
        LIST_STICKER_PACKS = "DISCORD_LIST_STICKER_PACKS"
        GET_MY_OAUTH2_AUTHORIZATION = "DISCORD_GET_MY_OAUTH2_AUTHORIZATION"
        LIST_MY_CONNECTIONS = "DISCORD_LIST_MY_CONNECTIONS"
        GET_MY_GUILD_MEMBER = "DISCORD_GET_MY_GUILD_MEMBER"
        GET_PUBLIC_KEYS = "DISCORD_GET_PUBLIC_KEYS"
        GET_MY_USER = "DISCORD_GET_MY_USER"
        GET_GUILD_WIDGET_PNG = "DISCORD_GET_GUILD_WIDGET_PNG"
        GET_GUILD_TEMPLATE = "DISCORD_GET_GUILD_TEMPLATE"
        GET_OPENID_CONNECT_USERINFO = "DISCORD_GET_OPENID_CONNECT_USERINFO"
        GET_USER = "DISCORD_GET_USER"
        INVITE_RESOLVE = "DISCORD_INVITE_RESOLVE"
        GET_INVITE = "DISCORD_GET_INVITE"
        LIST_MY_GUILDS = "DISCORD_LIST_MY_GUILDS"
        GET_GUILD_WIDGET = "DISCORD_GET_GUILD_WIDGET"
        GET_CURRENT_USER_APPLICATION_ENTITLEMENTS = "DISCORD_GET_CURRENT_USER_APPLICATION_ENTITLEMENTS"

    class triggers:
        NEW_MESSAGE_TRIGGER = {
          "config": {
            "properties": {
              "channel_id": {
                "description": "The ID of the Discord channel to monitor for new messages.",
                "title": "Channel Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "limit": {
                "default": 50,
                "description": "The number of messages to fetch per poll.",
                "title": "Limit",
                "type": "integer"
              }
            },
            "required": ["channel_id"],
            "title": "NewMessageConfig",
            "type": "object"
          },
          "description": "Polls a specific Discord channel for new messages.",
          "instructions": "\n    1. Provide the channel ID of the Discord channel you'd like to poll.\n    2. On first poll, we skip returning existing messages to avoid a flood.\n    3. On subsequent polls, any message with an ID greater than the last seen ID is returned as 'new.'\n    ",
          "name": "New Discord Message Trigger",
          "payload": {
            "$defs": {
              "DiscordMessageSchema": {
                "properties": {
                  "author_id": {
                    "default": "",
                    "description": "User ID of the message author.",
                    "title": "Author Id",
                    "type": "string"
                  },
                  "channel_id": {
                    "description": "Which channel the message is in.",
                    "title": "Channel Id",
                    "type": "string"
                  },
                  "content": {
                    "default": "",
                    "description": "The text content of the message.",
                    "title": "Content",
                    "type": "string"
                  },
                  "message_id": {
                    "description": "The ID of the message.",
                    "title": "Message Id",
                    "type": "string"
                  },
                  "timestamp": {
                    "default": "",
                    "description": "ISO8601 timestamp of when the message was created.",
                    "title": "Timestamp",
                    "type": "string"
                  },
                  "username": {
                    "default": "",
                    "description": "Username of the message author.",
                    "title": "Username",
                    "type": "string"
                  }
                },
                "required": ["message_id", "channel_id"],
                "title": "DiscordMessageSchema",
                "type": "object"
              }
            },
            "description": "Payload model for Discord message events.",
            "properties": {
              "event_type": {
                "default": "new_message",
                "description": "Type of Discord message event",
                "title": "Event Type",
                "type": "string"
              },
              "message": {
                "additionalProperties": False,
                "description": "The Discord message that was created",
                "properties": {
                  "author_id": {
                    "default": "",
                    "description": "User ID of the message author.",
                    "title": "Author Id",
                    "type": "string"
                  },
                  "channel_id": {
                    "description": "Which channel the message is in.",
                    "title": "Channel Id",
                    "type": "string"
                  },
                  "content": {
                    "default": "",
                    "description": "The text content of the message.",
                    "title": "Content",
                    "type": "string"
                  },
                  "message_id": {
                    "description": "The ID of the message.",
                    "title": "Message Id",
                    "type": "string"
                  },
                  "timestamp": {
                    "default": "",
                    "description": "ISO8601 timestamp of when the message was created.",
                    "title": "Timestamp",
                    "type": "string"
                  },
                  "username": {
                    "default": "",
                    "description": "Username of the message author.",
                    "title": "Username",
                    "type": "string"
                  }
                },
                "required": ["message_id", "channel_id"],
                "title": "Message",
                "type": "object"
              }
            },
            "required": ["message"],
            "title": "MessagePayload",
            "type": "object"
          },
          "slug": "DISCORD_NEW_MESSAGE_TRIGGER",
          "type": "poll"
        }
