# Auto-generated by Composio CLI. Do not modify manually..

class DOCPARSER:
    """Map of Composio's DOCPARSER toolkit."""

    slug: str = "docparser"

    class tools:
        GET_PARSER_MODELS = "DOCPARSER_GET_PARSER_MODELS"
        PING = "DOCPARSER_PING"
        GET_MULTIPLE_DOCUMENT_RESULTS = "DOCPARSER_GET_MULTIPLE_DOCUMENT_RESULTS"
        LIST_PARSERS = "DOCPARSER_LIST_PARSERS"

    class triggers:
        pass
