# Auto-generated by Composio CLI. Do not modify manually..

class DOCSUMO:
    """Map of Composio's DOCSUMO toolkit."""

    slug: str = "docsumo"

    class tools:
        GET_ENABLED_DOCUMENT_TYPES = "DOCSUMO_GET_ENABLED_DOCUMENT_TYPES"
        GET_USER_DOCUMENT_TYPES = "DOCSUMO_GET_USER_DOCUMENT_TYPES"
        POST_MCA_ANALYSIS = "DOCSUMO_POST_MCA_ANALYSIS"

    class triggers:
        pass
