# Auto-generated by Composio CLI. Do not modify manually..

class DOCUPILOT:
    """Map of Composio's DOCUPILOT toolkit."""

    slug: str = "docupilot"

    class tools:
        GET_AUTHENTICATED_USER = "DOCUPILOT_GET_AUTHENTICATED_USER"
        FOLDERS_CREATE = "DOCUPILOT_FOLDERS_CREATE"
        CREATE_FOLDER = "DOCUPILOT_CREATE_FOLDER"
        FOLDERS_LIST = "DOCUPILOT_FOLDERS_LIST"

    class triggers:
        pass
