# Auto-generated by Composio CLI. Do not modify manually..

class EMAILOCTOPUS:
    """Map of Composio's EMAILOCTOPUS toolkit."""

    slug: str = "emailoctopus"

    class tools:
        DELETE_CONTACT = "EMAILOCTOPUS_DELETE_CONTACT"
        UNSUBSCRIBE_CONTACT = "EMAILOCTOPUS_UNSUBSCRIBE_CONTACT"
        CREATE_LIST = "EMAILOCTOPUS_CREATE_LIST"
        DELETE_LIST = "EMAILOCTOPUS_DELETE_LIST"
        CREATE_CONTACT = "EMAILOCTOPUS_CREATE_CONTACT"
        GET_ALL_LISTS = "EMAILOCTOPUS_GET_ALL_LISTS"
        GET_RECENT_CAMPAIGNS = "EMAILOCTOPUS_GET_RECENT_CAMPAIGNS"

    class triggers:
        pass
