# Auto-generated by Composio CLI. Do not modify manually..

class ENTELLIGENCE:
    """Map of Composio's ENTELLIGENCE toolkit."""

    slug: str = "entelligence"

    class tools:
        ADD_A_NEW_REPOSITORY = "ENTELLIGENCE_ADD_A_NEW_REPOSITORY"
        INTERACT_WITH_THE_REPOSITORY_AGENT = "ENTELLIGENCE_INTERACT_WITH_THE_REPOSITORY_AGENT"

    class triggers:
        pass
