# Auto-generated by Composio CLI. Do not modify manually..

class EVENTEE:
    """Map of Composio's EVENTEE toolkit."""

    slug: str = "eventee"

    class tools:
        DELETE_SPEAKER = "EVENTEE_DELETE_SPEAKER"
        ADD_SPEAKER = "EVENTEE_ADD_SPEAKER"
        LIST_EVENTS = "EVENTEE_LIST_EVENTS"

    class triggers:
        pass
