# Auto-generated by Composio CLI. Do not modify manually..

class EVENIUM:
    """Map of Composio's EVENIUM toolkit."""

    slug: str = "evenium"

    class tools:
        GET_EVENTS = "EVENIUM_GET_EVENTS"
        GET_CONTACTS = "EVENIUM_GET_CONTACTS"
        LOGOUT = "EVENIUM_LOGOUT"

    class triggers:
        pass
