# Auto-generated by Composio CLI. Do not modify manually..

class FILES_COM:
    """Map of Composio's FILES_COM toolkit."""

    slug: str = "files_com"

    class tools:
        LIST_PERMISSIONS = "FILES_COM_LIST_PERMISSIONS"
        LIST_GROUPS = "FILES_COM_LIST_GROUPS"
        DELETE_API_KEY = "FILES_COM_DELETE_API_KEY"
        DELETE_SHARE = "FILES_COM_DELETE_SHARE"
        DELETE_PERMISSION = "FILES_COM_DELETE_PERMISSION"
        GET_S3_KEY_FOR_UPLOAD = "FILES_COM_GET_S3_KEY_FOR_UPLOAD"
        LIST_FOLDERS = "FILES_COM_LIST_FOLDERS"

    class triggers:
        pass
