# Auto-generated by Composio CLI. Do not modify manually..

class FINDYMAIL:
    """Map of Composio's FINDYMAIL toolkit."""

    slug: str = "findymail"

    class tools:
        DELETE_LIST = "FINDYMAIL_DELETE_LIST"
        CREATE_LIST = "FINDYMAIL_CREATE_LIST"
        LIST_CONTACTS = "FINDYMAIL_LIST_CONTACTS"
        VERIFY_EMAIL = "FINDYMAIL_VERIFY_EMAIL"
        GET_CONTACT_LISTS = "FINDYMAIL_GET_CONTACT_LISTS"
        FIND_EMAIL_BY_NAME = "FINDYMAIL_FIND_EMAIL_BY_NAME"

    class triggers:
        pass
