# Auto-generated by Composio CLI. Do not modify manually..

class FIXER_IO:
    """Map of Composio's FIXER_IO toolkit."""

    slug: str = "fixer_io"

    class tools:
        GET_TIME_SERIES = "FIXER_IO_GET_TIME_SERIES"
        GET_SUPPORTED_SYMBOLS = "FIXER_IO_GET_SUPPORTED_SYMBOLS"
        GET_HISTORICAL_RATES = "FIXER_IO_GET_HISTORICAL_RATES"
        CONVERT_CURRENCY = "FIXER_IO_CONVERT_CURRENCY"
        GET_FLUCTUATION = "FIXER_IO_GET_FLUCTUATION"
        GET_LATEST_RATES = "FIXER_IO_GET_LATEST_RATES"

    class triggers:
        pass
