# Auto-generated by Composio CLI. Do not modify manually..

class FOMO:
    """Map of Composio's FOMO toolkit."""

    slug: str = "fomo"

    class tools:
        GET_FOMO_EVENTS = "FOMO_GET_FOMO_EVENTS"

    class triggers:
        pass
