# Auto-generated by Composio CLI. Do not modify manually..

class FORMSITE:
    """Map of Composio's FORMSITE toolkit."""

    slug: str = "formsite"

    class tools:
        GET_FORM = "FORMSITE_GET_FORM"
        GET_FORM_ITEMS = "FORMSITE_GET_FORM_ITEMS"
        GET_WEBHOOKS = "FORMSITE_GET_WEBHOOKS"
        LIST_ALL_FORMS = "FORMSITE_LIST_ALL_FORMS"
        GET_FORM_RESULTS = "FORMSITE_GET_FORM_RESULTS"

    class triggers:
        pass
