# Auto-generated by Composio CLI. Do not modify manually..

class GEMINI:
    """Map of Composio's GEMINI toolkit."""

    slug: str = "gemini"

    class tools:
        WAIT_FOR_VIDEO = "GEMINI_WAIT_FOR_VIDEO"
        LIST_MODELS = "GEMINI_LIST_MODELS"
        GENERATE_IMAGE = "GEMINI_GENERATE_IMAGE"
        COUNT_TOKENS = "GEMINI_COUNT_TOKENS"
        EMBED_CONTENT = "GEMINI_EMBED_CONTENT"
        GENERATE_VIDEOS = "GEMINI_GENERATE_VIDEOS"
        GET_VIDEOS_OPERATION = "GEMINI_GET_VIDEOS_OPERATION"
        GENERATE_CONTENT = "GEMINI_GENERATE_CONTENT"

    class triggers:
        pass
