# Auto-generated by Composio CLI. Do not modify manually..

class GETFORM:
    """Map of Composio's GETFORM toolkit."""

    slug: str = "getform"

    class tools:
        GET_FORM_GET_SUBMISSIONS = "GETFORM_GET_FORM_GET_SUBMISSIONS"
        GET_FORM_GET_SUBMISSION = "GETFORM_GET_FORM_GET_SUBMISSION"
        GET_FORM_SUBMIT_FORM = "GETFORM_GET_FORM_SUBMIT_FORM"

    class triggers:
        pass
