# Auto-generated by Composio CLI. Do not modify manually..

class GOODBITS:
    """Map of Composio's GOODBITS toolkit."""

    slug: str = "goodbits"

    class tools:
        UPDATE_SUBSCRIBER_STATUS = "GOODBITS_UPDATE_SUBSCRIBER_STATUS"
        DELETE_SUBSCRIBER = "GOODBITS_DELETE_SUBSCRIBER"
        CREATE_SUBSCRIBER = "GOODBITS_CREATE_SUBSCRIBER"
        GET_NEWSLETTER = "GOODBITS_GET_NEWSLETTER"
        CREATE_LINK = "GOODBITS_CREATE_LINK"

    class triggers:
        pass
