# Auto-generated by Composio CLI. Do not modify manually..

class GOOGLECALENDAR:
    """Map of Composio's GOOGLECALENDAR toolkit."""

    slug: str = "googlecalendar"

    class tools:
        LIST_ACL_RULES = "GOOGLECALENDAR_LIST_ACL_RULES"
        EVENTS_WATCH = "GOOGLECALENDAR_EVENTS_WATCH"
        EVENTS_LIST_ALL_CALENDARS = "GOOGLECALENDAR_EVENTS_LIST_ALL_CALENDARS"
        FREE_BUSY_QUERY = "GOOGLECALENDAR_FREE_BUSY_QUERY"
        EVENTS_IMPORT = "GOOGLECALENDAR_EVENTS_IMPORT"
        UPDATE_EVENT = "GOOGLECALENDAR_UPDATE_EVENT"
        LIST_CALENDARS = "GOOGLECALENDAR_LIST_CALENDARS"
        CALENDAR_LIST_INSERT = "GOOGLECALENDAR_CALENDAR_LIST_INSERT"
        CALENDAR_LIST_GET = "GOOGLECALENDAR_CALENDAR_LIST_GET"
        CHANNELS_STOP = "GOOGLECALENDAR_CHANNELS_STOP"
        CALENDAR_LIST_DELETE = "GOOGLECALENDAR_CALENDAR_LIST_DELETE"
        CREATE_EVENT = "GOOGLECALENDAR_CREATE_EVENT"
        EVENTS_GET = "GOOGLECALENDAR_EVENTS_GET"
        QUICK_ADD = "GOOGLECALENDAR_QUICK_ADD"
        CALENDAR_LIST_WATCH = "GOOGLECALENDAR_CALENDAR_LIST_WATCH"
        CALENDARS_DELETE = "GOOGLECALENDAR_CALENDARS_DELETE"
        CALENDAR_LIST_UPDATE = "GOOGLECALENDAR_CALENDAR_LIST_UPDATE"
        SETTINGS_GET = "GOOGLECALENDAR_SETTINGS_GET"
        EVENTS_INSTANCES = "GOOGLECALENDAR_EVENTS_INSTANCES"
        DUPLICATE_CALENDAR = "GOOGLECALENDAR_DUPLICATE_CALENDAR"
        GET_CALENDAR = "GOOGLECALENDAR_GET_CALENDAR"
        CLEAR_CALENDAR = "GOOGLECALENDAR_CLEAR_CALENDAR"
        PATCH_CALENDAR = "GOOGLECALENDAR_PATCH_CALENDAR"
        SETTINGS_WATCH = "GOOGLECALENDAR_SETTINGS_WATCH"
        ACL_DELETE = "GOOGLECALENDAR_ACL_DELETE"
        EVENTS_LIST = "GOOGLECALENDAR_EVENTS_LIST"
        SYNC_EVENTS = "GOOGLECALENDAR_SYNC_EVENTS"
        GET_CURRENT_DATE_TIME = "GOOGLECALENDAR_GET_CURRENT_DATE_TIME"
        CALENDAR_LIST_LIST = "GOOGLECALENDAR_CALENDAR_LIST_LIST"
        ACL_INSERT = "GOOGLECALENDAR_ACL_INSERT"
        CALENDARS_UPDATE = "GOOGLECALENDAR_CALENDARS_UPDATE"
        REMOVE_ATTENDEE = "GOOGLECALENDAR_REMOVE_ATTENDEE"
        UPDATE_ACL_RULE = "GOOGLECALENDAR_UPDATE_ACL_RULE"
        SETTINGS_LIST = "GOOGLECALENDAR_SETTINGS_LIST"
        LIST_SETTINGS = "GOOGLECALENDAR_LIST_SETTINGS"
        COLORS_GET = "GOOGLECALENDAR_COLORS_GET"
        DELETE_EVENT = "GOOGLECALENDAR_DELETE_EVENT"
        FIND_FREE_SLOTS = "GOOGLECALENDAR_FIND_FREE_SLOTS"
        BATCH_EVENTS = "GOOGLECALENDAR_BATCH_EVENTS"
        CALENDAR_LIST_PATCH = "GOOGLECALENDAR_CALENDAR_LIST_PATCH"
        EVENTS_MOVE = "GOOGLECALENDAR_EVENTS_MOVE"
        FIND_EVENT = "GOOGLECALENDAR_FIND_EVENT"
        PATCH_EVENT = "GOOGLECALENDAR_PATCH_EVENT"
        ACL_WATCH = "GOOGLECALENDAR_ACL_WATCH"
        ACL_GET = "GOOGLECALENDAR_ACL_GET"
        ACL_PATCH = "GOOGLECALENDAR_ACL_PATCH"

    class triggers:
        ATTENDEE_RESPONSE_CHANGED_TRIGGER = {
          "config": {
            "description": "Configuration for Attendee Response Changed trigger",
            "properties": {
              "calendarId": {
                "default": "primary",
                "description": "The unique identifier for the calendar",
                "examples": ["primary", "example@gmail.com"],
                "title": "Calendar Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "maxResults": {
                "default": 10,
                "description": "Maximum number of events to retrieve per poll (1-50)",
                "examples": [10],
                "maximum": 50,
                "minimum": 1,
                "title": "Max Results",
                "type": "integer"
              },
              "showDeleted": {
                "default": True,
                "description": "Whether to include deleted events in the results",
                "examples": [True, False],
                "title": "Show Deleted",
                "type": "boolean"
              }
            },
            "title": "AttendeeResponseChangedConfig",
            "type": "object"
          },
          "description": "Polling trigger that fires when any attendee's RSVP changes to\n    accepted, declined, or tentative. Returns attendee info and current status.",
          "instructions": "Monitor a Google Calendar for attendee RSVP updates. This trigger checks events that were updated since the last poll and emits a payload whenever an attendee's response status changes to accepted, declined, or tentative. Provide the calendar ID (usually 'primary'). Default limit: 10 events per poll.",
          "name": "Attendee Response Changed",
          "payload": {
            "description": "Payload when an attendee RSVP changes",
            "properties": {
              "attendee_email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email of the attendee whose RSVP changed",
                "title": "Attendee Email"
              },
              "attendee_name": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Display name of the attendee",
                "title": "Attendee Name"
              },
              "calendar_id": {
                "description": "The calendar identifier",
                "title": "Calendar Id",
                "type": "string"
              },
              "event_html_link": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Link to the event in Google Calendar",
                "title": "Event Html Link"
              },
              "event_id": {
                "description": "The unique identifier of the event",
                "title": "Event Id",
                "type": "string"
              },
              "event_summary": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event title/summary",
                "title": "Event Summary"
              },
              "previous_response_status": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Previous RSVP status",
                "title": "Previous Response Status"
              },
              "response_status": {
                "description": "Current RSVP status (accepted, declined, tentative)",
                "title": "Response Status",
                "type": "string"
              }
            },
            "required": ["event_id", "calendar_id", "response_status"],
            "title": "AttendeeResponsePayload",
            "type": "object"
          },
          "slug": "GOOGLECALENDAR_ATTENDEE_RESPONSE_CHANGED_TRIGGER",
          "type": "poll"
        }
        EVENT_CANCELED_DELETED_TRIGGER = {
          "config": {
            "description": "Configuration for Google Calendar Event Canceled/Deleted polling trigger",
            "properties": {
              "calendarId": {
                "default": "primary",
                "description": "The unique identifier for the calendar to monitor",
                "examples": ["primary", "example@gmail.com"],
                "title": "Calendar Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "maxResults": {
                "default": 10,
                "description": "Maximum number of events to retrieve per poll (1-50)",
                "examples": [10],
                "maximum": 50,
                "minimum": 1,
                "title": "Max Results",
                "type": "integer"
              }
            },
            "title": "EventCanceledDeletedConfig",
            "type": "object"
          },
          "description": "Triggers when a Google Calendar event is cancelled or deleted.\n    Returns minimal data: event_id, summary (if available), and cancellation timestamp.",
          "instructions": "Monitors a Google Calendar and fires when an event is cancelled or deleted. Provide the calendar ID (use 'primary' for your main calendar). On the very first poll, no events are emitted (baseline sync).",
          "name": "Event Canceled or Deleted",
          "payload": {
            "description": "Payload returned when an event is canceled or deleted",
            "properties": {
              "cancelled_at": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Cancellation timestamp (from event.updated)",
                "title": "Cancelled At"
              },
              "event_id": {
                "description": "The unique identifier of the event",
                "title": "Event Id",
                "type": "string"
              },
              "summary": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event title/summary (may be missing for cancelled events)",
                "title": "Summary"
              }
            },
            "required": ["event_id"],
            "title": "EventCanceledDeletedPayload",
            "type": "object"
          },
          "slug": "GOOGLECALENDAR_EVENT_CANCELED_DELETED_TRIGGER",
          "type": "poll"
        }
        EVENT_STARTING_SOON_TRIGGER = {
          "config": {
            "description": "Configuration for Event Starting Soon polling trigger.",
            "properties": {
              "calendarId": {
                "default": "primary",
                "description": "The unique identifier for the calendar to monitor",
                "examples": ["primary", "user@example.com"],
                "title": "Calendar Id",
                "type": "string"
              },
              "countdown_window_minutes": {
                "default": 60,
                "description": "Look-ahead window (in minutes) for upcoming events to evaluate",
                "examples": [30, 60],
                "maximum": 4320,
                "minimum": 1,
                "title": "Countdown Window Minutes",
                "type": "integer"
              },
              "include_all_day": {
                "default": False,
                "description": "Whether to consider all-day events (default False)",
                "title": "Include All Day",
                "type": "boolean"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "maxResults": {
                "default": 50,
                "description": "Maximum number of events retrieved per poll (1-2500)",
                "maximum": 2500,
                "minimum": 1,
                "title": "Max Results",
                "type": "integer"
              },
              "minutes_before_start": {
                "default": 10,
                "description": "Trigger when an event is within this many minutes from starting",
                "examples": [5, 10, 15],
                "maximum": 1440,
                "minimum": 1,
                "title": "Minutes Before Start",
                "type": "integer"
              }
            },
            "title": "EventStartingSoonConfig",
            "type": "object"
          },
          "description": "Triggers when a calendar event is within a configured number of minutes from starting.\n    Includes countdown window, start time, and event metadata.",
          "instructions": "Configure minutes_before_start to decide when a notification should fire. Set countdown_window_minutes to control how far ahead the trigger scans for upcoming events. By default, all-day events are ignored; enable include_all_day to consider them (start of day).",
          "name": "Event Starting Soon",
          "payload": {
            "description": "Payload returned when an event is starting soon.",
            "properties": {
              "attendees": {
                "description": "List of attendees",
                "items": {
                  "additionalProperties": True,
                  "properties": {},
                  "type": "object"
                },
                "title": "Attendees",
                "type": "array"
              },
              "calendar_id": {
                "description": "The calendar identifier",
                "title": "Calendar Id",
                "type": "string"
              },
              "countdown_window_minutes": {
                "description": "Countdown window used for this trigger",
                "title": "Countdown Window Minutes",
                "type": "integer"
              },
              "creator_email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email of the event creator",
                "title": "Creator Email"
              },
              "description": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event description",
                "title": "Description"
              },
              "event_id": {
                "description": "The unique identifier of the event",
                "title": "Event Id",
                "type": "string"
              },
              "hangout_link": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Google Meet link for the conference, if available",
                "title": "Hangout Link"
              },
              "html_link": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Link to the event in Google Calendar",
                "title": "Html Link"
              },
              "location": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event location",
                "title": "Location"
              },
              "minutes_until_start": {
                "anyOf": [{
                    "type": "number"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Minutes remaining until event starts (>= 0)",
                "title": "Minutes Until Start"
              },
              "organizer_email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email of the event organizer",
                "title": "Organizer Email"
              },
              "start_time": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event start time in ISO format",
                "title": "Start Time"
              },
              "start_timestamp": {
                "anyOf": [{
                    "type": "number"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event start time as UNIX epoch timestamp (UTC)",
                "title": "Start Timestamp"
              },
              "summary": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event title/summary",
                "title": "Summary"
              }
            },
            "required": ["event_id", "calendar_id", "countdown_window_minutes"],
            "title": "EventStartingSoonPayload",
            "type": "object"
          },
          "slug": "GOOGLECALENDAR_EVENT_STARTING_SOON_TRIGGER",
          "type": "poll"
        }
        GOOGLE_CALENDAR_EVENT_CHANGE_TRIGGER = {
          "config": {
            "description": "No config needed for this webhook",
            "properties": {
              "calendar_id": {
                "default": "primary",
                "description": "The unique identifier for the calendar",
                "title": "Calendar Id",
                "type": "string"
              },
              "ttl": {
                "default": 604800,
                "description": "The time-to-live in seconds for the notification channel",
                "title": "Ttl",
                "type": "integer"
              }
            },
            "title": "GoogleCalendarTriggerConfig",
            "type": "object"
          },
          "description": "**SOON TO BE DEPRECATED** - Use Calendar Event Sync (polling trigger) instead.\n    Real-time webhook trigger for calendar event changes. Returns event metadata only.\n    For full event data, use Calendar Event Sync (polling trigger).",
          "instructions": "",
          "name": "Calendar Event Changes",
          "payload": {
            "description": "Data structure for Google Calendar event changes",
            "properties": {
              "channel_id": {
                "description": "The unique identifier passed to identify this channel",
                "title": "Channel Id",
                "type": "string"
              },
              "resource_id": {
                "description": "The unique identifier of the resource",
                "title": "Resource Id",
                "type": "string"
              },
              "resource_state": {
                "description": "The state of the resource",
                "title": "Resource State",
                "type": "string"
              },
              "resource_url": {
                "description": "The url for the resource",
                "title": "Resource Url",
                "type": "string"
              }
            },
            "required": ["resource_id", "resource_url", "resource_state", "channel_id"],
            "title": "GoogleCalendarEventChangePayload",
            "type": "object"
          },
          "slug": "GOOGLECALENDAR_GOOGLE_CALENDAR_EVENT_CHANGE_TRIGGER",
          "type": "webhook"
        }
        GOOGLE_CALENDAR_EVENT_CREATED_TRIGGER = {
          "config": {
            "description": "Configuration for Google Calendar 'Event Created' polling trigger",
            "properties": {
              "calendarId": {
                "default": "primary",
                "description": "The unique identifier for the calendar",
                "examples": ["primary", "example@gmail.com"],
                "title": "Calendar Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "maxResults": {
                "default": 10,
                "description": "Maximum number of events to retrieve per poll (1-50)",
                "examples": [10],
                "maximum": 50,
                "minimum": 1,
                "title": "Max Results",
                "type": "integer"
              },
              "showDeleted": {
                "default": False,
                "description": "Whether to include deleted events in the results",
                "examples": [False],
                "title": "Show Deleted",
                "type": "boolean"
              }
            },
            "title": "GoogleCalendarEventCreatedConfig",
            "type": "object"
          },
          "description": "Polling trigger that fires when a new calendar event is created.\n    Returns event ID, summary, start/end times, and organizer info.",
          "instructions": "This trigger monitors a Google Calendar and fires when a new event is created. Provide the calendar ID (use 'primary' for the main calendar). On the first run, the trigger initializes state and does not emit any events to avoid noise. Subsequent polls will return only newly created events since the last sync.",
          "name": "Event Created",
          "payload": {
            "description": "Payload structure for newly created Google Calendar event",
            "properties": {
              "calendar_id": {
                "description": "The calendar identifier",
                "title": "Calendar Id",
                "type": "string"
              },
              "end_time": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event end time in ISO format",
                "title": "End Time"
              },
              "event_id": {
                "description": "The unique identifier of the event",
                "title": "Event Id",
                "type": "string"
              },
              "organizer_email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email of the event organizer",
                "title": "Organizer Email"
              },
              "organizer_name": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Name of the event organizer",
                "title": "Organizer Name"
              },
              "start_time": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event start time in ISO format",
                "title": "Start Time"
              },
              "summary": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event title/summary",
                "title": "Summary"
              }
            },
            "required": ["event_id", "calendar_id"],
            "title": "GoogleCalendarEventCreatedPayload",
            "type": "object"
          },
          "slug": "GOOGLECALENDAR_GOOGLE_CALENDAR_EVENT_CREATED_TRIGGER",
          "type": "poll"
        }
        GOOGLE_CALENDAR_EVENT_SYNC_TRIGGER = {
          "config": {
            "description": "Configuration for Google Calendar event polling",
            "properties": {
              "calendarId": {
                "default": "primary",
                "description": "The unique identifier for the calendar",
                "examples": ["primary", "example@gmail.com"],
                "title": "Calendar Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "maxResults": {
                "default": 10,
                "description": "Maximum number of events to retrieve per poll (1-50)",
                "examples": [10],
                "maximum": 50,
                "minimum": 1,
                "title": "Max Results",
                "type": "integer"
              },
              "showDeleted": {
                "default": True,
                "description": "Whether to include deleted events in the results",
                "examples": [True, False],
                "title": "Show Deleted",
                "type": "boolean"
              }
            },
            "title": "GoogleCalendarEventSyncConfig",
            "type": "object"
          },
          "description": "Polling trigger that returns full event data including details, attendees, and metadata.\n    For real-time notifications with basic info, use Calendar Event Changes (webhook).",
          "instructions": "\n    **Calendar Event Sync (Polling):**\n    \n    - Returns complete event data: title, description, attendees, times, etc.\n    - Polls at intervals you configure (not real-time)\n    - Provide calendar ID (usually 'primary' for main calendar)\n    - Set show_deleted to true to capture deleted events\n    - Default limit: 10 events per poll (increase if needed)\n    ",
          "name": "Calendar Event Sync",
          "payload": {
            "description": "Payload structure for Google Calendar event sync",
            "properties": {
              "attendees": {
                "description": "List of attendees",
                "items": {
                  "additionalProperties": True,
                  "properties": {},
                  "type": "object"
                },
                "title": "Attendees",
                "type": "array"
              },
              "calendar_id": {
                "description": "The calendar identifier",
                "title": "Calendar Id",
                "type": "string"
              },
              "conference_data": {
                "anyOf": [{
                    "additionalProperties": True,
                    "type": "object"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Conference data structure containing details about the meeting",
                "title": "Conference Data"
              },
              "created_at": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "When the event was created",
                "title": "Created At"
              },
              "creator_email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email of the event creator",
                "title": "Creator Email"
              },
              "creator_name": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Name of the event creator",
                "title": "Creator Name"
              },
              "description": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event description",
                "title": "Description"
              },
              "end_time": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event end time in ISO format",
                "title": "End Time"
              },
              "event_id": {
                "description": "The unique identifier of the event",
                "title": "Event Id",
                "type": "string"
              },
              "event_type": {
                "description": "Type of change: created, updated, or deleted",
                "title": "Event Type",
                "type": "string"
              },
              "hangout_link": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Google Meet link for the conference, if available",
                "title": "Hangout Link"
              },
              "html_link": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Link to the event in Google Calendar",
                "title": "Html Link"
              },
              "location": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event location",
                "title": "Location"
              },
              "organizer_email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email of the event organizer",
                "title": "Organizer Email"
              },
              "organizer_name": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Name of the event organizer",
                "title": "Organizer Name"
              },
              "recurring_event_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "ID of recurring event if applicable",
                "title": "Recurring Event Id"
              },
              "start_time": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event start time in ISO format",
                "title": "Start Time"
              },
              "status": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event status (confirmed, tentative, cancelled)",
                "title": "Status"
              },
              "summary": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event title/summary",
                "title": "Summary"
              },
              "updated_at": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "When the event was last updated",
                "title": "Updated At"
              },
              "visibility": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Event visibility",
                "title": "Visibility"
              }
            },
            "required": ["event_id", "event_type", "calendar_id"],
            "title": "GoogleCalendarEventSyncPayload",
            "type": "object"
          },
          "slug": "GOOGLECALENDAR_GOOGLE_CALENDAR_EVENT_SYNC_TRIGGER",
          "type": "poll"
        }
        GOOGLE_CALENDAR_EVENT_UPDATED_TRIGGER = {
          "config": {
            "description": "Configuration for Google Calendar Event Updated polling trigger",
            "properties": {
              "calendarId": {
                "default": "primary",
                "description": "The unique identifier for the calendar",
                "examples": ["primary", "example@gmail.com"],
                "title": "Calendar Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "maxResults": {
                "default": 10,
                "description": "Maximum number of events to retrieve per poll (1-50)",
                "examples": [10],
                "maximum": 50,
                "minimum": 1,
                "title": "Max Results",
                "type": "integer"
              },
              "showDeleted": {
                "default": True,
                "description": "Whether to include deleted (cancelled) events in the results",
                "examples": [True, False],
                "title": "Show Deleted",
                "type": "boolean"
              },
              "tracked_fields": {
                "description": "List of event fields to track for changes. start and end are compared as RFC3339 strings (preferring dateTime over date). Attendees are compared by email, displayName, responseStatus, and optional flag.",
                "items": {
                  "properties": {},
                  "type": "string"
                },
                "title": "Tracked Fields",
                "type": "array"
              }
            },
            "title": "GoogleCalendarEventUpdatedConfig",
            "type": "object"
          },
          "description": "Triggers when an existing Google Calendar event is modified. Returns the event ID,\n    change type, and the specific fields that changed with their previous and new values.",
          "instructions": "This trigger monitors a Google Calendar for changes to existing events.\n- Specify the calendar ID (default: 'primary').\n- On the very first run, the trigger initializes and does not emit events.\n- Subsequent polls return only events that were modified since the last sync.\n- The payload includes the event ID, change type (updated), and per-field changes (old/new).",
          "name": "Event Updated",
          "payload": {
            "description": "Payload for an updated event.",
            "properties": {
              "calendar_id": {
                "description": "The calendar identifier",
                "title": "Calendar Id",
                "type": "string"
              },
              "change_type": {
                "default": "updated",
                "description": "Type of change. Always 'updated' for this trigger",
                "title": "Change Type",
                "type": "string"
              },
              "event_id": {
                "description": "The unique identifier of the event",
                "title": "Event Id",
                "type": "string"
              },
              "updated_at": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "When the event was last updated (RFC3339)",
                "title": "Updated At"
              },
              "updated_fields": {
                "additionalProperties": {
                  "additionalProperties": True,
                  "type": "object"
                },
                "description": "Dictionary of changed fields with old and new values",
                "title": "Updated Fields",
                "type": "object"
              }
            },
            "required": ["event_id", "updated_fields", "calendar_id"],
            "title": "GoogleCalendarEventUpdatedPayload",
            "type": "object"
          },
          "slug": "GOOGLECALENDAR_GOOGLE_CALENDAR_EVENT_UPDATED_TRIGGER",
          "type": "poll"
        }
