# Auto-generated by Composio CLI. Do not modify manually..

class GOOGLESLIDES:
    """Map of Composio's GOOGLESLIDES toolkit."""

    slug: str = "googleslides"

    class tools:
        PRESENTATIONS_PAGES_GET_THUMBNAIL = "GOOGLESLIDES_PRESENTATIONS_PAGES_GET_THUMBNAIL"
        PRESENTATIONS_CREATE = "GOOGLESLIDES_PRESENTATIONS_CREATE"
        PRESENTATIONS_GET = "GOOGLESLIDES_PRESENTATIONS_GET"
        PRESENTATIONS_COPY_FROM_TEMPLATE = "GOOGLESLIDES_PRESENTATIONS_COPY_FROM_TEMPLATE"
        PRESENTATIONS_BATCH_UPDATE = "GOOGLESLIDES_PRESENTATIONS_BATCH_UPDATE"
        CREATE_SLIDES_MARKDOWN = "GOOGLESLIDES_CREATE_SLIDES_MARKDOWN"
        PRESENTATIONS_PAGES_GET = "GOOGLESLIDES_PRESENTATIONS_PAGES_GET"

    class triggers:
        SLIDE_ADDED_TRIGGER = {
          "config": {
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "presentation_id": {
                "description": "The ID of the presentation to monitor for new slides",
                "title": "Presentation Id",
                "type": "string"
              }
            },
            "required": ["presentation_id"],
            "title": "SlideAddedConfig",
            "type": "object"
          },
          "description": "Fires when a new slide is added to a Google Slides presentation.",
          "instructions": "\n**Instructions for Setting Up the Trigger:**\n\n- Provide the presentation ID you want to monitor.\n- This trigger will poll the presentation for new slides and fire when a new slide is added.\n- You can get the presentation ID from the Google Slides URL or via the Get Presentation action.\n    ",
          "name": "New Slide Added",
          "payload": {
            "description": "Payload model for new slide events.",
            "properties": {
              "event_type": {
                "default": "slide_added",
                "description": "Type of slide event",
                "title": "Event Type",
                "type": "string"
              },
              "slide": {
                "additionalProperties": True,
                "description": "The slide object that was added",
                "title": "Slide",
                "type": "object"
              }
            },
            "required": ["slide"],
            "title": "SlidePayload",
            "type": "object"
          },
          "slug": "GOOGLESLIDES_SLIDE_ADDED_TRIGGER",
          "type": "poll"
        }
