# Auto-generated by Composio CLI. Do not modify manually..

class GRAPHHOPPER:
    """Map of Composio's GRAPHHOPPER toolkit."""

    slug: str = "graphhopper"

    class tools:
        ROUTE_POST = "GRAPHHOPPER_ROUTE_POST"
        CLUSTER_POST = "GRAPHHOPPER_CLUSTER_POST"
        GEOCODE_GET = "GRAPHHOPPER_GEOCODE_GET"
        ISOCHRONE_GET = "GRAPHHOPPER_ISOCHRONE_GET"
        UPLOAD_GPX_FILE = "GRAPHHOPPER_UPLOAD_GPX_FILE"
        MATRIX_POST = "GRAPHHOPPER_MATRIX_POST"
        VRP_POST = "GRAPHHOPPER_VRP_POST"
        PROFILES_GET = "GRAPHHOPPER_PROFILES_GET"

    class triggers:
        pass
