# Auto-generated by Composio CLI. Do not modify manually..

class HACKERNEWS:
    """Map of Composio's HACKERNEWS toolkit."""

    slug: str = "hackernews"

    class tools:
        GET_FRONTPAGE = "HACKERNEWS_GET_FRONTPAGE"
        SEARCH_POSTS = "HACKERNEWS_SEARCH_POSTS"
        GET_LATEST_POSTS = "HACKERNEWS_GET_LATEST_POSTS"
        GET_USER = "HACKERNEWS_GET_USER"
        GET_TODAYS_POSTS = "HACKERNEWS_GET_TODAYS_POSTS"
        GET_ITEM_WITH_ID = "HACKERNEWS_GET_ITEM_WITH_ID"

    class triggers:
        pass
