# Auto-generated by Composio CLI. Do not modify manually..

class HYPERISE:
    """Map of Composio's HYPERISE toolkit."""

    slug: str = "hyperise"

    class tools:
        USER_AUTHENTICATION = "HYPERISE_USER_AUTHENTICATION"
        LIST_IMAGE_TEMPLATES = "HYPERISE_LIST_IMAGE_TEMPLATES"
        CREATE_CLIENT_ACCOUNT = "HYPERISE_CREATE_CLIENT_ACCOUNT"
        PROSPECT_BUSINESS_DATA = "HYPERISE_PROSPECT_BUSINESS_DATA"
        PERSONALIZED_SHORT_LINKS = "HYPERISE_PERSONALIZED_SHORT_LINKS"

    class triggers:
        pass
