# Auto-generated by Composio CLI. Do not modify manually..

class HYPEAUDITOR:
    """Map of Composio's HYPEAUDITOR toolkit."""

    slug: str = "hypeauditor"

    class tools:
        GET_REPORT_INSTAGRAM = "HYPEAUDITOR_GET_REPORT_INSTAGRAM"
        GET_ACCOUNT_MEDIA = "HYPEAUDITOR_GET_ACCOUNT_MEDIA"
        GET_REPORT_TIK_TOK = "HYPEAUDITOR_GET_REPORT_TIK_TOK"

    class triggers:
        pass
