# Auto-generated by Composio CLI. Do not modify manually..

class HYSTRUCT:
    """Map of Composio's HYSTRUCT toolkit."""

    slug: str = "hystruct"

    class tools:
        LIST_ALL_WEBHOOKS = "HYSTRUCT_LIST_ALL_WEBHOOKS"

    class triggers:
        pass
