# Auto-generated by Composio CLI. Do not modify manually..

class IMAGIOR:
    """Map of Composio's IMAGIOR toolkit."""

    slug: str = "imagior"

    class tools:
        LIST_TEMPLATES = "IMAGIOR_LIST_TEMPLATES"

    class triggers:
        pass
