# Auto-generated by Composio CLI. Do not modify manually..

class IMGBB:
    """Map of Composio's IMGBB toolkit."""

    slug: str = "imgbb"

    class tools:
        UPLOAD_IMAGE = "IMGBB_UPLOAD_IMAGE"
        GET_API_KEY = "IMGBB_GET_API_KEY"

    class triggers:
        pass
