# Auto-generated by Composio CLI. Do not modify manually..

class IP2PROXY:
    """Map of Composio's IP2PROXY toolkit."""

    slug: str = "ip2proxy"

    class tools:
        CHECK_PROXY = "IP2PROXY_CHECK_PROXY"

    class triggers:
        pass
