# Auto-generated by Composio CLI. Do not modify manually..

class L2S:
    """Map of Composio's L2S toolkit."""

    slug: str = "l2s"

    class tools:
        L2_S_LIST_URLS = "L2S_L2_S_LIST_URLS"
        GET_URL_DETAILS = "L2S_GET_URL_DETAILS"
        L2_S_SHORTEN_URL = "L2S_L2_S_SHORTEN_URL"
        L2_S_GET_USER_SETTINGS = "L2S_L2_S_GET_USER_SETTINGS"

    class triggers:
        pass
