# Auto-generated by Composio CLI. Do not modify manually..

class LEADFEEDER:
    """Map of Composio's LEADFEEDER toolkit."""

    slug: str = "leadfeeder"

    class tools:
        GET_CUSTOM_FEEDS = "LEADFEEDER_GET_CUSTOM_FEEDS"
        GET_COMPANY_INFO_BY_IP = "LEADFEEDER_GET_COMPANY_INFO_BY_IP"
        GET_ALL_VISITS = "LEADFEEDER_GET_ALL_VISITS"
        GET_ACCOUNTS = "LEADFEEDER_GET_ACCOUNTS"

    class triggers:
        pass
