# Auto-generated by Composio CLI. Do not modify manually..

class MAILCHIMP:
    """Map of Composio's MAILCHIMP toolkit."""

    slug: str = "mailchimp"

    class tools:
        DELETE_PRODUCT_IMAGE = "MAILCHIMP_DELETE_PRODUCT_IMAGE"
        LIST_ACCOUNT_ORDERS = "MAILCHIMP_LIST_ACCOUNT_ORDERS"
        GET_CAMPAIGN_FOLDER = "MAILCHIMP_GET_CAMPAIGN_FOLDER"
        ADD_CART_LINE_ITEM = "MAILCHIMP_ADD_CART_LINE_ITEM"
        GET_CAMPAIGN_SEND_CHECKLIST = "MAILCHIMP_GET_CAMPAIGN_SEND_CHECKLIST"
        ADD_ORDER_LINE_ITEM = "MAILCHIMP_ADD_ORDER_LINE_ITEM"
        LIST_CUSTOMERS = "MAILCHIMP_LIST_CUSTOMERS"
        GET_SUBSCRIBER_REMOVED_FROM_WORKFLOW = "MAILCHIMP_GET_SUBSCRIBER_REMOVED_FROM_WORKFLOW"
        SEARCH_FOR_TAGS_ON_A_LIST_BY_NAME = "MAILCHIMP_SEARCH_FOR_TAGS_ON_A_LIST_BY_NAME"
        CUSTOMER_JOURNEYS_API_TRIGGER_FOR_A_CONTACT = "MAILCHIMP_CUSTOMER_JOURNEYS_API_TRIGGER_FOR_A_CONTACT"
        GET_MEMBER_NOTE = "MAILCHIMP_GET_MEMBER_NOTE"
        UNPUBLISH_LANDING_PAGE = "MAILCHIMP_UNPUBLISH_LANDING_PAGE"
        CUSTOMIZE_SIGNUP_FORM = "MAILCHIMP_CUSTOMIZE_SIGNUP_FORM"
        GET_LANDING_PAGE_CONTENT = "MAILCHIMP_GET_LANDING_PAGE_CONTENT"
        DELETE_ORDER = "MAILCHIMP_DELETE_ORDER"
        VIEW_RECENT_ACTIVITY50 = "MAILCHIMP_VIEW_RECENT_ACTIVITY50"
        GET_WEBHOOK_INFO = "MAILCHIMP_GET_WEBHOOK_INFO"
        DELETE_BATCH_WEBHOOK = "MAILCHIMP_DELETE_BATCH_WEBHOOK"
        LIST_INTERESTS_IN_CATEGORY = "MAILCHIMP_LIST_INTERESTS_IN_CATEGORY"
        ADD_FILE = "MAILCHIMP_ADD_FILE"
        GET_CAMPAIGN_REPORT = "MAILCHIMP_GET_CAMPAIGN_REPORT"
        LIST_ORDERS = "MAILCHIMP_LIST_ORDERS"
        LIST_FACEBOOK_ADS = "MAILCHIMP_LIST_FACEBOOK_ADS"
        LIST_FACEBOOK_ADS_REPORTS = "MAILCHIMP_LIST_FACEBOOK_ADS_REPORTS"
        GET_CONNECTED_SITE = "MAILCHIMP_GET_CONNECTED_SITE"
        ADD_INTEREST_IN_CATEGORY = "MAILCHIMP_ADD_INTEREST_IN_CATEGORY"
        LIST_MEMBERS_INFO = "MAILCHIMP_LIST_MEMBERS_INFO"
        DELETE_CONNECTED_SITE = "MAILCHIMP_DELETE_CONNECTED_SITE"
        ADD_MEMBER_TO_SEGMENT = "MAILCHIMP_ADD_MEMBER_TO_SEGMENT"
        LIST_ANSWERS_FOR_QUESTION = "MAILCHIMP_LIST_ANSWERS_FOR_QUESTION"
        LIST_TEMPLATES = "MAILCHIMP_LIST_TEMPLATES"
        GET_CART_INFO = "MAILCHIMP_GET_CART_INFO"
        LIST_SURVEY_QUESTION_REPORTS = "MAILCHIMP_LIST_SURVEY_QUESTION_REPORTS"
        GET_SURVEY_RESPONSE = "MAILCHIMP_GET_SURVEY_RESPONSE"
        DELETE_SEGMENT = "MAILCHIMP_DELETE_SEGMENT"
        GET_PRODUCT_VARIANT_INFO = "MAILCHIMP_GET_PRODUCT_VARIANT_INFO"
        UNSCHEDULE_CAMPAIGN = "MAILCHIMP_UNSCHEDULE_CAMPAIGN"
        LIST_STORED_FILES = "MAILCHIMP_LIST_STORED_FILES"
        GET_FACEBOOK_AD_INFO = "MAILCHIMP_GET_FACEBOOK_AD_INFO"
        BATCH_ADD_OR_REMOVE_MEMBERS = "MAILCHIMP_BATCH_ADD_OR_REMOVE_MEMBERS"
        LIST_CAMPAIGN_RECIPIENTS = "MAILCHIMP_LIST_CAMPAIGN_RECIPIENTS"
        UPDATE_INTEREST_CATEGORY = "MAILCHIMP_UPDATE_INTEREST_CATEGORY"
        ADD_PRODUCT = "MAILCHIMP_ADD_PRODUCT"
        LIST_MERGE_FIELDS = "MAILCHIMP_LIST_MERGE_FIELDS"
        LIST_CAMPAIGN_PRODUCT_ACTIVITY = "MAILCHIMP_LIST_CAMPAIGN_PRODUCT_ACTIVITY"
        PAUSE_AUTOMATED_EMAIL = "MAILCHIMP_PAUSE_AUTOMATED_EMAIL"
        CREATE_A_SURVEY_CAMPAIGN = "MAILCHIMP_CREATE_A_SURVEY_CAMPAIGN"
        GET_PROMO_CODE = "MAILCHIMP_GET_PROMO_CODE"
        DELETE_BATCH_REQUEST = "MAILCHIMP_DELETE_BATCH_REQUEST"
        UPDATE_CART = "MAILCHIMP_UPDATE_CART"
        DELETE_PROMO_RULE = "MAILCHIMP_DELETE_PROMO_RULE"
        GET_SEGMENT_INFO = "MAILCHIMP_GET_SEGMENT_INFO"
        DELETE_CART_LINE_ITEM = "MAILCHIMP_DELETE_CART_LINE_ITEM"
        GET_CAMPAIGN_CONTENT = "MAILCHIMP_GET_CAMPAIGN_CONTENT"
        GET_INTEREST_CATEGORY_INFO = "MAILCHIMP_GET_INTEREST_CATEGORY_INFO"
        UPDATE_WEBHOOK = "MAILCHIMP_UPDATE_WEBHOOK"
        DELETE_CART = "MAILCHIMP_DELETE_CART"
        LIST_BATCH_REQUESTS = "MAILCHIMP_LIST_BATCH_REQUESTS"
        DELETE_PRODUCT = "MAILCHIMP_DELETE_PRODUCT"
        UPDATE_BATCH_WEBHOOK = "MAILCHIMP_UPDATE_BATCH_WEBHOOK"
        DELETE_FILE = "MAILCHIMP_DELETE_FILE"
        CANCEL_CAMPAIGN = "MAILCHIMP_CANCEL_CAMPAIGN"
        ADD_PROMO_CODE = "MAILCHIMP_ADD_PROMO_CODE"
        REPLICATE_CAMPAIGN = "MAILCHIMP_REPLICATE_CAMPAIGN"
        RESUME_RSS_CAMPAIGN = "MAILCHIMP_RESUME_RSS_CAMPAIGN"
        UPDATE_PRODUCT_IMAGE = "MAILCHIMP_UPDATE_PRODUCT_IMAGE"
        UPDATE_STORE = "MAILCHIMP_UPDATE_STORE"
        LIST_CARTS = "MAILCHIMP_LIST_CARTS"
        GET_ORDER_INFO = "MAILCHIMP_GET_ORDER_INFO"
        GET_MERGE_FIELD = "MAILCHIMP_GET_MERGE_FIELD"
        GET_LISTS_INFO = "MAILCHIMP_GET_LISTS_INFO"
        UPDATE_CUSTOMER = "MAILCHIMP_UPDATE_CUSTOMER"
        GET_CONVERSATION = "MAILCHIMP_GET_CONVERSATION"
        RETRIEVE_FOLDER_CONTENTS = "MAILCHIMP_RETRIEVE_FOLDER_CONTENTS"
        ARCHIVE_LIST_MEMBER = "MAILCHIMP_ARCHIVE_LIST_MEMBER"
        DELETE_PROMO_CODE = "MAILCHIMP_DELETE_PROMO_CODE"
        ADD_MEMBER_NOTE = "MAILCHIMP_ADD_MEMBER_NOTE"
        LIST_PRODUCT = "MAILCHIMP_LIST_PRODUCT"
        DELETE_PRODUCT_VARIANT = "MAILCHIMP_DELETE_PRODUCT_VARIANT"
        DELETE_ORDER_LINE_ITEM = "MAILCHIMP_DELETE_ORDER_LINE_ITEM"
        DELETE_WORKFLOW_EMAIL = "MAILCHIMP_DELETE_WORKFLOW_EMAIL"
        ADD_MEMBER_TO_LIST = "MAILCHIMP_ADD_MEMBER_TO_LIST"
        GET_TEMPLATE_FOLDER = "MAILCHIMP_GET_TEMPLATE_FOLDER"
        ADD_LIST = "MAILCHIMP_ADD_LIST"
        LIST_LANDING_PAGES_REPORTS = "MAILCHIMP_LIST_LANDING_PAGES_REPORTS"
        GET_BATCH_OPERATION_STATUS = "MAILCHIMP_GET_BATCH_OPERATION_STATUS"
        BATCH_SUBSCRIBE_OR_UNSUBSCRIBE = "MAILCHIMP_BATCH_SUBSCRIBE_OR_UNSUBSCRIBE"
        GET_LANDING_PAGE_REPORT = "MAILCHIMP_GET_LANDING_PAGE_REPORT"
        LIST_UNSUBSCRIBED_MEMBERS = "MAILCHIMP_LIST_UNSUBSCRIBED_MEMBERS"
        ADD_LANDING_PAGE = "MAILCHIMP_ADD_LANDING_PAGE"
        LIST_API_ROOT_RESOURCES = "MAILCHIMP_LIST_API_ROOT_RESOURCES"
        UPDATE_LISTS = "MAILCHIMP_UPDATE_LISTS"
        DELETE_CAMPAIGN = "MAILCHIMP_DELETE_CAMPAIGN"
        UPDATE_CAMPAIGN_FEEDBACK_MESSAGE = "MAILCHIMP_UPDATE_CAMPAIGN_FEEDBACK_MESSAGE"
        GET_ACCOUNT_EXPORT_INFO = "MAILCHIMP_GET_ACCOUNT_EXPORT_INFO"
        LIST_CAMPAIGN_DETAILS = "MAILCHIMP_LIST_CAMPAIGN_DETAILS"
        PING = "MAILCHIMP_PING"
        GET_MESSAGE = "MAILCHIMP_GET_MESSAGE"
        LIST_CAMPAIGN_REPORTS = "MAILCHIMP_LIST_CAMPAIGN_REPORTS"
        LIST_FACEBOOK_ECOMMERCE_REPORT = "MAILCHIMP_LIST_FACEBOOK_ECOMMERCE_REPORT"
        LIST_MEMBER_TAGS = "MAILCHIMP_LIST_MEMBER_TAGS"
        LIST_ACCOUNT_EXPORTS = "MAILCHIMP_LIST_ACCOUNT_EXPORTS"
        DELETE_FOLDER = "MAILCHIMP_DELETE_FOLDER"
        LIST_LOCATIONS = "MAILCHIMP_LIST_LOCATIONS"
        PUBLISH_A_SURVEY = "MAILCHIMP_PUBLISH_A_SURVEY"
        GET_LANDING_PAGE_INFO = "MAILCHIMP_GET_LANDING_PAGE_INFO"
        UPDATE_MERGE_FIELD = "MAILCHIMP_UPDATE_MERGE_FIELD"
        ADD_CAMPAIGN_FOLDER = "MAILCHIMP_ADD_CAMPAIGN_FOLDER"
        VIEW_DEFAULT_CONTENT = "MAILCHIMP_VIEW_DEFAULT_CONTENT"
        GET_CUSTOMER_INFO = "MAILCHIMP_GET_CUSTOMER_INFO"
        LIST_EEP_URL_ACTIVITY = "MAILCHIMP_LIST_EEP_URL_ACTIVITY"
        DELETE_TEMPLATE = "MAILCHIMP_DELETE_TEMPLATE"
        DELETE_STORE = "MAILCHIMP_DELETE_STORE"
        ADD_TEMPLATE_FOLDER = "MAILCHIMP_ADD_TEMPLATE_FOLDER"
        LIST_STORES = "MAILCHIMP_LIST_STORES"
        UPDATE_CAMPAIGN_SETTINGS = "MAILCHIMP_UPDATE_CAMPAIGN_SETTINGS"
        LIST_ORDER_LINE_ITEMS = "MAILCHIMP_LIST_ORDER_LINE_ITEMS"
        GET_ORDER_LINE_ITEM = "MAILCHIMP_GET_ORDER_LINE_ITEM"
        LIST_FOLDERS = "MAILCHIMP_LIST_FOLDERS"
        SET_CAMPAIGN_CONTENT = "MAILCHIMP_SET_CAMPAIGN_CONTENT"
        LIST_CONNECTED_SITES = "MAILCHIMP_LIST_CONNECTED_SITES"
        ADD_INTEREST_CATEGORY = "MAILCHIMP_ADD_INTEREST_CATEGORY"
        LIST_SEGMENTS = "MAILCHIMP_LIST_SEGMENTS"
        LIST_CONVERSATIONS = "MAILCHIMP_LIST_CONVERSATIONS"
        LIST_BATCH_WEBHOOKS = "MAILCHIMP_LIST_BATCH_WEBHOOKS"
        ADD_CONNECTED_SITE = "MAILCHIMP_ADD_CONNECTED_SITE"
        UPDATE_NOTE = "MAILCHIMP_UPDATE_NOTE"
        LIST_MEMBER_EVENTS = "MAILCHIMP_LIST_MEMBER_EVENTS"
        GET_SURVEY = "MAILCHIMP_GET_SURVEY"
        LIST_CAMPAIGN_FEEDBACK = "MAILCHIMP_LIST_CAMPAIGN_FEEDBACK"
        ADD_AUTOMATION = "MAILCHIMP_ADD_AUTOMATION"
        ADD_PRODUCT_IMAGE = "MAILCHIMP_ADD_PRODUCT_IMAGE"
        GET_SURVEY_REPORT = "MAILCHIMP_GET_SURVEY_REPORT"
        GET_FOLDER = "MAILCHIMP_GET_FOLDER"
        CAMPAIGN_ABUSE_REPORT_DETAILS = "MAILCHIMP_CAMPAIGN_ABUSE_REPORT_DETAILS"
        ADD_TEMPLATE = "MAILCHIMP_ADD_TEMPLATE"
        LIST_SENDING_DOMAINS = "MAILCHIMP_LIST_SENDING_DOMAINS"
        SEARCH_MEMBERS = "MAILCHIMP_SEARCH_MEMBERS"
        GET_WORKFLOW_EMAIL_INFO = "MAILCHIMP_GET_WORKFLOW_EMAIL_INFO"
        LIST_ABUSE_REPORTS = "MAILCHIMP_LIST_ABUSE_REPORTS"
        LIST_WEBHOOKS = "MAILCHIMP_LIST_WEBHOOKS"
        VIEW_RECENT_ACTIVITY = "MAILCHIMP_VIEW_RECENT_ACTIVITY"
        UPDATE_LANDING_PAGE = "MAILCHIMP_UPDATE_LANDING_PAGE"
        ADD_PRODUCT_VARIANT = "MAILCHIMP_ADD_PRODUCT_VARIANT"
        ARCHIVE_AUTOMATION = "MAILCHIMP_ARCHIVE_AUTOMATION"
        GET_LIST_INFO = "MAILCHIMP_GET_LIST_INFO"
        DELETE_CAMPAIGN_FEEDBACK_MESSAGE = "MAILCHIMP_DELETE_CAMPAIGN_FEEDBACK_MESSAGE"
        LIST_TOP_EMAIL_CLIENTS = "MAILCHIMP_LIST_TOP_EMAIL_CLIENTS"
        ADD_PROMO_RULE = "MAILCHIMP_ADD_PROMO_RULE"
        UPDATE_ORDER = "MAILCHIMP_UPDATE_ORDER"
        ADD_EVENT = "MAILCHIMP_ADD_EVENT"
        LIST_TOP_OPEN_ACTIVITIES = "MAILCHIMP_LIST_TOP_OPEN_ACTIVITIES"
        GET_AUTOMATED_EMAIL_SUBSCRIBER = "MAILCHIMP_GET_AUTOMATED_EMAIL_SUBSCRIBER"
        UPDATE_LIST_MEMBER = "MAILCHIMP_UPDATE_LIST_MEMBER"
        UPDATE_ORDER_LINE_ITEM = "MAILCHIMP_UPDATE_ORDER_LINE_ITEM"
        ADD_MERGE_FIELD = "MAILCHIMP_ADD_MERGE_FIELD"
        GET_AUTHORIZED_APP_INFO = "MAILCHIMP_GET_AUTHORIZED_APP_INFO"
        GET_CAMPAIGN_RECIPIENT_INFO = "MAILCHIMP_GET_CAMPAIGN_RECIPIENT_INFO"
        LIST_PRODUCT_VARIANTS = "MAILCHIMP_LIST_PRODUCT_VARIANTS"
        UPDATE_PRODUCT_VARIANT = "MAILCHIMP_UPDATE_PRODUCT_VARIANT"
        DELETE_LANDING_PAGE = "MAILCHIMP_DELETE_LANDING_PAGE"
        GET_FACEBOOK_AD_REPORT = "MAILCHIMP_GET_FACEBOOK_AD_REPORT"
        GET_UNSUBSCRIBED_MEMBER = "MAILCHIMP_GET_UNSUBSCRIBED_MEMBER"
        LIST_CAMPAIGNS = "MAILCHIMP_LIST_CAMPAIGNS"
        LIST_CAMPAIGN_OPEN_DETAILS = "MAILCHIMP_LIST_CAMPAIGN_OPEN_DETAILS"
        UPDATE_PRODUCT = "MAILCHIMP_UPDATE_PRODUCT"
        ADD_CAMPAIGN_FEEDBACK = "MAILCHIMP_ADD_CAMPAIGN_FEEDBACK"
        LIST_TEMPLATE_FOLDERS = "MAILCHIMP_LIST_TEMPLATE_FOLDERS"
        GET_SUBSCRIBER_EMAIL_ACTIVITY = "MAILCHIMP_GET_SUBSCRIBER_EMAIL_ACTIVITY"
        DELETE_DOMAIN = "MAILCHIMP_DELETE_DOMAIN"
        GET_ABUSE_REPORT = "MAILCHIMP_GET_ABUSE_REPORT"
        DELETE_MERGE_FIELD = "MAILCHIMP_DELETE_MERGE_FIELD"
        DELETE_CAMPAIGN_FOLDER = "MAILCHIMP_DELETE_CAMPAIGN_FOLDER"
        ADD_OR_UPDATE_CUSTOMER = "MAILCHIMP_ADD_OR_UPDATE_CUSTOMER"
        ADD_OR_UPDATE_PRODUCT_VARIANT = "MAILCHIMP_ADD_OR_UPDATE_PRODUCT_VARIANT"
        LIST_RECENT_MEMBER_NOTES = "MAILCHIMP_LIST_RECENT_MEMBER_NOTES"
        ADD_SUBSCRIBER_TO_WORKFLOW_EMAIL = "MAILCHIMP_ADD_SUBSCRIBER_TO_WORKFLOW_EMAIL"
        PAUSE_RSS_CAMPAIGN = "MAILCHIMP_PAUSE_RSS_CAMPAIGN"
        GET_INFORMATION_ABOUT_ALL_SURVEYS_FOR_A_LIST = "MAILCHIMP_GET_INFORMATION_ABOUT_ALL_SURVEYS_FOR_A_LIST"
        LIST_MESSAGES = "MAILCHIMP_LIST_MESSAGES"
        UNPUBLISH_A_SURVEY = "MAILCHIMP_UNPUBLISH_A_SURVEY"
        CAMPAIGN_STATISTICS_FEEDBACK = "MAILCHIMP_CAMPAIGN_STATISTICS_FEEDBACK"
        ADD_WEBHOOK = "MAILCHIMP_ADD_WEBHOOK"
        REMOVE_LIST_MEMBER_FROM_SEGMENT = "MAILCHIMP_REMOVE_LIST_MEMBER_FROM_SEGMENT"
        UPDATE_TEMPLATE_FOLDER = "MAILCHIMP_UPDATE_TEMPLATE_FOLDER"
        LIST_EMAIL_ACTIVITY = "MAILCHIMP_LIST_EMAIL_ACTIVITY"
        UPDATE_FOLDER = "MAILCHIMP_UPDATE_FOLDER"
        LIST_CHILD_CAMPAIGN_REPORTS = "MAILCHIMP_LIST_CHILD_CAMPAIGN_REPORTS"
        GET_STORE_INFO = "MAILCHIMP_GET_STORE_INFO"
        ADD_ORDER = "MAILCHIMP_ADD_ORDER"
        UPDATE_INTEREST_IN_CATEGORY = "MAILCHIMP_UPDATE_INTEREST_IN_CATEGORY"
        UPDATE_CAMPAIGN_FOLDER = "MAILCHIMP_UPDATE_CAMPAIGN_FOLDER"
        RETRIEVE_CAMPAIGN_ABUSE_COMPLAINTS = "MAILCHIMP_RETRIEVE_CAMPAIGN_ABUSE_COMPLAINTS"
        GET_CAMPAIGN_LINK_DETAILS = "MAILCHIMP_GET_CAMPAIGN_LINK_DETAILS"
        DELETE_TEMPLATE_FOLDER = "MAILCHIMP_DELETE_TEMPLATE_FOLDER"
        START_AUTOMATED_EMAIL = "MAILCHIMP_START_AUTOMATED_EMAIL"
        GET_CAMPAIGN_INFO = "MAILCHIMP_GET_CAMPAIGN_INFO"
        DELETE_INTEREST_IN_CATEGORY = "MAILCHIMP_DELETE_INTEREST_IN_CATEGORY"
        DELETE_LIST_MEMBER = "MAILCHIMP_DELETE_LIST_MEMBER"
        START_AUTOMATION_EMAILS = "MAILCHIMP_START_AUTOMATION_EMAILS"
        DELETE_INTEREST_CATEGORY = "MAILCHIMP_DELETE_INTEREST_CATEGORY"
        LIST_LANDING_PAGES = "MAILCHIMP_LIST_LANDING_PAGES"
        GET_AUTOMATION_INFO = "MAILCHIMP_GET_AUTOMATION_INFO"
        LIST_MEMBER_GOAL_EVENTS = "MAILCHIMP_LIST_MEMBER_GOAL_EVENTS"
        UPDATE_FILE = "MAILCHIMP_UPDATE_FILE"
        GET_SURVEY_QUESTION_REPORT = "MAILCHIMP_GET_SURVEY_QUESTION_REPORT"
        DELETE_CUSTOMER = "MAILCHIMP_DELETE_CUSTOMER"
        LIST_RECENT_ACTIVITY = "MAILCHIMP_LIST_RECENT_ACTIVITY"
        LIST_CART_LINE_ITEMS = "MAILCHIMP_LIST_CART_LINE_ITEMS"
        ADD_EXPORT = "MAILCHIMP_ADD_EXPORT"
        LIST_PROMO_CODES = "MAILCHIMP_LIST_PROMO_CODES"
        SEARCH_CAMPAIGNS = "MAILCHIMP_SEARCH_CAMPAIGNS"
        GET_PROMO_RULE = "MAILCHIMP_GET_PROMO_RULE"
        UPDATE_PROMO_CODE = "MAILCHIMP_UPDATE_PROMO_CODE"
        LIST_PRODUCT_IMAGES = "MAILCHIMP_LIST_PRODUCT_IMAGES"
        LIST_CLICKED_LINK_SUBSCRIBERS = "MAILCHIMP_LIST_CLICKED_LINK_SUBSCRIBERS"
        GET_PRODUCT_INFO = "MAILCHIMP_GET_PRODUCT_INFO"
        DELETE_WEBHOOK = "MAILCHIMP_DELETE_WEBHOOK"
        GET_LATEST_CHIMP_CHATTER = "MAILCHIMP_GET_LATEST_CHIMP_CHATTER"
        LIST_AUTHORIZED_APPS = "MAILCHIMP_LIST_AUTHORIZED_APPS"
        RESEND_CAMPAIGN = "MAILCHIMP_RESEND_CAMPAIGN"
        REMOVE_SUBSCRIBER_FROM_WORKFLOW = "MAILCHIMP_REMOVE_SUBSCRIBER_FROM_WORKFLOW"
        GET_PRODUCT_IMAGE_INFO = "MAILCHIMP_GET_PRODUCT_IMAGE_INFO"
        ADD_CAMPAIGN = "MAILCHIMP_ADD_CAMPAIGN"
        ADD_FOLDER = "MAILCHIMP_ADD_FOLDER"
        GET_CLICKED_LINK_SUBSCRIBER = "MAILCHIMP_GET_CLICKED_LINK_SUBSCRIBER"
        LIST_AUTOMATED_EMAIL_SUBSCRIBERS = "MAILCHIMP_LIST_AUTOMATED_EMAIL_SUBSCRIBERS"
        GET_OPENED_CAMPAIGN_SUBSCRIBER = "MAILCHIMP_GET_OPENED_CAMPAIGN_SUBSCRIBER"
        LIST_SURVEY_RESPONSES = "MAILCHIMP_LIST_SURVEY_RESPONSES"
        LIST_DOMAIN_PERFORMANCE_STATS = "MAILCHIMP_LIST_DOMAIN_PERFORMANCE_STATS"
        PUBLISH_LANDING_PAGE = "MAILCHIMP_PUBLISH_LANDING_PAGE"
        VERIFY_DOMAIN = "MAILCHIMP_VERIFY_DOMAIN"
        UPDATE_CART_LINE_ITEM = "MAILCHIMP_UPDATE_CART_LINE_ITEM"
        UPDATE_WORKFLOW_EMAIL = "MAILCHIMP_UPDATE_WORKFLOW_EMAIL"
        SEND_TEST_EMAIL = "MAILCHIMP_SEND_TEST_EMAIL"
        LIST_SUBSCRIBERS_REMOVED_FROM_WORKFLOW = "MAILCHIMP_LIST_SUBSCRIBERS_REMOVED_FROM_WORKFLOW"
        LIST_CAMPAIGN_FOLDERS = "MAILCHIMP_LIST_CAMPAIGN_FOLDERS"
        ADD_BATCH_WEBHOOK = "MAILCHIMP_ADD_BATCH_WEBHOOK"
        DELETE_LIST = "MAILCHIMP_DELETE_LIST"
        UPDATE_TEMPLATE = "MAILCHIMP_UPDATE_TEMPLATE"
        ADD_CART = "MAILCHIMP_ADD_CART"
        GET_DOMAIN_INFO = "MAILCHIMP_GET_DOMAIN_INFO"
        ADD_DOMAIN_TO_ACCOUNT = "MAILCHIMP_ADD_DOMAIN_TO_ACCOUNT"
        LIST_AUTOMATED_EMAILS = "MAILCHIMP_LIST_AUTOMATED_EMAILS"
        START_BATCH_OPERATION = "MAILCHIMP_START_BATCH_OPERATION"
        LIST_GROWTH_HISTORY_DATA = "MAILCHIMP_LIST_GROWTH_HISTORY_DATA"
        VERIFY_CONNECTED_SITE_SCRIPT = "MAILCHIMP_VERIFY_CONNECTED_SITE_SCRIPT"
        LIST_INTEREST_CATEGORIES = "MAILCHIMP_LIST_INTEREST_CATEGORIES"
        GET_CART_LINE_ITEM = "MAILCHIMP_GET_CART_LINE_ITEM"
        GET_INTEREST_IN_CATEGORY = "MAILCHIMP_GET_INTEREST_IN_CATEGORY"
        ADD_OR_REMOVE_MEMBER_TAGS = "MAILCHIMP_ADD_OR_REMOVE_MEMBER_TAGS"
        LIST_SURVEY_REPORTS = "MAILCHIMP_LIST_SURVEY_REPORTS"
        GET_MEMBER_INFO = "MAILCHIMP_GET_MEMBER_INFO"
        ADD_CUSTOMER = "MAILCHIMP_ADD_CUSTOMER"
        LIST_PROMO_RULES = "MAILCHIMP_LIST_PROMO_RULES"
        ADD_OR_UPDATE_LIST_MEMBER = "MAILCHIMP_ADD_OR_UPDATE_LIST_MEMBER"
        GET_TEMPLATE_INFO = "MAILCHIMP_GET_TEMPLATE_INFO"
        GET_BATCH_WEBHOOK_INFO = "MAILCHIMP_GET_BATCH_WEBHOOK_INFO"
        ADD_SEGMENT = "MAILCHIMP_ADD_SEGMENT"
        LIST_SIGNUP_FORMS = "MAILCHIMP_LIST_SIGNUP_FORMS"
        GET_FILE = "MAILCHIMP_GET_FILE"
        PAUSE_AUTOMATION_EMAILS = "MAILCHIMP_PAUSE_AUTOMATION_EMAILS"
        UPDATE_PROMO_RULE = "MAILCHIMP_UPDATE_PROMO_RULE"
        GET_GROWTH_HISTORY_BY_MONTH = "MAILCHIMP_GET_GROWTH_HISTORY_BY_MONTH"
        LIST_AUTOMATIONS = "MAILCHIMP_LIST_AUTOMATIONS"
        GET_CAMPAIGN_FEEDBACK_MESSAGE = "MAILCHIMP_GET_CAMPAIGN_FEEDBACK_MESSAGE"
        LIST_MEMBERS_IN_SEGMENT = "MAILCHIMP_LIST_MEMBERS_IN_SEGMENT"
        SEND_CAMPAIGN = "MAILCHIMP_SEND_CAMPAIGN"
        SCHEDULE_CAMPAIGN = "MAILCHIMP_SCHEDULE_CAMPAIGN"
        ADD_STORE = "MAILCHIMP_ADD_STORE"
        DELETE_NOTE = "MAILCHIMP_DELETE_NOTE"

    class triggers:
        CAMPAIGN_TRIGGER = {
          "config": {
            "description": "Configuration for Mailchimp webhook",
            "properties": {
              "list_id": {
                "description": "The Mailchimp list/audience ID to monitor",
                "title": "List Id",
                "type": "string"
              }
            },
            "required": ["list_id"],
            "title": "MailchimpTriggerConfig",
            "type": "object"
          },
          "description": "Triggered when a campaign is sent or experiences an event in Mailchimp",
          "instructions": "",
          "name": "Campaign Trigger",
          "payload": {
            "description": "Base class for Mailchimp payloads",
            "properties": {
              "email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email address of the subscriber",
                "title": "Email"
              },
              "event_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Type of event",
                "title": "Event Type"
              },
              "list_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "ID of the list/audience",
                "title": "List Id"
              },
              "merge_fields": {
                "anyOf": [{
                    "additionalProperties": True,
                    "type": "object"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Custom merge fields/data",
                "title": "Merge Fields"
              },
              "timestamp": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "When the event occurred",
                "title": "Timestamp"
              }
            },
            "title": "MailchimpBasePayload",
            "type": "object"
          },
          "slug": "MAILCHIMP_CAMPAIGN_TRIGGER",
          "type": "webhook"
        }
        PROFILE_UPDATE_TRIGGER = {
          "config": {
            "description": "Configuration for Mailchimp webhook",
            "properties": {
              "list_id": {
                "description": "The Mailchimp list/audience ID to monitor",
                "title": "List Id",
                "type": "string"
              }
            },
            "required": ["list_id"],
            "title": "MailchimpTriggerConfig",
            "type": "object"
          },
          "description": "Triggered when a subscriber's profile is updated in Mailchimp",
          "instructions": "",
          "name": "Profile Update Trigger",
          "payload": {
            "description": "Base class for Mailchimp payloads",
            "properties": {
              "email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email address of the subscriber",
                "title": "Email"
              },
              "event_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Type of event",
                "title": "Event Type"
              },
              "list_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "ID of the list/audience",
                "title": "List Id"
              },
              "merge_fields": {
                "anyOf": [{
                    "additionalProperties": True,
                    "type": "object"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Custom merge fields/data",
                "title": "Merge Fields"
              },
              "timestamp": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "When the event occurred",
                "title": "Timestamp"
              }
            },
            "title": "MailchimpBasePayload",
            "type": "object"
          },
          "slug": "MAILCHIMP_PROFILE_UPDATE_TRIGGER",
          "type": "webhook"
        }
        SUBSCRIBE_TRIGGER = {
          "config": {
            "description": "Configuration for Mailchimp webhook",
            "properties": {
              "list_id": {
                "description": "The Mailchimp list/audience ID to monitor",
                "title": "List Id",
                "type": "string"
              }
            },
            "required": ["list_id"],
            "title": "MailchimpTriggerConfig",
            "type": "object"
          },
          "description": "Triggered when a subscriber subscribes to Mailchimp",
          "instructions": "",
          "name": "Subscribe Trigger",
          "payload": {
            "description": "Base class for Mailchimp payloads",
            "properties": {
              "email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email address of the subscriber",
                "title": "Email"
              },
              "event_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Type of event",
                "title": "Event Type"
              },
              "list_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "ID of the list/audience",
                "title": "List Id"
              },
              "merge_fields": {
                "anyOf": [{
                    "additionalProperties": True,
                    "type": "object"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Custom merge fields/data",
                "title": "Merge Fields"
              },
              "timestamp": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "When the event occurred",
                "title": "Timestamp"
              }
            },
            "title": "MailchimpBasePayload",
            "type": "object"
          },
          "slug": "MAILCHIMP_SUBSCRIBE_TRIGGER",
          "type": "webhook"
        }
        UNSUBSCRIBE_TRIGGER = {
          "config": {
            "description": "Configuration for Mailchimp webhook",
            "properties": {
              "list_id": {
                "description": "The Mailchimp list/audience ID to monitor",
                "title": "List Id",
                "type": "string"
              }
            },
            "required": ["list_id"],
            "title": "MailchimpTriggerConfig",
            "type": "object"
          },
          "description": "Triggered when a subscriber unsubscribes from Mailchimp",
          "instructions": "",
          "name": "Unsubscribe Trigger",
          "payload": {
            "description": "Base class for Mailchimp payloads",
            "properties": {
              "email": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Email address of the subscriber",
                "title": "Email"
              },
              "event_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Type of event",
                "title": "Event Type"
              },
              "list_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "ID of the list/audience",
                "title": "List Id"
              },
              "merge_fields": {
                "anyOf": [{
                    "additionalProperties": True,
                    "type": "object"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Custom merge fields/data",
                "title": "Merge Fields"
              },
              "timestamp": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "When the event occurred",
                "title": "Timestamp"
              }
            },
            "title": "MailchimpBasePayload",
            "type": "object"
          },
          "slug": "MAILCHIMP_UNSUBSCRIBE_TRIGGER",
          "type": "webhook"
        }
