# Auto-generated by Composio CLI. Do not modify manually..

class MAILS_SO:
    """Map of Composio's MAILS_SO toolkit."""

    slug: str = "mails_so"

    class tools:
        VALIDATE_BULK_EMAILS = "MAILS_SO_VALIDATE_BULK_EMAILS"
        RETRIEVE_BATCH_RESULTS = "MAILS_SO_RETRIEVE_BATCH_RESULTS"
        VALIDATE_SINGLE_EMAIL = "MAILS_SO_VALIDATE_SINGLE_EMAIL"

    class triggers:
        pass
