# Auto-generated by Composio CLI. Do not modify manually..

class MEZMO:
    """Map of Composio's MEZMO toolkit."""

    slug: str = "mezmo"

    class tools:
        DELETE_PIPELINE_ALERT = "MEZMO_DELETE_PIPELINE_ALERT"
        INGEST_LOGS = "MEZMO_INGEST_LOGS"

    class triggers:
        pass
