# Auto-generated by Composio CLI. Do not modify manually..

class MOCEAN:
    """Map of Composio's MOCEAN toolkit."""

    slug: str = "mocean"

    class tools:
        WHATSAPP_INCOMING_WEBHOOK_V2 = "MOCEAN_WHATSAPP_INCOMING_WEBHOOK_V2"
        QUERY_MESSAGE_STATUS_V2 = "MOCEAN_QUERY_MESSAGE_STATUS_V2"
        WHATS_APP_SEND_MESSAGE_V2 = "MOCEAN_WHATS_APP_SEND_MESSAGE_V2"
        VOICE_DOWNLOAD_RECORDING_V2 = "MOCEAN_VOICE_DOWNLOAD_RECORDING_V2"
        VOICE_DIAL_V2 = "MOCEAN_VOICE_DIAL_V2"
        VOICE_HANGUP_V2 = "MOCEAN_VOICE_HANGUP_V2"

    class triggers:
        pass
