# Auto-generated by Composio CLI. Do not modify manually..

class MURAL:
    """Map of Composio's MURAL toolkit."""

    slug: str = "mural"

    class tools:
        GET_CURRENT_USER = "MURAL_GET_CURRENT_USER"
        GET_FILES_FOR_MURAL = "MURAL_GET_FILES_FOR_MURAL"
        AUTHORIZATION_REQUEST = "MURAL_AUTHORIZATION_REQUEST"
        GET_MURAL_WIDGETS = "MURAL_GET_MURAL_WIDGETS"
        CREATE_STICKY_NOTE = "MURAL_CREATE_STICKY_NOTE"

    class triggers:
        pass
