# Auto-generated by Composio CLI. Do not modify manually..

class NANGO:
    """Map of Composio's NANGO toolkit."""

    slug: str = "nango"

    class tools:
        PROVIDERS_LIST_GET = "NANGO_PROVIDERS_LIST_GET"
        CONNECTION_GET = "NANGO_CONNECTION_GET"
        ACTION_TRIGGER_POST = "NANGO_ACTION_TRIGGER_POST"
        SCRIPTS_CONFIG_GET = "NANGO_SCRIPTS_CONFIG_GET"
        PROVIDERS_GET_GET = "NANGO_PROVIDERS_GET_GET"
        CONNECTION_LIST_GET = "NANGO_CONNECTION_LIST_GET"
        SYNC_TRIGGER_POST = "NANGO_SYNC_TRIGGER_POST"

    class triggers:
        pass
