# Auto-generated by Composio CLI. Do not modify manually..

class NINOX:
    """Map of Composio's NINOX toolkit."""

    slug: str = "ninox"

    class tools:
        DELETE_RECORD = "NINOX_DELETE_RECORD"
        GET_DATABASES = "NINOX_GET_DATABASES"

    class triggers:
        pass
