# Auto-generated by Composio CLI. Do not modify manually..

class OCRSPACE:
    """Map of Composio's OCRSPACE toolkit."""

    slug: str = "ocrspace"

    class tools:
        OCR_PARSE_IMAGE_POST = "OCRSPACE_OCR_PARSE_IMAGE_POST"

    class triggers:
        pass
