# Auto-generated by Composio CLI. Do not modify manually..

class OPENGRAPH_IO:
    """Map of Composio's OPENGRAPH_IO toolkit."""

    slug: str = "opengraph_io"

    class tools:
        SCREENSHOT_SITE = "OPENGRAPH_IO_SCREENSHOT_SITE"
        EXTRACT_SITE = "OPENGRAPH_IO_EXTRACT_SITE"
        SCRAPE_SITE = "OPENGRAPH_IO_SCRAPE_SITE"
        GET_OPEN_GRAPH = "OPENGRAPH_IO_GET_OPEN_GRAPH"

    class triggers:
        pass
