# Auto-generated by Composio CLI. Do not modify manually..

class PAGE_X:
    """Map of Composio's PAGE_X toolkit."""

    slug: str = "page_x"

    class tools:
        GET_INCIDENT = "PAGE_X_GET_INCIDENT"
        DELETE_INCIDENT = "PAGE_X_DELETE_INCIDENT"
        PAGEX_CLIENT_REQUEST = "PAGE_X_PAGEX_CLIENT_REQUEST"
        PAGEX_INCIDENTS_DELETE = "PAGE_X_PAGEX_INCIDENTS_DELETE"
        LIST_INCIDENTS = "PAGE_X_LIST_INCIDENTS"

    class triggers:
        pass
