# Auto-generated by Composio CLI. Do not modify manually..

class PERPLEXITYAI:
    """Map of Composio's PERPLEXITYAI toolkit."""

    slug: str = "perplexityai"

    class tools:
        PERPLEXITY_AI_SEARCH = "PERPLEXITYAI_PERPLEXITY_AI_SEARCH"

    class triggers:
        pass
