# Auto-generated by Composio CLI. Do not modify manually..

class PLACEKEY:
    """Map of Composio's PLACEKEY toolkit."""

    slug: str = "placekey"

    class tools:
        GET_PLACEKEY_FROM_ADDRESS = "PLACEKEY_GET_PLACEKEY_FROM_ADDRESS"
        GET_PLACEKEY_FROM_COORDINATES = "PLACEKEY_GET_PLACEKEY_FROM_COORDINATES"
        GET_GEOCODE_FROM_ADDRESS = "PLACEKEY_GET_GEOCODE_FROM_ADDRESS"

    class triggers:
        pass
