# Auto-generated by Composio CLI. Do not modify manually..

class PRERENDER:
    """Map of Composio's PRERENDER toolkit."""

    slug: str = "prerender"

    class tools:
        GET_PRERENDERED_PAGE = "PRERENDER_GET_PRERENDERED_PAGE"

    class triggers:
        pass
