# Auto-generated by Composio CLI. Do not modify manually..

class PRINTAUTOPILOT:
    """Map of Composio's PRINTAUTOPILOT toolkit."""

    slug: str = "printautopilot"

    class tools:
        LIST_QUEUES = "PRINTAUTOPILOT_LIST_QUEUES"
        UPLOAD_FILE = "PRINTAUTOPILOT_UPLOAD_FILE"

    class triggers:
        pass
