# Auto-generated by Composio CLI. Do not modify manually..

class PROXIEDMAIL:
    """Map of Composio's PROXIEDMAIL toolkit."""

    slug: str = "proxiedmail"

    class tools:
        CREATE_WEBHOOK_RECEIVER = "PROXIEDMAIL_CREATE_WEBHOOK_RECEIVER"
        GET_API_TOKEN = "PROXIEDMAIL_GET_API_TOKEN"
        UPDATE_PROXY_BINDING = "PROXIEDMAIL_UPDATE_PROXY_BINDING"
        LIST_PROXY_BINDINGS = "PROXIEDMAIL_LIST_PROXY_BINDINGS"

    class triggers:
        pass
