# Auto-generated by Composio CLI. Do not modify manually..

class REMARKETY:
    """Map of Composio's REMARKETY toolkit."""

    slug: str = "remarkety"

    class tools:
        GET_PRODUCTS = "REMARKETY_GET_PRODUCTS"
        GET_CAMPAIGNS = "REMARKETY_GET_CAMPAIGNS"
        UPLOAD_CONTACTS_BATCH = "REMARKETY_UPLOAD_CONTACTS_BATCH"
        TRACK_CART = "REMARKETY_TRACK_CART"
        GET_CUSTOMERS = "REMARKETY_GET_CUSTOMERS"

    class triggers:
        pass
