# Auto-generated by Composio CLI. Do not modify manually..

class RENDERFORM:
    """Map of Composio's RENDERFORM toolkit."""

    slug: str = "renderform"

    class tools:
        LIST_TEMPLATES = "RENDERFORM_LIST_TEMPLATES"
        TAKE_SCREENSHOT = "RENDERFORM_TAKE_SCREENSHOT"
        LIST_RESULTS = "RENDERFORM_LIST_RESULTS"

    class triggers:
        pass
