# Auto-generated by Composio CLI. Do not modify manually..

class RETAILED:
    """Map of Composio's RETAILED toolkit."""

    slug: str = "retailed"

    class tools:
        SEARCH_PRODUCTS = "RETAILED_SEARCH_PRODUCTS"
        GET_USAGE = "RETAILED_GET_USAGE"
        GET_STOCKX_SEARCH = "RETAILED_GET_STOCKX_SEARCH"
        GET_GOAT_PRICES = "RETAILED_GET_GOAT_PRICES"
        GET_STOCK_X_PRODUCT = "RETAILED_GET_STOCK_X_PRODUCT"
        GET_STOCKX_TRENDS = "RETAILED_GET_STOCKX_TRENDS"

    class triggers:
        pass
