# Auto-generated by Composio CLI. Do not modify manually..

class SATISMETER:
    """Map of Composio's SATISMETER toolkit."""

    slug: str = "satismeter"

    class tools:
        UPDATE_UNSUBSCRIBED_EMAILS = "SATISMETER_UPDATE_UNSUBSCRIBED_EMAILS"
        LIST_USERS = "SATISMETER_LIST_USERS"
        EMBED_SURVEY = "SATISMETER_EMBED_SURVEY"
        GET_UNSUBSCRIBED_EMAILS = "SATISMETER_GET_UNSUBSCRIBED_EMAILS"
        LIST_SURVEYS = "SATISMETER_LIST_SURVEYS"

    class triggers:
        pass
