# Auto-generated by Composio CLI. Do not modify manually..

class SCRAPINGANT:
    """Map of Composio's SCRAPINGANT toolkit."""

    slug: str = "scrapingant"

    class tools:
        EXTRACT_CONTENT_AS_MARKDOWN = "SCRAPINGANT_EXTRACT_CONTENT_AS_MARKDOWN"
        SCRAPE_WEB_PAGE = "SCRAPINGANT_SCRAPE_WEB_PAGE"
        SCRAPE_WITH_EXTENDED_JSON_OUTPUT = "SCRAPINGANT_SCRAPE_WITH_EXTENDED_JSON_OUTPUT"
        GET_API_CREDITS_USAGE = "SCRAPINGANT_GET_API_CREDITS_USAGE"
        EXTRACT_DATA_WITH_AI = "SCRAPINGANT_EXTRACT_DATA_WITH_AI"

    class triggers:
        pass
