# Auto-generated by Composio CLI. Do not modify manually..

class SCRAPINGBEE:
    """Map of Composio's SCRAPINGBEE toolkit."""

    slug: str = "scrapingbee"

    class tools:
        DATA_EXTRACTION = "SCRAPINGBEE_DATA_EXTRACTION"
        HTML_FETCH = "SCRAPINGBEE_HTML_FETCH"
        USAGE_STATS = "SCRAPINGBEE_USAGE_STATS"
        SCRAPING_BEE_PROXY_MODE = "SCRAPINGBEE_SCRAPING_BEE_PROXY_MODE"
        STEALTH_PROXY = "SCRAPINGBEE_STEALTH_PROXY"

    class triggers:
        pass
