# Auto-generated by Composio CLI. Do not modify manually..

class SCRAPFLY:
    """Map of Composio's SCRAPFLY toolkit."""

    slug: str = "scrapfly"

    class tools:
        GET_ACCOUNT_INFO = "SCRAPFLY_GET_ACCOUNT_INFO"
        SCRAPE = "SCRAPFLY_SCRAPE"

    class triggers:
        pass
