# Auto-generated by Composio CLI. Do not modify manually..

class SCREENSHOTONE:
    """Map of Composio's SCREENSHOTONE toolkit."""

    slug: str = "screenshotone"

    class tools:
        TAKE_ANIMATED_SCREENSHOT = "SCREENSHOTONE_TAKE_ANIMATED_SCREENSHOT"

    class triggers:
        pass
