# Auto-generated by Composio CLI. Do not modify manually..

class SEGMETRICS:
    """Map of Composio's SEGMETRICS toolkit."""

    slug: str = "segmetrics"

    class tools:
        CREATE_PRODUCT = "SEGMETRICS_CREATE_PRODUCT"
        DELETE_CONTACT = "SEGMETRICS_DELETE_CONTACT"
        V1_ADD_OR_UPDATE_CONTACT = "SEGMETRICS_V1_ADD_OR_UPDATE_CONTACT"

    class triggers:
        pass
