# Auto-generated by Composio CLI. Do not modify manually..

class SENDLANE:
    """Map of Composio's SENDLANE toolkit."""

    slug: str = "sendlane"

    class tools:
        GET_CUSTOM_FIELDS = "SENDLANE_GET_CUSTOM_FIELDS"
        GET_LISTS = "SENDLANE_GET_LISTS"
        TAG_CREATE = "SENDLANE_TAG_CREATE"
        GET_CAMPAIGNS = "SENDLANE_GET_CAMPAIGNS"
        POST_LIST = "SENDLANE_POST_LIST"
        LIST_DELETE = "SENDLANE_LIST_DELETE"

    class triggers:
        pass
