# Auto-generated by Composio CLI. Do not modify manually..

class SERPLY:
    """Map of Composio's SERPLY toolkit."""

    slug: str = "serply"

    class tools:
        PERFORM_SCHOLAR_SEARCH = "SERPLY_PERFORM_SCHOLAR_SEARCH"
        PERFORM_MAPS_SEARCH = "SERPLY_PERFORM_MAPS_SEARCH"
        PERFORM_IMAGE_SEARCH = "SERPLY_PERFORM_IMAGE_SEARCH"

    class triggers:
        pass
