# Auto-generated by Composio CLI. Do not modify manually..

class SIMILARWEB_DIGITALRANK_API:
    """Map of Composio's SIMILARWEB_DIGITALRANK_API toolkit."""

    slug: str = "similarweb_digitalrank_api"

    class tools:
        GET_SUBSCRIPTION_STATUS = "SIMILARWEB_DIGITALRANK_API_GET_SUBSCRIPTION_STATUS"

    class triggers:
        pass
