# Auto-generated by Composio CLI. Do not modify manually..

class SITESPEAKAI:
    """Map of Composio's SITESPEAKAI toolkit."""

    slug: str = "sitespeakai"

    class tools:
        GET_PROMPTS = "SITESPEAKAI_GET_PROMPTS"
        GET_USER = "SITESPEAKAI_GET_USER"
        LIST_CHATBOTS = "SITESPEAKAI_LIST_CHATBOTS"

    class triggers:
        pass
