# Auto-generated by Composio CLI. Do not modify manually..

class SLACKBOT:
    """Map of Composio's SLACKBOT toolkit."""

    slug: str = "slackbot"

    class tools:
        LIST_SCHEDULED_MESSAGES = "SLACKBOT_LIST_SCHEDULED_MESSAGES"
        LIST_ALL_CHANNELS = "SLACKBOT_LIST_ALL_CHANNELS"
        RETRIEVE_CONVERSATION_MEMBERS_LIST = "SLACKBOT_RETRIEVE_CONVERSATION_MEMBERS_LIST"
        LIST_USER_REACTIONS = "SLACKBOT_LIST_USER_REACTIONS"
        FETCH_CONVERSATION_HISTORY = "SLACKBOT_FETCH_CONVERSATION_HISTORY"
        UPDATES_A_MESSAGE = "SLACKBOT_UPDATES_A_MESSAGE"
        LIST_FILES_WITH_FILTERS_IN_SLACK = "SLACKBOT_LIST_FILES_WITH_FILTERS_IN_SLACK"
        FIND_USERS = "SLACKBOT_FIND_USERS"
        REGISTERS_A_NEW_CALL_WITH_PARTICIPANTS = "SLACKBOT_REGISTERS_A_NEW_CALL_WITH_PARTICIPANTS"
        LIST_CANVASES = "SLACKBOT_LIST_CANVASES"
        UPLOAD_OR_CREATE_A_FILE_IN_SLACK = "SLACKBOT_UPLOAD_OR_CREATE_A_FILE_IN_SLACK"
        LIST_TEAM_CUSTOM_EMOJIS = "SLACKBOT_LIST_TEAM_CUSTOM_EMOJIS"
        REMOVE_A_REMOTE_FILE = "SLACKBOT_REMOVE_A_REMOTE_FILE"
        FETCH_WORKSPACE_SETTINGS_INFORMATION = "SLACKBOT_FETCH_WORKSPACE_SETTINGS_INFORMATION"
        MANUALLY_SET_USER_PRESENCE = "SLACKBOT_MANUALLY_SET_USER_PRESENCE"
        REMOVE_A_USER_FROM_A_CONVERSATION = "SLACKBOT_REMOVE_A_USER_FROM_A_CONVERSATION"
        OPEN_DM = "SLACKBOT_OPEN_DM"
        RETRIEVE_MESSAGE_PERMALINK_URL = "SLACKBOT_RETRIEVE_MESSAGE_PERMALINK_URL"
        JOIN_AN_EXISTING_CONVERSATION = "SLACKBOT_JOIN_AN_EXISTING_CONVERSATION"
        ENABLE_PUBLIC_SHARING_OF_A_FILE = "SLACKBOT_ENABLE_PUBLIC_SHARING_OF_A_FILE"
        CUSTOMIZE_URL_UNFURL = "SLACKBOT_CUSTOMIZE_URL_UNFURL"
        RETRIEVE_USER_PROFILE_INFORMATION = "SLACKBOT_RETRIEVE_USER_PROFILE_INFORMATION"
        LIST_CONVERSATIONS = "SLACKBOT_LIST_CONVERSATIONS"
        RENAME_AN_EMOJI = "SLACKBOT_RENAME_AN_EMOJI"
        FETCH_BOT_USER_INFORMATION = "SLACKBOT_FETCH_BOT_USER_INFORMATION"
        EDIT_CANVAS = "SLACKBOT_EDIT_CANVAS"
        DELETE_A_SCHEDULED_MESSAGE_IN_A_CHAT = "SLACKBOT_DELETE_A_SCHEDULED_MESSAGE_IN_A_CHAT"
        GET_CANVAS = "SLACKBOT_GET_CANVAS"
        SET_STATUS = "SLACKBOT_SET_STATUS"
        UNPIN_ITEM_FROM_CHANNEL = "SLACKBOT_UNPIN_ITEM_FROM_CHANNEL"
        CLOSE_DM_OR_MULTI_PERSON_DM = "SLACKBOT_CLOSE_DM_OR_MULTI_PERSON_DM"
        GET_REMINDER_INFORMATION = "SLACKBOT_GET_REMINDER_INFORMATION"
        FETCH_MESSAGE_THREAD_FROM_A_CONVERSATION = "SLACKBOT_FETCH_MESSAGE_THREAD_FROM_A_CONVERSATION"
        UPDATE_CALL_INFORMATION = "SLACKBOT_UPDATE_CALL_INFORMATION"
        SET_USER_PROFILE_INFORMATION = "SLACKBOT_SET_USER_PROFILE_INFORMATION"
        LIST_REMOTE_FILES = "SLACKBOT_LIST_REMOTE_FILES"
        ADD_REACTION_TO_AN_ITEM = "SLACKBOT_ADD_REACTION_TO_AN_ITEM"
        REVERSE_A_CONVERSATION_S_ARCHIVAL_STATUS = "SLACKBOT_REVERSE_A_CONVERSATION_S_ARCHIVAL_STATUS"
        LIST_ALL_USERS = "SLACKBOT_LIST_ALL_USERS"
        RETRIEVE_CURRENT_USER_DND_STATUS = "SLACKBOT_RETRIEVE_CURRENT_USER_DND_STATUS"
        REMOVE_A_STAR_FROM_AN_ITEM = "SLACKBOT_REMOVE_A_STAR_FROM_AN_ITEM"
        ENABLE_A_SPECIFIED_USER_GROUP = "SLACKBOT_ENABLE_A_SPECIFIED_USER_GROUP"
        CREATE_CHANNEL_BASED_CONVERSATION = "SLACKBOT_CREATE_CHANNEL_BASED_CONVERSATION"
        LIST_STARRED_ITEMS = "SLACKBOT_LIST_STARRED_ITEMS"
        REMOVE_REACTION_FROM_ITEM = "SLACKBOT_REMOVE_REACTION_FROM_ITEM"
        END_A_CALL_WITH_DURATION_AND_ID = "SLACKBOT_END_A_CALL_WITH_DURATION_AND_ID"
        DELETE_A_COMMENT_ON_A_FILE = "SLACKBOT_DELETE_A_COMMENT_ON_A_FILE"
        ADD_A_REMOTE_FILE_FROM_A_SERVICE = "SLACKBOT_ADD_A_REMOTE_FILE_FROM_A_SERVICE"
        LOOKUP_CANVAS_SECTIONS = "SLACKBOT_LOOKUP_CANVAS_SECTIONS"
        RENAME_A_CHANNEL = "SLACKBOT_RENAME_A_CHANNEL"
        SCHEDULE_MESSAGE = "SLACKBOT_SCHEDULE_MESSAGE"
        LEAVE_A_CONVERSATION = "SLACKBOT_LEAVE_A_CONVERSATION"
        RETRIEVE_CONVERSATION_INFORMATION = "SLACKBOT_RETRIEVE_CONVERSATION_INFORMATION"
        SEND_MESSAGE = "SLACKBOT_SEND_MESSAGE"
        FETCH_ITEM_REACTIONS = "SLACKBOT_FETCH_ITEM_REACTIONS"
        UPDATE_AN_EXISTING_USER_GROUP = "SLACKBOT_UPDATE_AN_EXISTING_USER_GROUP"
        GET_REMOTE_FILE = "SLACKBOT_GET_REMOTE_FILE"
        UPDATE_USER_GROUP_MEMBERS = "SLACKBOT_UPDATE_USER_GROUP_MEMBERS"
        START_REAL_TIME_MESSAGING_SESSION = "SLACKBOT_START_REAL_TIME_MESSAGING_SESSION"
        REVOKE_PUBLIC_SHARING_ACCESS_FOR_A_FILE = "SLACKBOT_REVOKE_PUBLIC_SHARING_ACCESS_FOR_A_FILE"
        RETRIEVE_DETAILED_INFORMATION_ABOUT_A_FILE = "SLACKBOT_RETRIEVE_DETAILED_INFORMATION_ABOUT_A_FILE"
        LISTS_PINNED_ITEMS_IN_A_CHANNEL = "SLACKBOT_LISTS_PINNED_ITEMS_IN_A_CHANNEL"
        CREATE_CHANNEL = "SLACKBOT_CREATE_CHANNEL"
        DELETE_A_REMINDER = "SLACKBOT_DELETE_A_REMINDER"
        RENAME_A_CONVERSATION = "SLACKBOT_RENAME_A_CONVERSATION"
        END_SNOOZE = "SLACKBOT_END_SNOOZE"
        DELETES_A_MESSAGE_FROM_A_CHAT = "SLACKBOT_DELETES_A_MESSAGE_FROM_A_CHAT"
        DELETE_A_FILE_BY_ID = "SLACKBOT_DELETE_A_FILE_BY_ID"
        CREATE_A_USER_GROUP = "SLACKBOT_CREATE_A_USER_GROUP"
        SET_PROFILE_PHOTO = "SLACKBOT_SET_PROFILE_PHOTO"
        RETRIEVE_CALL_INFORMATION = "SLACKBOT_RETRIEVE_CALL_INFORMATION"
        SEND_EPHEMERAL_MESSAGE = "SLACKBOT_SEND_EPHEMERAL_MESSAGE"
        SET_A_CONVERSATION_S_PURPOSE = "SLACKBOT_SET_A_CONVERSATION_S_PURPOSE"
        FETCH_DND_STATUS_FOR_MULTIPLE_TEAM_MEMBERS = "SLACKBOT_FETCH_DND_STATUS_FOR_MULTIPLE_TEAM_MEMBERS"
        DELETE_CANVAS = "SLACKBOT_DELETE_CANVAS"
        GET_USER_PRESENCE_INFO = "SLACKBOT_GET_USER_PRESENCE_INFO"
        PINS_AN_ITEM_TO_A_CHANNEL = "SLACKBOT_PINS_AN_ITEM_TO_A_CHANNEL"
        INVITE_USER_TO_WORKSPACE = "SLACKBOT_INVITE_USER_TO_WORKSPACE"
        ARCHIVE_A_CONVERSATION = "SLACKBOT_ARCHIVE_A_CONVERSATION"
        MARK_REMINDER_AS_COMPLETE = "SLACKBOT_MARK_REMINDER_AS_COMPLETE"
        ADD_AN_EMOJI_ALIAS_IN_SLACK = "SLACKBOT_ADD_AN_EMOJI_ALIAS_IN_SLACK"
        GET_CHANNEL_CONVERSATION_PREFERENCES = "SLACKBOT_GET_CHANNEL_CONVERSATION_PREFERENCES"
        SET_THE_TOPIC_OF_A_CONVERSATION = "SLACKBOT_SET_THE_TOPIC_OF_A_CONVERSATION"
        RETRIEVE_TEAM_PROFILE_DETAILS = "SLACKBOT_RETRIEVE_TEAM_PROFILE_DETAILS"
        DELETE_USER_PROFILE_PHOTO = "SLACKBOT_DELETE_USER_PROFILE_PHOTO"
        LIST_USER_GROUPS_FOR_TEAM_WITH_OPTIONS = "SLACKBOT_LIST_USER_GROUPS_FOR_TEAM_WITH_OPTIONS"
        SHARE_REMOTE_FILE_IN_CHANNELS = "SLACKBOT_SHARE_REMOTE_FILE_IN_CHANNELS"
        FETCH_TEAM_INFO = "SLACKBOT_FETCH_TEAM_INFO"
        LIST_WORKSPACE_USERS = "SLACKBOT_LIST_WORKSPACE_USERS"
        UNARCHIVE_A_PUBLIC_OR_PRIVATE_CHANNEL = "SLACKBOT_UNARCHIVE_A_PUBLIC_OR_PRIVATE_CHANNEL"
        FIND_CHANNELS = "SLACKBOT_FIND_CHANNELS"
        RETRIEVE_A_USER_S_IDENTITY_DETAILS = "SLACKBOT_RETRIEVE_A_USER_S_IDENTITY_DETAILS"
        END_USER_DO_NOT_DISTURB_SESSION = "SLACKBOT_END_USER_DO_NOT_DISTURB_SESSION"
        DISABLE_AN_EXISTING_USER_GROUP = "SLACKBOT_DISABLE_AN_EXISTING_USER_GROUP"
        DELETE_A_PUBLIC_OR_PRIVATE_CHANNEL = "SLACKBOT_DELETE_A_PUBLIC_OR_PRIVATE_CHANNEL"
        SEARCH_MESSAGES = "SLACKBOT_SEARCH_MESSAGES"
        INVITE_USERS_TO_A_CHANNEL = "SLACKBOT_INVITE_USERS_TO_A_CHANNEL"
        RETRIEVE_DETAILED_USER_INFORMATION = "SLACKBOT_RETRIEVE_DETAILED_USER_INFORMATION"
        GET_APP_PERMISSION_SCOPES = "SLACKBOT_GET_APP_PERMISSION_SCOPES"
        SET_READ_CURSOR_IN_A_CONVERSATION = "SLACKBOT_SET_READ_CURSOR_IN_A_CONVERSATION"
        CREATE_CANVAS = "SLACKBOT_CREATE_CANVAS"
        ARCHIVE_A_PUBLIC_OR_PRIVATE_CHANNEL = "SLACKBOT_ARCHIVE_A_PUBLIC_OR_PRIVATE_CHANNEL"
        CREATE_A_REMINDER = "SLACKBOT_CREATE_A_REMINDER"
        LIST_ALL_USERS_IN_A_USER_GROUP = "SLACKBOT_LIST_ALL_USERS_IN_A_USER_GROUP"
        CLEAR_STATUS = "SLACKBOT_CLEAR_STATUS"
        LIST_REMINDERS = "SLACKBOT_LIST_REMINDERS"
        SEARCH_ALL = "SLACKBOT_SEARCH_ALL"
        INVITE_USER_TO_CHANNEL = "SLACKBOT_INVITE_USER_TO_CHANNEL"
        UPDATES_AN_EXISTING_REMOTE_FILE = "SLACKBOT_UPDATES_AN_EXISTING_REMOTE_FILE"
        ADD_A_CUSTOM_EMOJI_TO_A_TEAM = "SLACKBOT_ADD_A_CUSTOM_EMOJI_TO_A_TEAM"
        SET_DND_DURATION = "SLACKBOT_SET_DND_DURATION"
        FIND_USER_BY_EMAIL_ADDRESS = "SLACKBOT_FIND_USER_BY_EMAIL_ADDRESS"
        ADD_A_STAR_TO_AN_ITEM = "SLACKBOT_ADD_A_STAR_TO_AN_ITEM"
        ADD_CALL_PARTICIPANTS = "SLACKBOT_ADD_CALL_PARTICIPANTS"
        SHARE_A_ME_MESSAGE_IN_A_CHANNEL = "SLACKBOT_SHARE_A_ME_MESSAGE_IN_A_CHANNEL"
        REGISTER_CALL_PARTICIPANTS_REMOVAL = "SLACKBOT_REGISTER_CALL_PARTICIPANTS_REMOVAL"

    class triggers:
        CHANNEL_CREATED = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when a new channel is created in Slack.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `channel_created` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n",
          "name": "New Channel Created Trigger",
          "payload": {
            "properties": {
              "created": {
                "description": "The timestamp of when the channel was created, formatted as a Unix timestamp",
                "title": "Created",
                "type": "integer"
              },
              "creator": {
                "description": "The ID of the user who created the channel",
                "title": "Creator",
                "type": "string"
              },
              "id": {
                "description": "The ID of the channel",
                "title": "Id",
                "type": "string"
              },
              "name": {
                "description": "The name of the channel",
                "title": "Name",
                "type": "string"
              }
            },
            "required": ["id", "name", "creator", "created"],
            "title": "ChannelCreatedPayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_CHANNEL_CREATED",
          "type": "webhook"
        }
        REACTION_ADDED = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when a reaction is added to a message in Slack.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `reaction_added` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n",
          "name": "Reaction Added Trigger",
          "payload": {
            "properties": {
              "bot_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the bot that posted the message",
                "title": "Bot Id"
              },
              "channel_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The type of the channel where the message was posted",
                "title": "Channel Type"
              },
              "event_ts": {
                "description": "The timestamp of the reaction event. Formatted as a Unix timestamp",
                "title": "Event Ts",
                "type": "string"
              },
              "message_channel": {
                "description": "The ID of the channel where the message that was reacted to is located",
                "title": "Message Channel",
                "type": "string"
              },
              "message_ts": {
                "description": "The timestamp of the message that was reacted to. Formatted as a Unix timestamp",
                "title": "Message Ts",
                "type": "string"
              },
              "message_user": {
                "description": "The ID of the user who owns the message that was reacted to",
                "title": "Message User",
                "type": "string"
              },
              "reaction": {
                "description": "The type of reaction that was added",
                "title": "Reaction",
                "type": "string"
              },
              "team_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the team where the message was posted",
                "title": "Team Id"
              },
              "user": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the user who added the reaction",
                "title": "User"
              }
            },
            "required": ["user", "reaction", "message_user", "message_channel", "message_ts", "event_ts", "team_id", "bot_id", "channel_type"],
            "title": "ReactionAddedPayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_REACTION_ADDED",
          "type": "webhook"
        }
        REACTION_REMOVED = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when a reaction is removed from a message.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `reaction_removed` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n",
          "name": "Reaction Removed Trigger",
          "payload": {
            "properties": {
              "bot_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the bot that posted the message",
                "title": "Bot Id"
              },
              "channel_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The type of the channel where the message was posted",
                "title": "Channel Type"
              },
              "event_ts": {
                "description": "The timestamp of the reaction event. Formatted as a Unix timestamp",
                "title": "Event Ts",
                "type": "string"
              },
              "message_channel": {
                "description": "The ID of the channel where the message that was reacted to is located",
                "title": "Message Channel",
                "type": "string"
              },
              "message_ts": {
                "description": "The timestamp of the message that was reacted to. Formatted as a Unix timestamp",
                "title": "Message Ts",
                "type": "string"
              },
              "message_user": {
                "description": "The ID of the user who owns the message that was reacted to",
                "title": "Message User",
                "type": "string"
              },
              "reaction": {
                "description": "The type of reaction that was added",
                "title": "Reaction",
                "type": "string"
              },
              "team_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the team where the message was posted",
                "title": "Team Id"
              },
              "user": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the user who added the reaction",
                "title": "User"
              }
            },
            "required": ["user", "reaction", "message_user", "message_channel", "message_ts", "event_ts", "team_id", "bot_id", "channel_type"],
            "title": "ReactionRemovedPayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_REACTION_REMOVED",
          "type": "webhook"
        }
        RECEIVE_BOT_MESSAGE = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when a new bot message is posted to a Slack channel.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `message.channels` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n",
          "name": "New Bot Message Received Trigger",
          "payload": {
            "properties": {
              "attachments": {
                "anyOf": [{
                    "items": {
                      "additionalProperties": True,
                      "type": "object"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Attachments included with the bot message, if any. Slack apps (like Datadog) often send their content via attachments rather than the top-level text field.",
                "title": "Attachments"
              },
              "bot_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the bot that posted the message",
                "title": "Bot Id"
              },
              "channel": {
                "description": "The ID of the channel where the bot message was posted",
                "title": "Channel",
                "type": "string"
              },
              "channel_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The type of the channel where the bot message was posted",
                "title": "Channel Type"
              },
              "subtype": {
                "description": "The subtype of the message (should be 'bot_message')",
                "title": "Subtype",
                "type": "string"
              },
              "team_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the team where the bot message was posted",
                "title": "Team Id"
              },
              "text": {
                "description": "The text content of the bot message",
                "title": "Text",
                "type": "string"
              },
              "ts": {
                "description": "The timestamp of the bot message",
                "title": "Ts",
                "type": "string"
              },
              "username": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The username of the bot that posted the message",
                "title": "Username"
              }
            },
            "required": ["channel", "text", "ts", "subtype"],
            "title": "BotMessagePayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_RECEIVE_BOT_MESSAGE",
          "type": "webhook"
        }
        RECEIVE_DIRECT_MESSAGE = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when a new direct message (DM) is sent to a user in Slack.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `message.im` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n\n\nTo use this trigger, ensure your Slack integration has the `im:history` OAuth scope.",
          "name": "New Direct Message Received Trigger",
          "payload": {
            "properties": {
              "attachments": {
                "anyOf": [{
                    "items": {
                      "additionalProperties": True,
                      "type": "object"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Attachments included with the direct message, if any. Some Slack apps (like Datadog) send content via attachments rather than the top-level text field.",
                "title": "Attachments"
              },
              "bot_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the bot that sent the direct message",
                "title": "Bot Id"
              },
              "channel": {
                "description": "The ID of the direct message channel",
                "title": "Channel",
                "type": "string"
              },
              "channel_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The type of the channel (should be 'im' for direct messages)",
                "title": "Channel Type"
              },
              "team_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the team where the direct message was sent",
                "title": "Team Id"
              },
              "text": {
                "description": "The text content of the direct message",
                "title": "Text",
                "type": "string"
              },
              "ts": {
                "description": "The timestamp of the direct message",
                "title": "Ts",
                "type": "string"
              },
              "user": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the user who sent the direct message",
                "title": "User"
              }
            },
            "required": ["channel", "user", "text", "ts", "team_id", "bot_id", "channel_type"],
            "title": "DirectMessagePayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_RECEIVE_DIRECT_MESSAGE",
          "type": "webhook"
        }
        RECEIVE_GROUP_MESSAGE = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when a new message is posted to a private channel in Slack.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `message.groups` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n\n\nTo use this trigger, ensure your Slack app has the `groups:history` OAuth scope. You can add this scope when creating or configuring your Slack app in the App Settings > OAuth & Permissions section.",
          "name": "New Private Channel Message Received Trigger",
          "payload": {
            "properties": {
              "attachments": {
                "anyOf": [{
                    "items": {
                      "additionalProperties": True,
                      "type": "object"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Attachments included with the message, if any. Some Slack apps (like Datadog) send content via attachments rather than the top-level text field.",
                "title": "Attachments"
              },
              "bot_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the bot that sent the message",
                "title": "Bot Id"
              },
              "channel": {
                "description": "The ID of the private channel",
                "title": "Channel",
                "type": "string"
              },
              "channel_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The type of the channel (should be 'group' for private channels)",
                "title": "Channel Type"
              },
              "team_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the team where the message was sent",
                "title": "Team Id"
              },
              "text": {
                "description": "The text content of the message",
                "title": "Text",
                "type": "string"
              },
              "ts": {
                "description": "The timestamp of the message",
                "title": "Ts",
                "type": "string"
              },
              "user": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the user who sent the message in the private channel",
                "title": "User"
              }
            },
            "required": ["channel", "user", "text", "ts", "team_id", "bot_id", "channel_type"],
            "title": "GroupMessagePayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_RECEIVE_GROUP_MESSAGE",
          "type": "webhook"
        }
        RECEIVE_MESSAGE = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when a new message is posted to a Slack channel.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `message.channels` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n",
          "name": "New Message Received Trigger",
          "payload": {
            "properties": {
              "attachments": {
                "anyOf": [{
                    "items": {
                      "additionalProperties": True,
                      "type": "object"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Attachments included with the message, if any. Some Slack apps (like Datadog) send content via attachments rather than the top-level text field.",
                "title": "Attachments"
              },
              "bot_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the bot that posted the message",
                "title": "Bot Id"
              },
              "channel": {
                "description": "The ID of the channel where the message was posted",
                "title": "Channel",
                "type": "string"
              },
              "channel_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The type of the channel where the message was posted",
                "title": "Channel Type"
              },
              "team_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the team where the message was posted",
                "title": "Team Id"
              },
              "text": {
                "description": "The text content of the message",
                "title": "Text",
                "type": "string"
              },
              "ts": {
                "description": "The timestamp of the message",
                "title": "Ts",
                "type": "string"
              },
              "user": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the user who posted the message",
                "title": "User"
              }
            },
            "required": ["channel", "text", "ts"],
            "title": "MessagePayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_RECEIVE_MESSAGE",
          "type": "webhook"
        }
        RECEIVE_MPIM_MESSAGE = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when a new message is posted to a multi-person direct message in Slack.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `message.mpim` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n\n\nTo use this trigger, ensure your Slack app has the `mpim:history` OAuth scope.",
          "name": "New Multi-Person Direct Message Received Trigger",
          "payload": {
            "properties": {
              "bot_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the bot that sent the message",
                "title": "Bot Id"
              },
              "channel": {
                "description": "The ID of the multi-person direct message channel",
                "title": "Channel",
                "type": "string"
              },
              "channel_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The type of the channel (should be 'mpim' for multi-person direct messages)",
                "title": "Channel Type"
              },
              "team_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the team where the message was sent",
                "title": "Team Id"
              },
              "text": {
                "description": "The text content of the message",
                "title": "Text",
                "type": "string"
              },
              "ts": {
                "description": "The timestamp of the message",
                "title": "Ts",
                "type": "string"
              },
              "user": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "description": "The ID of the user who sent the message in the multi-person direct message",
                "title": "User"
              }
            },
            "required": ["channel", "user", "text", "ts", "team_id", "bot_id", "channel_type"],
            "title": "MpimMessagePayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_RECEIVE_MPIM_MESSAGE",
          "type": "webhook"
        }
        RECEIVE_THREAD_REPLY = {
          "config": {
            "properties": {},
            "title": "SlackWebhookConfig",
            "type": "object"
          },
          "description": "Triggered when reply is added to a message in a thread.\n    Excludes the parent message_replied event by design (ts != thread_ts check).",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - If you are using your own Slack app:\n        1. Go to the 'Event Subscriptions' section of your app's settings.\n        2. Enable events.\n        3. Input the 'Request URL' field with `https://backend.composio.dev/api/v3/trigger_instances/slackbot/pr_g5BuyndZjyH8/handle`\n        4. Add `message.channels` to the 'Subscribe to bot events' section and\n          `Subscribe to events on behalf of users` section and save.\n    - If you are using the Composio Slack app, you are all set here!\n    - If you are using Slackbot integration, you would need to add the Slack\n      app to the channels you want to monitor. In case using Composio Slack app,\n      you need to do /add and then choose Composio App.\n",
          "name": "Thread Reply Received Trigger",
          "payload": {
            "properties": {
              "bot_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the bot that posted the message",
                "title": "Bot Id"
              },
              "channel": {
                "description": "The ID of the channel where the message was posted",
                "title": "Channel",
                "type": "string"
              },
              "channel_type": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The type of the channel where the message was posted",
                "title": "Channel Type"
              },
              "parent_user_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the user who posted the parent message",
                "title": "Parent User Id"
              },
              "reply_count": {
                "anyOf": [{
                    "type": "integer"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The number of replies in the thread",
                "title": "Reply Count"
              },
              "team_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the team where the message was posted",
                "title": "Team Id"
              },
              "text": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The text content of the message (may be None for block-only replies)",
                "title": "Text"
              },
              "thread_ts": {
                "description": "The timestamp of the parent message in the thread",
                "title": "Thread Ts",
                "type": "string"
              },
              "ts": {
                "description": "The timestamp of the message",
                "title": "Ts",
                "type": "string"
              },
              "user": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ID of the user who posted the message",
                "title": "User"
              }
            },
            "required": ["channel", "ts", "thread_ts"],
            "title": "ThreadReplyPayloadSchema",
            "type": "object"
          },
          "slug": "SLACKBOT_RECEIVE_THREAD_REPLY",
          "type": "webhook"
        }
