# Auto-generated by Composio CLI. Do not modify manually..

class STANNP:
    """Map of Composio's STANNP toolkit."""

    slug: str = "stannp"

    class tools:
        GET_CONTACT = "STANNP_GET_CONTACT"
        ADD_RECIPIENT_TO_GROUP = "STANNP_ADD_RECIPIENT_TO_GROUP"
        LIST_TEMPLATES = "STANNP_LIST_TEMPLATES"
        IMPORT_RECIPIENTS = "STANNP_IMPORT_RECIPIENTS"
        CREATE_GROUP = "STANNP_CREATE_GROUP"
        LIST_CONTACTS = "STANNP_LIST_CONTACTS"

    class triggers:
        pass
