# Auto-generated by Composio CLI. Do not modify manually..

class STOREGANISE:
    """Map of Composio's STOREGANISE toolkit."""

    slug: str = "storeganise"

    class tools:
        GET_ADMIN_USERS_BY_IDS = "STOREGANISE_GET_ADMIN_USERS_BY_IDS"
        GET_ADMIN_SITES_BY_ID = "STOREGANISE_GET_ADMIN_SITES_BY_ID"
        GET_ADMIN_USERS_BY_ID = "STOREGANISE_GET_ADMIN_USERS_BY_ID"

    class triggers:
        pass
