# Auto-generated by Composio CLI. Do not modify manually..

class STREAMTIME:
    """Map of Composio's STREAMTIME toolkit."""

    slug: str = "streamtime"

    class tools:
        USERS_LIST_SAVED_SEGMENTS = "STREAMTIME_USERS_LIST_SAVED_SEGMENTS"
        ROLES_GET_ROLE = "STREAMTIME_ROLES_GET_ROLE"
        ORGANISATION_GET_ORGANISATION = "STREAMTIME_ORGANISATION_GET_ORGANISATION"
        LIST_ROLES = "STREAMTIME_LIST_ROLES"

    class triggers:
        pass
