# Auto-generated by Composio CLI. Do not modify manually..

class TEAMCAMP:
    """Map of Composio's TEAMCAMP toolkit."""

    slug: str = "teamcamp"

    class tools:
        DELETE_PROJECT = "TEAMCAMP_DELETE_PROJECT"
        GET_PROJECT_LIST = "TEAMCAMP_GET_PROJECT_LIST"
        GET_TASK_LIST = "TEAMCAMP_GET_TASK_LIST"
        CREATE_TASK = "TEAMCAMP_CREATE_TASK"

    class triggers:
        pass
