# Auto-generated by Composio CLI. Do not modify manually..

class TEXT_TO_PDF:
    """Map of Composio's TEXT_TO_PDF toolkit."""

    slug: str = "text_to_pdf"

    class tools:
        CONVERT_TEXT_TO_PDF = "TEXT_TO_PDF_CONVERT_TEXT_TO_PDF"

    class triggers:
        pass
