# Auto-generated by Composio CLI. Do not modify manually..

class TIMECAMP:
    """Map of Composio's TIMECAMP toolkit."""

    slug: str = "timecamp"

    class tools:
        GET_PROJECTS_LIST = "TIMECAMP_GET_PROJECTS_LIST"

    class triggers:
        pass
