# Auto-generated by Composio CLI. Do not modify manually..

class TINYURL:
    """Map of Composio's TINYURL toolkit."""

    slug: str = "tinyurl"

    class tools:
        CREATE_SHORT_URL = "TINYURL_CREATE_SHORT_URL"

    class triggers:
        pass
