# Auto-generated by Composio CLI. Do not modify manually..

class TISANE:
    """Map of Composio's TISANE toolkit."""

    slug: str = "tisane"

    class tools:
        TRANSFORM_TEXT = "TISANE_TRANSFORM_TEXT"
        DETECT_LANGUAGE = "TISANE_DETECT_LANGUAGE"
        GET_SUPPORTED_LANGUAGES = "TISANE_GET_SUPPORTED_LANGUAGES"
        ANALYZE_TEXT = "TISANE_ANALYZE_TEXT"
        CALCULATE_SIMILARITY = "TISANE_CALCULATE_SIMILARITY"
        EXTRACT_TEXT = "TISANE_EXTRACT_TEXT"

    class triggers:
        pass
