# Auto-generated by Composio CLI. Do not modify manually..

class TOKEN_METRICS:
    """Map of Composio's TOKEN_METRICS toolkit."""

    slug: str = "token_metrics"

    class tools:
        GET_TRADING_SIGNALS = "TOKEN_METRICS_GET_TRADING_SIGNALS"
        GET_PRICE = "TOKEN_METRICS_GET_PRICE"
        GET_TOKENS = "TOKEN_METRICS_GET_TOKENS"
        GET_TOP_MARKET_CAP_TOKENS = "TOKEN_METRICS_GET_TOP_MARKET_CAP_TOKENS"
        GET_TECHNICAL_INDICATORS = "TOKEN_METRICS_GET_TECHNICAL_INDICATORS"

    class triggers:
        pass
