# Auto-generated by Composio CLI. Do not modify manually..

class TYPEFULLY:
    """Map of Composio's TYPEFULLY toolkit."""

    slug: str = "typefully"

    class tools:
        MARK_NOTIFICATIONS_READ = "TYPEFULLY_MARK_NOTIFICATIONS_READ"
        GET_RECENTLY_PUBLISHED = "TYPEFULLY_GET_RECENTLY_PUBLISHED"
        GET_NOTIFICATIONS = "TYPEFULLY_GET_NOTIFICATIONS"
        CREATE_DRAFT = "TYPEFULLY_CREATE_DRAFT"
        GET_RECENTLY_SCHEDULED = "TYPEFULLY_GET_RECENTLY_SCHEDULED"

    class triggers:
        pass
