# Auto-generated by Composio CLI. Do not modify manually..

class V0:
    """Map of Composio's V0 toolkit."""

    slug: str = "v0"

    class tools:
        FIND_CHATS = "V0_FIND_CHATS"
        CHAT_COMPLETIONS = "V0_CHAT_COMPLETIONS"
        FIND_PROJECTS = "V0_FIND_PROJECTS"

    class triggers:
        pass
