# Auto-generated by Composio CLI. Do not modify manually..

class VERIPHONE:
    """Map of Composio's VERIPHONE toolkit."""

    slug: str = "veriphone"

    class tools:
        GET_EXAMPLE_PHONE_NUMBER = "VERIPHONE_GET_EXAMPLE_PHONE_NUMBER"
        VERIFY_PHONE_NUMBER = "VERIPHONE_VERIFY_PHONE_NUMBER"

    class triggers:
        pass
