# Auto-generated by Composio CLI. Do not modify manually..

class WEBVIZIO:
    """Map of Composio's WEBVIZIO toolkit."""

    slug: str = "webvizio"

    class tools:
        LIST_WEBHOOKS = "WEBVIZIO_LIST_WEBHOOKS"

    class triggers:
        pass
