# Auto-generated by Composio CLI. Do not modify manually..

class Y_GY:
    """Map of Composio's Y_GY toolkit."""

    slug: str = "y_gy"

    class tools:
        GET_ALL_TAGS = "Y_GY_GET_ALL_TAGS"
        GET_SHORT_LINK = "Y_GY_GET_SHORT_LINK"
        DELETE_SHORT_LINK = "Y_GY_DELETE_SHORT_LINK"
        REGISTER_USER = "Y_GY_REGISTER_USER"
        GET_ALL_LINKS = "Y_GY_GET_ALL_LINKS"
        CREATE_SHORT_LINK = "Y_GY_CREATE_SHORT_LINK"
        DELETE_TAG = "Y_GY_DELETE_TAG"
        CREATE_TAG = "Y_GY_CREATE_TAG"

    class triggers:
        pass
