# Auto-generated by Composio CLI. Do not modify manually..

class ADDRESSZEN:
    """Map of Composio's ADDRESSZEN toolkit."""

    slug: str = "addresszen"

    class tools:
        KEY_AVAILABILITY = "ADDRESSZEN_KEY_AVAILABILITY"
        RESOLVE_ADDRESS_USA = "ADDRESSZEN_RESOLVE_ADDRESS_USA"

    class triggers:
        pass
