# Auto-generated by Composio CLI. Do not modify manually..

class ADRAPID:
    """Map of Composio's ADRAPID toolkit."""

    slug: str = "adrapid"

    class tools:
        GET_SYSTEM_ME = "ADRAPID_GET_SYSTEM_ME"
        GET_API_INFO = "ADRAPID_GET_API_INFO"
        LIST_BANNERS = "ADRAPID_LIST_BANNERS"

    class triggers:
        pass
