# Auto-generated by Composio CLI. Do not modify manually..

class AGENT_MAIL:
    """Map of Composio's AGENT_MAIL toolkit."""

    slug: str = "agent_mail"

    class tools:
        GET_MESSAGE = "AGENT_MAIL_GET_MESSAGE"
        SEND_EMAIL = "AGENT_MAIL_SEND_EMAIL"
        LIST_MESSAGES = "AGENT_MAIL_LIST_MESSAGES"

    class triggers:
        NEW_EMAIL_TRIGGER = {
          "config": {
            "properties": {
              "inbox_id": {
                "description": "The inbox ID or email address to monitor for new emails",
                "examples": ["agent@agentmail.to", "inbox_123"],
                "title": "Inbox Id",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "labels": {
                "default": None,
                "description": "Filter messages by specific labels (e.g., 'unread', 'inbox')",
                "examples": [["unread"], ["inbox", "important"]],
                "items": {
                  "properties": {},
                  "type": "string"
                },
                "nullable": True,
                "title": "Labels",
                "type": "array"
              }
            },
            "required": ["inbox_id"],
            "title": "NewEmailConfig",
            "type": "object"
          },
          "description": "Trigger for new emails in an AgentMail inbox",
          "instructions": "",
          "name": "New Email Received",
          "payload": {
            "$defs": {
              "MessageAttachment": {
                "properties": {
                  "attachment_id": {
                    "description": "ID of the attachment",
                    "title": "Attachment Id",
                    "type": "string"
                  },
                  "content_type": {
                    "description": "MIME type of the attachment",
                    "title": "Content Type",
                    "type": "string"
                  },
                  "filename": {
                    "description": "Name of the attachment file",
                    "title": "Filename",
                    "type": "string"
                  },
                  "inline": {
                    "description": "Whether the attachment is inline",
                    "title": "Inline",
                    "type": "boolean"
                  },
                  "size": {
                    "description": "Size of the attachment in bytes",
                    "title": "Size",
                    "type": "integer"
                  }
                },
                "required": ["attachment_id", "size", "inline", "filename", "content_type"],
                "title": "MessageAttachment",
                "type": "object"
              }
            },
            "properties": {
              "attachments": {
                "default": None,
                "description": "Message attachments",
                "items": {
                  "properties": {
                    "attachment_id": {
                      "description": "ID of the attachment",
                      "title": "Attachment Id",
                      "type": "string"
                    },
                    "content_type": {
                      "description": "MIME type of the attachment",
                      "title": "Content Type",
                      "type": "string"
                    },
                    "filename": {
                      "description": "Name of the attachment file",
                      "title": "Filename",
                      "type": "string"
                    },
                    "inline": {
                      "description": "Whether the attachment is inline",
                      "title": "Inline",
                      "type": "boolean"
                    },
                    "size": {
                      "description": "Size of the attachment in bytes",
                      "title": "Size",
                      "type": "integer"
                    }
                  },
                  "required": ["attachment_id", "size", "inline", "filename", "content_type"],
                  "title": "MessageAttachment",
                  "type": "object"
                },
                "nullable": True,
                "title": "Attachments",
                "type": "array"
              },
              "bcc": {
                "default": None,
                "description": "BCC email addresses",
                "items": {
                  "properties": {},
                  "type": "string"
                },
                "nullable": True,
                "title": "Bcc",
                "type": "array"
              },
              "cc": {
                "default": None,
                "description": "CC email addresses",
                "items": {
                  "properties": {},
                  "type": "string"
                },
                "nullable": True,
                "title": "Cc",
                "type": "array"
              },
              "created_at": {
                "description": "When the message was created",
                "title": "Created At",
                "type": "string"
              },
              "from": {
                "description": "Sender's email address",
                "title": "From",
                "type": "string"
              },
              "html": {
                "default": None,
                "description": "HTML content",
                "nullable": True,
                "title": "Html",
                "type": "string"
              },
              "in_reply_to": {
                "default": None,
                "description": "ID of message being replied to",
                "nullable": True,
                "title": "In Reply To",
                "type": "string"
              },
              "inbox_id": {
                "description": "ID of the inbox",
                "title": "Inbox Id",
                "type": "string"
              },
              "labels": {
                "description": "Labels applied to the message",
                "items": {
                  "properties": {},
                  "type": "string"
                },
                "title": "Labels",
                "type": "array"
              },
              "message_id": {
                "description": "ID of the message",
                "title": "Message Id",
                "type": "string"
              },
              "preview": {
                "default": None,
                "description": "Text preview of the message",
                "nullable": True,
                "title": "Preview",
                "type": "string"
              },
              "references": {
                "default": None,
                "description": "IDs of previous messages in thread",
                "items": {
                  "properties": {},
                  "type": "string"
                },
                "nullable": True,
                "title": "References",
                "type": "array"
              },
              "reply_to": {
                "default": None,
                "description": "Reply-to email addresses",
                "items": {
                  "properties": {},
                  "type": "string"
                },
                "nullable": True,
                "title": "Reply To",
                "type": "array"
              },
              "subject": {
                "default": None,
                "description": "Email subject",
                "nullable": True,
                "title": "Subject",
                "type": "string"
              },
              "text": {
                "default": None,
                "description": "Plain text content",
                "nullable": True,
                "title": "Text",
                "type": "string"
              },
              "thread_id": {
                "description": "ID of the thread",
                "title": "Thread Id",
                "type": "string"
              },
              "timestamp": {
                "description": "When the message was received",
                "title": "Timestamp",
                "type": "string"
              },
              "to": {
                "description": "Recipient email addresses",
                "items": {
                  "properties": {},
                  "type": "string"
                },
                "title": "To",
                "type": "array"
              },
              "updated_at": {
                "description": "When the message was last updated",
                "title": "Updated At",
                "type": "string"
              }
            },
            "required": ["inbox_id", "thread_id", "message_id", "labels", "timestamp", "from", "to", "updated_at", "created_at"],
            "title": "NewEmailPayload",
            "type": "object"
          },
          "slug": "AGENT_MAIL_NEW_EMAIL_TRIGGER",
          "type": "poll"
        }
