# Auto-generated by Composio CLI. Do not modify manually..

class ALCHEMY:
    """Map of Composio's ALCHEMY toolkit."""

    slug: str = "alchemy"

    class tools:
        GET_TRANSACTION_COUNT = "ALCHEMY_GET_TRANSACTION_COUNT"
        GET_NF_TS_FOR_CONTRACT = "ALCHEMY_GET_NF_TS_FOR_CONTRACT"
        GET_TOKEN_METADATA = "ALCHEMY_GET_TOKEN_METADATA"
        GET_OWNERS_FOR_NFT = "ALCHEMY_GET_OWNERS_FOR_NFT"
        GET_TOKEN_BALANCES = "ALCHEMY_GET_TOKEN_BALANCES"
        GET_NFT_SALES = "ALCHEMY_GET_NFT_SALES"
        GET_CONTRACT_METADATA = "ALCHEMY_GET_CONTRACT_METADATA"

    class triggers:
        pass
