# Auto-generated by Composio CLI. Do not modify manually..

class ALL_IMAGES_AI:
    """Map of Composio's ALL_IMAGES_AI toolkit."""

    slug: str = "all_images_ai"

    class tools:
        CHECK_API_KEY = "ALL_IMAGES_AI_CHECK_API_KEY"
        LIST_AUTOMATED_IMAGES = "ALL_IMAGES_AI_LIST_AUTOMATED_IMAGES"
        CREATE_WEBHOOK_ENDPOINT = "ALL_IMAGES_AI_CREATE_WEBHOOK_ENDPOINT"

    class triggers:
        pass
