# Auto-generated by Composio CLI. Do not modify manually..

class ALTTEXT_AI:
    """Map of Composio's ALTTEXT_AI toolkit."""

    slug: str = "alttext_ai"

    class tools:
        ALT_TEXT_AI_GET_ACCOUNT = "ALTTEXT_AI_ALT_TEXT_AI_GET_ACCOUNT"
        GET_IMAGES = "ALTTEXT_AI_GET_IMAGES"
        UPDATE_ACCOUNT = "ALTTEXT_AI_UPDATE_ACCOUNT"
        GET_ACCOUNT = "ALTTEXT_AI_GET_ACCOUNT"
        SEARCH_IMAGES = "ALTTEXT_AI_SEARCH_IMAGES"

    class triggers:
        pass
