# Auto-generated by Composio CLI. Do not modify manually..

class AMBIENT_WEATHER:
    """Map of Composio's AMBIENT_WEATHER toolkit."""

    slug: str = "ambient_weather"

    class tools:
        GET_DEVICES = "AMBIENT_WEATHER_GET_DEVICES"

    class triggers:
        pass
