# Auto-generated by Composio CLI. Do not modify manually..

class API_BIBLE:
    """Map of Composio's API_BIBLE toolkit."""

    slug: str = "api_bible"

    class tools:
        GET_ALL_BOOKS = "API_BIBLE_GET_ALL_BOOKS"
        GET_SUPPORTED_VERSIONS = "API_BIBLE_GET_SUPPORTED_VERSIONS"
        SEARCH_VERSES = "API_BIBLE_SEARCH_VERSES"
        GET_BIBLE = "API_BIBLE_GET_BIBLE"
        GET_SECTION = "API_BIBLE_GET_SECTION"
        GET_SECTIONS = "API_BIBLE_GET_SECTIONS"

    class triggers:
        pass
