# Auto-generated by Composio CLI. Do not modify manually..

class APIFLASH:
    """Map of Composio's APIFLASH toolkit."""

    slug: str = "apiflash"

    class tools:
        GET_QUOTA_INFORMATION = "APIFLASH_GET_QUOTA_INFORMATION"
        GET_SCREENSHOT_METADATA = "APIFLASH_GET_SCREENSHOT_METADATA"
        CAPTURE_WEBSITE_SCREENSHOT_POST = "APIFLASH_CAPTURE_WEBSITE_SCREENSHOT_POST"
        BATCH_CAPTURE_SCREENSHOTS = "APIFLASH_BATCH_CAPTURE_SCREENSHOTS"

    class triggers:
        pass
