# Auto-generated by Composio CLI. Do not modify manually..

class APPVEYOR:
    """Map of Composio's APPVEYOR toolkit."""

    slug: str = "appveyor"

    class tools:
        GET_ROLES = "APPVEYOR_GET_ROLES"
        GET_ROLE = "APPVEYOR_GET_ROLE"
        GET_ENVIRONMENTS = "APPVEYOR_GET_ENVIRONMENTS"
        GET_BUILD_ARTIFACTS = "APPVEYOR_GET_BUILD_ARTIFACTS"
        GET_PROJECTS = "APPVEYOR_GET_PROJECTS"
        GET_USERS = "APPVEYOR_GET_USERS"

    class triggers:
        pass
