# Auto-generated by Composio CLI. Do not modify manually..

class ASIN_DATA_API:
    """Map of Composio's ASIN_DATA_API toolkit."""

    slug: str = "asin_data_api"

    class tools:
        CLEAR_COLLECTION_REQUESTS = "ASIN_DATA_API_CLEAR_COLLECTION_REQUESTS"
        LIST_COLLECTION_REQUESTS = "ASIN_DATA_API_LIST_COLLECTION_REQUESTS"

    class triggers:
        pass
