# Auto-generated by Composio CLI. Do not modify manually..

class AUTOM:
    """Map of Composio's AUTOM toolkit."""

    slug: str = "autom"

    class tools:
        GOOGLE_IMAGES = "AUTOM_GOOGLE_IMAGES"
        GOOGLE_COUNTRIES = "AUTOM_GOOGLE_COUNTRIES"
        GOOGLE_LANGUAGES = "AUTOM_GOOGLE_LANGUAGES"
        GOOGLE_LOCATIONS = "AUTOM_GOOGLE_LOCATIONS"

    class triggers:
        pass
