# Auto-generated by Composio CLI. Do not modify manually..

class AYRSHARE:
    """Map of Composio's AYRSHARE toolkit."""

    slug: str = "ayrshare"

    class tools:
        CREATE_AUTO_SCHEDULE = "AYRSHARE_CREATE_AUTO_SCHEDULE"
        POST_SET_AUTO_SCHEDULE = "AYRSHARE_POST_SET_AUTO_SCHEDULE"
        DELETE_DELETE_POST = "AYRSHARE_DELETE_DELETE_POST"
        GET_POST_HISTORY = "AYRSHARE_GET_POST_HISTORY"

    class triggers:
        pass
