# Auto-generated by Composio CLI. Do not modify manually..

class BASEROW:
    """Map of Composio's BASEROW toolkit."""

    slug: str = "baserow"

    class tools:
        LIST_TABLES = "BASEROW_LIST_TABLES"
        LIST_DATABASES = "BASEROW_LIST_DATABASES"

    class triggers:
        pass
