# Auto-generated by Composio CLI. Do not modify manually..

class BEEMINDER:
    """Map of Composio's BEEMINDER toolkit."""

    slug: str = "beeminder"

    class tools:
        CREATE_CHARGE = "BEEMINDER_CREATE_CHARGE"
        GET_USER_INFORMATION = "BEEMINDER_GET_USER_INFORMATION"
        GET_ALL_GOALS = "BEEMINDER_GET_ALL_GOALS"
        GET_ARCHIVED_GOALS = "BEEMINDER_GET_ARCHIVED_GOALS"
        AUTHENTICATE_AND_REDIRECT_USER = "BEEMINDER_AUTHENTICATE_AND_REDIRECT_USER"

    class triggers:
        pass
