# Auto-generated by Composio CLI. Do not modify manually..

class BOLOFORMS:
    """Map of Composio's BOLOFORMS toolkit."""

    slug: str = "boloforms"

    class tools:
        GET_DOCUMENTS_LIST = "BOLOFORMS_GET_DOCUMENTS_LIST"

    class triggers:
        pass
