# Auto-generated by Composio CLI. Do not modify manually..

class BOLT_IOT:
    """Map of Composio's BOLT_IOT toolkit."""

    slug: str = "bolt_iot"

    class tools:
        SERIAL_WRITE = "BOLT_IOT_SERIAL_WRITE"
        DIGITAL_WRITE = "BOLT_IOT_DIGITAL_WRITE"
        SERIAL_READ = "BOLT_IOT_SERIAL_READ"
        SERIAL_WRITE_READ = "BOLT_IOT_SERIAL_WRITE_READ"
        CHECK_DEVICE_STATUS = "BOLT_IOT_CHECK_DEVICE_STATUS"
        ANALOG_READ = "BOLT_IOT_ANALOG_READ"

    class triggers:
        pass
