# Auto-generated by Composio CLI. Do not modify manually..

class BUGBUG:
    """Map of Composio's BUGBUG toolkit."""

    slug: str = "bugbug"

    class tools:
        LIST_SUITES = "BUGBUG_LIST_SUITES"
        RUN_TEST = "BUGBUG_RUN_TEST"
        LIST_TESTS = "BUGBUG_LIST_TESTS"
        GET_TEST_RUN_DETAILS = "BUGBUG_GET_TEST_RUN_DETAILS"

    class triggers:
        pass
