# Auto-generated by Composio CLI. Do not modify manually..

class BYTEFORMS:
    """Map of Composio's BYTEFORMS toolkit."""

    slug: str = "byteforms"

    class tools:
        GET_FORM_BY_ID = "BYTEFORMS_GET_FORM_BY_ID"
        CREATE_FORM = "BYTEFORMS_CREATE_FORM"
        DELETE_FORM = "BYTEFORMS_DELETE_FORM"
        GET_ALL_FORMS = "BYTEFORMS_GET_ALL_FORMS"
        GET_FORM_RESPONSES = "BYTEFORMS_GET_FORM_RESPONSES"

    class triggers:
        pass
