# Auto-generated by Composio CLI. Do not modify manually..

class CAMPAYN:
    """Map of Composio's CAMPAYN toolkit."""

    slug: str = "campayn"

    class tools:
        GET_REPORTS = "CAMPAYN_GET_REPORTS"
        GET_MESSAGE = "CAMPAYN_GET_MESSAGE"
        CREATE_CONTACT = "CAMPAYN_CREATE_CONTACT"
        DELETE_WEBFORM = "CAMPAYN_DELETE_WEBFORM"
        GET_LISTS = "CAMPAYN_GET_LISTS"
        UPDATE_LIST = "CAMPAYN_UPDATE_LIST"
        DELETE_LIST = "CAMPAYN_DELETE_LIST"
        GET_CONTACTS = "CAMPAYN_GET_CONTACTS"
        GET_MESSAGES = "CAMPAYN_GET_MESSAGES"
        GET_LIST = "CAMPAYN_GET_LIST"
        GET_WEBFORMS = "CAMPAYN_GET_WEBFORMS"
        GET_WEBFORM = "CAMPAYN_GET_WEBFORM"
        DELETE_CONTACT = "CAMPAYN_DELETE_CONTACT"
        GET_CONTACT = "CAMPAYN_GET_CONTACT"

    class triggers:
        pass
