# Auto-generated by Composio CLI. Do not modify manually..

class CARBONE:
    """Map of Composio's CARBONE toolkit."""

    slug: str = "carbone"

    class tools:
        DELETE_TEMPLATE = "CARBONE_DELETE_TEMPLATE"
        DOWNLOAD_TEMPLATE = "CARBONE_DOWNLOAD_TEMPLATE"
        GENERATE_TEMPLATE_ID = "CARBONE_GENERATE_TEMPLATE_ID"
        SET_API_VERSION = "CARBONE_SET_API_VERSION"
        GET_STATUS = "CARBONE_GET_STATUS"
        GENERATE_REPORT = "CARBONE_GENERATE_REPORT"
        UPLOAD_TEMPLATE = "CARBONE_UPLOAD_TEMPLATE"

    class triggers:
        pass
