# Auto-generated by Composio CLI. Do not modify manually..

class CATS:
    """Map of Composio's CATS toolkit."""

    slug: str = "cats"

    class tools:
        GET_PORTALS = "CATS_GET_PORTALS"

    class triggers:
        pass
