# Auto-generated by Composio CLI. Do not modify manually..

class CINCOPA:
    """Map of Composio's CINCOPA toolkit."""

    slug: str = "cincopa"

    class tools:
        ASSET_UPLOAD_FROM_URL_GET_STATUS = "CINCOPA_ASSET_UPLOAD_FROM_URL_GET_STATUS"
        ASSET_UPLOAD_FROM_URL = "CINCOPA_ASSET_UPLOAD_FROM_URL"
        ASSET_UPLOAD_FROM_URL_ABORT = "CINCOPA_ASSET_UPLOAD_FROM_URL_ABORT"
        PING = "CINCOPA_PING"

    class triggers:
        pass
