# Auto-generated by Composio CLI. Do not modify manually..

class CODACY:
    """Map of Composio's CODACY toolkit."""

    slug: str = "codacy"

    class tools:
        DELETE_API_TOKEN = "CODACY_DELETE_API_TOKEN"
        GET_USER_ORGANIZATIONS = "CODACY_GET_USER_ORGANIZATIONS"
        GET_ACCOUNT_DETAILS = "CODACY_GET_ACCOUNT_DETAILS"
        LIST_PROJECTS = "CODACY_LIST_PROJECTS"
        GET_ORGANIZATION_REPOSITORIES = "CODACY_GET_ORGANIZATION_REPOSITORIES"
        CREATE_API_TOKEN = "CODACY_CREATE_API_TOKEN"

    class triggers:
        pass
