# Auto-generated by Composio CLI. Do not modify manually..

class COINBASE:
    """Map of Composio's COINBASE toolkit."""

    slug: str = "coinbase"

    class tools:
        LIST_WALLETS = "COINBASE_LIST_WALLETS"

    class triggers:
        pass
