# Auto-generated by Composio CLI. Do not modify manually..

class CRAFTMYPDF:
    """Map of Composio's CRAFTMYPDF toolkit."""

    slug: str = "craftmypdf"

    class tools:
        CREATE_PDF_ASYNC = "CRAFTMYPDF_CREATE_PDF_ASYNC"
        LIST_TEMPLATES = "CRAFTMYPDF_LIST_TEMPLATES"
        CREATE_EDITOR_SESSION = "CRAFTMYPDF_CREATE_EDITOR_SESSION"

    class triggers:
        pass
