# Auto-generated by Composio CLI. Do not modify manually..

class CURATED:
    """Map of Composio's CURATED toolkit."""

    slug: str = "curated"

    class tools:
        LIST_ISSUES = "CURATED_LIST_ISSUES"
        CREATE_LINK = "CURATED_CREATE_LINK"
        LIST_PUBLICATIONS = "CURATED_LIST_PUBLICATIONS"
        LIST_CATEGORIES = "CURATED_LIST_CATEGORIES"
        CREATE_DRAFT_ISSUE = "CURATED_CREATE_DRAFT_ISSUE"
        LIST_EMAIL_SUBSCRIBERS = "CURATED_LIST_EMAIL_SUBSCRIBERS"

    class triggers:
        pass
