# Auto-generated by Composio CLI. Do not modify manually..

class DEEPSEEK:
    """Map of Composio's DEEPSEEK toolkit."""

    slug: str = "deepseek"

    class tools:
        GET_USER_BALANCE = "DEEPSEEK_GET_USER_BALANCE"
        CREATE_CHAT_COMPLETION = "DEEPSEEK_CREATE_CHAT_COMPLETION"
        LIST_MODELS = "DEEPSEEK_LIST_MODELS"
        CREATE_ANTHROPIC_MESSAGE = "DEEPSEEK_CREATE_ANTHROPIC_MESSAGE"

    class triggers:
        pass
