# Auto-generated by Composio CLI. Do not modify manually..

class DICTIONARY_API:
    """Map of Composio's DICTIONARY_API toolkit."""

    slug: str = "dictionary_api"

    class tools:
        GET_WORD_DEFINITION_V2 = "DICTIONARY_API_GET_WORD_DEFINITION_V2"

    class triggers:
        pass
