# Auto-generated by Composio CLI. Do not modify manually..

class DIFFBOT:
    """Map of Composio's DIFFBOT toolkit."""

    slug: str = "diffbot"

    class tools:
        SEARCH = "DIFFBOT_SEARCH"
        STOP_BULK_JOB = "DIFFBOT_STOP_BULK_JOB"
        GET_VIDEO = "DIFFBOT_GET_VIDEO"
        GET_ANALYZE = "DIFFBOT_GET_ANALYZE"
        RESOLVE_LOST_ID = "DIFFBOT_RESOLVE_LOST_ID"
        GET_ARTICLE = "DIFFBOT_GET_ARTICLE"
        START_CRAWL = "DIFFBOT_START_CRAWL"
        LIST_BULK_JOBS = "DIFFBOT_LIST_BULK_JOBS"
        GET_DISCUSSION = "DIFFBOT_GET_DISCUSSION"
        GET_IMAGE = "DIFFBOT_GET_IMAGE"
        GET_PRODUCT = "DIFFBOT_GET_PRODUCT"
        GET_EVENT = "DIFFBOT_GET_EVENT"
        START_BULK = "DIFFBOT_START_BULK"
        GET_ACCOUNT = "DIFFBOT_GET_ACCOUNT"

    class triggers:
        pass
