# Auto-generated by Composio CLI. Do not modify manually..

class DIGICERT:
    """Map of Composio's DIGICERT toolkit."""

    slug: str = "digicert"

    class tools:
        LIST_INTERMEDIATE_CERTIFICATES = "DIGICERT_LIST_INTERMEDIATE_CERTIFICATES"
        LIST_USERS = "DIGICERT_LIST_USERS"
        CHECK_PERMISSION = "DIGICERT_CHECK_PERMISSION"
        UPDATE_REPORT = "DIGICERT_UPDATE_REPORT"
        LIST_API_ACCESS_ROLES = "DIGICERT_LIST_API_ACCESS_ROLES"
        CREATE_API_KEY = "DIGICERT_CREATE_API_KEY"

    class triggers:
        pass
