# Auto-generated by Composio CLI. Do not modify manually..

class DOCUMINT:
    """Map of Composio's DOCUMINT toolkit."""

    slug: str = "documint"

    class tools:
        DELETE_TEMPLATE = "DOCUMINT_DELETE_TEMPLATE"
        GET_TEMPLATE = "DOCUMINT_GET_TEMPLATE"
        LIST_TEMPLATES = "DOCUMINT_LIST_TEMPLATES"
        UPDATE_TEMPLATE = "DOCUMINT_UPDATE_TEMPLATE"
        LIST_DOCUMENTS = "DOCUMINT_LIST_DOCUMENTS"

    class triggers:
        pass
