# Auto-generated by Composio CLI. Do not modify manually..

class DOCUPOST:
    """Map of Composio's DOCUPOST toolkit."""

    slug: str = "docupost"

    class tools:
        SEND_LETTER = "DOCUPOST_SEND_LETTER"
        SEND_POSTCARD = "DOCUPOST_SEND_POSTCARD"

    class triggers:
        pass
