# Auto-generated by Composio CLI. Do not modify manually..

class DPD2:
    """Map of Composio's DPD2 toolkit."""

    slug: str = "dpd2"

    class tools:
        LIST_CUSTOMERS = "DPD2_LIST_CUSTOMERS"
        VERIFY_NOTIFICATION = "DPD2_VERIFY_NOTIFICATION"
        GET_STOREFRONT = "DPD2_GET_STOREFRONT"
        LIST_SUBSCRIBERS = "DPD2_LIST_SUBSCRIBERS"
        LIST_PURCHASES = "DPD2_LIST_PURCHASES"
        PING = "DPD2_PING"
        LIST_STOREFRONTS = "DPD2_LIST_STOREFRONTS"

    class triggers:
        pass
