# Auto-generated by Composio CLI. Do not modify manually..

class DREAMSTUDIO:
    """Map of Composio's DREAMSTUDIO toolkit."""

    slug: str = "dreamstudio"

    class tools:
        USER_ACCOUNT = "DREAMSTUDIO_USER_ACCOUNT"
        GENERATE_IMAGE_FROM_IMAGE = "DREAMSTUDIO_GENERATE_IMAGE_FROM_IMAGE"
        LIST_ENGINES = "DREAMSTUDIO_LIST_ENGINES"
        USER_BALANCE = "DREAMSTUDIO_USER_BALANCE"

    class triggers:
        pass
