# Auto-generated by Composio CLI. Do not modify manually..

class DROMO:
    """Map of Composio's DROMO toolkit."""

    slug: str = "dromo"

    class tools:
        UPLOAD_FILE_TO_HEADLESS_IMPORT = "DROMO_UPLOAD_FILE_TO_HEADLESS_IMPORT"
        LIST_UPLOADS = "DROMO_LIST_UPLOADS"

    class triggers:
        pass
