# Auto-generated by Composio CLI. Do not modify manually..

class DUB:
    """Map of Composio's DUB toolkit."""

    slug: str = "dub"

    class tools:
        GET_LINK_INFO = "DUB_GET_LINK_INFO"
        LIST_DOMAINS = "DUB_LIST_DOMAINS"
        UPDATE_DOMAIN = "DUB_UPDATE_DOMAIN"
        GET_LINKS_COUNT = "DUB_GET_LINKS_COUNT"
        DELETE_TAG = "DUB_DELETE_TAG"
        BULK_UPDATE_LINKS = "DUB_BULK_UPDATE_LINKS"
        DELETE_DOMAIN = "DUB_DELETE_DOMAIN"
        UPDATE_TAG = "DUB_UPDATE_TAG"
        TRACK_OPEN = "DUB_TRACK_OPEN"
        BULK_DELETE_LINKS = "DUB_BULK_DELETE_LINKS"
        UPSERT_LINK = "DUB_UPSERT_LINK"
        CREATE_TAG = "DUB_CREATE_TAG"
        CREATE_DOMAIN = "DUB_CREATE_DOMAIN"
        UPDATE_WORKSPACE = "DUB_UPDATE_WORKSPACE"
        GET_TAGS = "DUB_GET_TAGS"
        GET_WORKSPACE = "DUB_GET_WORKSPACE"
        GET_LINKS = "DUB_GET_LINKS"

    class triggers:
        pass
