# Auto-generated by Composio CLI. Do not modify manually..

class ECHTPOST:
    """Map of Composio's ECHTPOST toolkit."""

    slug: str = "echtpost"

    class tools:
        LIST_TEMPLATES = "ECHTPOST_LIST_TEMPLATES"

    class triggers:
        pass
