# Auto-generated by Composio CLI. Do not modify manually..

class ELASTICSEARCH:
    """Map of Composio's ELASTICSEARCH toolkit."""

    slug: str = "elasticsearch"

    class tools:
        QUERY_INDEX = "ELASTICSEARCH_QUERY_INDEX"
        GET_INDEX_SCHEMA = "ELASTICSEARCH_GET_INDEX_SCHEMA"
        LIST_INDICES = "ELASTICSEARCH_LIST_INDICES"

    class triggers:
        pass
