# Auto-generated by Composio CLI. Do not modify manually..

class EMAILLISTVERIFY:
    """Map of Composio's EMAILLISTVERIFY toolkit."""

    slug: str = "emaillistverify"

    class tools:
        VERIFY_EMAIL_DETAILED = "EMAILLISTVERIFY_VERIFY_EMAIL_DETAILED"
        VERIFY_EMAIL = "EMAILLISTVERIFY_VERIFY_EMAIL"

    class triggers:
        pass
