# Auto-generated by Composio CLI. Do not modify manually..

class EODHD_APIS:
    """Map of Composio's EODHD_APIS toolkit."""

    slug: str = "eodhd_apis"

    class tools:
        GET_MACRO_INDICATORS = "EODHD_APIS_GET_MACRO_INDICATORS"
        GET_REAL_TIME_WEBSOCKET_US_TRADE = "EODHD_APIS_GET_REAL_TIME_WEBSOCKET_US_TRADE"
        GET_MUTUAL_FUNDS_DATA = "EODHD_APIS_GET_MUTUAL_FUNDS_DATA"
        GET_REAL_TIME_WEBSOCKET_FOREX = "EODHD_APIS_GET_REAL_TIME_WEBSOCKET_FOREX"

    class triggers:
        pass
