# Auto-generated by Composio CLI. Do not modify manually..

class EVENTZILLA:
    """Map of Composio's EVENTZILLA toolkit."""

    slug: str = "eventzilla"

    class tools:
        LIST_EVENTS = "EVENTZILLA_LIST_EVENTS"
        LIST_CATEGORIES = "EVENTZILLA_LIST_CATEGORIES"
        LIST_USERS = "EVENTZILLA_LIST_USERS"
        GET_USER_DETAILS = "EVENTZILLA_GET_USER_DETAILS"

    class triggers:
        pass
