# Auto-generated by Composio CLI. Do not modify manually..

class EXPOFP:
    """Map of Composio's EXPOFP toolkit."""

    slug: str = "expofp"

    class tools:
        LIST_ALL_EXPOS = "EXPOFP_LIST_ALL_EXPOS"
        REMOVE_CATEGORY = "EXPOFP_REMOVE_CATEGORY"
        UPDATE_CATEGORY = "EXPOFP_UPDATE_CATEGORY"
        LIST_ALL_EXPO_EXTRAS = "EXPOFP_LIST_ALL_EXPO_EXTRAS"
        ADD_CATEGORY = "EXPOFP_ADD_CATEGORY"

    class triggers:
        pass
