# Auto-generated by Composio CLI. Do not modify manually..

class FATHOM:
    """Map of Composio's FATHOM toolkit."""

    slug: str = "fathom"

    class tools:
        GET_RECORDING_SUMMARY = "FATHOM_GET_RECORDING_SUMMARY"
        CREATE_WEBHOOK = "FATHOM_CREATE_WEBHOOK"
        LIST_TEAMS = "FATHOM_LIST_TEAMS"
        GET_RECORDING_TRANSCRIPT = "FATHOM_GET_RECORDING_TRANSCRIPT"
        LIST_TEAM_MEMBERS = "FATHOM_LIST_TEAM_MEMBERS"
        LIST_MEETINGS = "FATHOM_LIST_MEETINGS"
        DELETE_WEBHOOK = "FATHOM_DELETE_WEBHOOK"

    class triggers:
        pass
