# Auto-generated by Composio CLI. Do not modify manually..

class FIREFLIES:
    """Map of Composio's FIREFLIES toolkit."""

    slug: str = "fireflies"

    class tools:
        GET_USER_BY_ID = "FIREFLIES_GET_USER_BY_ID"
        CONTINUE_ASK_FRED_THREAD = "FIREFLIES_CONTINUE_ASK_FRED_THREAD"
        UPDATE_MEETING_CHANNEL = "FIREFLIES_UPDATE_MEETING_CHANNEL"
        UPLOAD_AUDIO = "FIREFLIES_UPLOAD_AUDIO"
        GRAPHQL_QUERY = "FIREFLIES_GRAPHQL_QUERY"
        GET_BITE_BY_ID = "FIREFLIES_GET_BITE_BY_ID"
        ADD_TO_LIVE = "FIREFLIES_ADD_TO_LIVE"
        DELETE_TRANSCRIPT_BY_ID = "FIREFLIES_DELETE_TRANSCRIPT_BY_ID"
        GET_USER_GROUPS = "FIREFLIES_GET_USER_GROUPS"
        FETCH_AI_APP_OUTPUTS = "FIREFLIES_FETCH_AI_APP_OUTPUTS"
        GET_TRANSCRIPTS = "FIREFLIES_GET_TRANSCRIPTS"
        UPDATE_MEETING_PRIVACY = "FIREFLIES_UPDATE_MEETING_PRIVACY"
        CREATE_ASK_FRED_THREAD = "FIREFLIES_CREATE_ASK_FRED_THREAD"
        GET_ASK_FRED_THREADS = "FIREFLIES_GET_ASK_FRED_THREADS"
        GET_ASK_FRED_THREAD = "FIREFLIES_GET_ASK_FRED_THREAD"
        GET_TRANSCRIPT_BY_ID = "FIREFLIES_GET_TRANSCRIPT_BY_ID"
        GET_USERS = "FIREFLIES_GET_USERS"
        SET_USER_ROLE = "FIREFLIES_SET_USER_ROLE"
        CREATE_BITE = "FIREFLIES_CREATE_BITE"
        GET_BITES = "FIREFLIES_GET_BITES"
        UPDATE_MEETING_TITLE = "FIREFLIES_UPDATE_MEETING_TITLE"

    class triggers:
        TRANSCRIPTION_COMPLETE = {
          "config": {
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "TranscriptionCompleteConfig",
            "type": "object"
          },
          "description": "Triggers when a transcription is complete. Polls Fireflies API for transcripts\n    created or updated since the last poll time. Handles rate limiting gracefully.",
          "instructions": "",
          "name": "Transcription Complete Trigger",
          "payload": {
            "$defs": {
              "TranscriptSchema": {
                "properties": {
                  "id": {
                    "description": "The ID of the transcript",
                    "title": "Id",
                    "type": "string"
                  },
                  "summary": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The summary of the transcript",
                    "title": "Summary"
                  }
                },
                "required": ["id"],
                "title": "TranscriptSchema",
                "type": "object"
              }
            },
            "description": "Payload model for Fireflies transcript events.",
            "properties": {
              "event_type": {
                "default": "transcription_complete",
                "description": "Type of transcript event",
                "title": "Event Type",
                "type": "string"
              },
              "transcript": {
                "additionalProperties": False,
                "description": "The transcript that was completed",
                "properties": {
                  "id": {
                    "description": "The ID of the transcript",
                    "title": "Id",
                    "type": "string"
                  },
                  "summary": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The summary of the transcript",
                    "title": "Summary"
                  }
                },
                "required": ["id"],
                "title": "Transcript",
                "type": "object"
              }
            },
            "required": ["transcript"],
            "title": "TranscriptPayload",
            "type": "object"
          },
          "slug": "FIREFLIES_TRANSCRIPTION_COMPLETE",
          "type": "poll"
        }
