# Auto-generated by Composio CLI. Do not modify manually..

class FOLK:
    """Map of Composio's FOLK toolkit."""

    slug: str = "folk"

    class tools:
        CREATE_COMPANY = "FOLK_CREATE_COMPANY"
        GET_CURRENT_WORKSPACE_USER = "FOLK_GET_CURRENT_WORKSPACE_USER"
        LIST_GROUP_CUSTOM_FIELDS = "FOLK_LIST_GROUP_CUSTOM_FIELDS"
        LIST_USERS = "FOLK_LIST_USERS"
        UPDATE_COMPANY = "FOLK_UPDATE_COMPANY"
        LIST_COMPANIES = "FOLK_LIST_COMPANIES"
        DELETE_COMPANY = "FOLK_DELETE_COMPANY"
        DELETE_PERSON = "FOLK_DELETE_PERSON"
        LIST_GROUPS = "FOLK_LIST_GROUPS"
        GET_COMPANY = "FOLK_GET_COMPANY"
        GET_PERSON = "FOLK_GET_PERSON"
        LIST_PEOPLE = "FOLK_LIST_PEOPLE"

    class triggers:
        pass
