# Auto-generated by Composio CLI. Do not modify manually..

class GEOKEO:
    """Map of Composio's GEOKEO toolkit."""

    slug: str = "geokeo"

    class tools:
        REVERSE_GEOCODING = "GEOKEO_REVERSE_GEOCODING"
        FORWARD_GEOCODING = "GEOKEO_FORWARD_GEOCODING"

    class triggers:
        pass
