# Auto-generated by Composio CLI. Do not modify manually..

class GOOGLE_ADDRESS_VALIDATION:
    """Map of Composio's GOOGLE_ADDRESS_VALIDATION toolkit."""

    slug: str = "google_address_validation"

    class tools:
        PROVIDE_VALIDATION_FEEDBACK = "GOOGLE_ADDRESS_VALIDATION_PROVIDE_VALIDATION_FEEDBACK"
        VALIDATE_ADDRESS = "GOOGLE_ADDRESS_VALIDATION_VALIDATE_ADDRESS"

    class triggers:
        pass
