# Auto-generated by Composio CLI. Do not modify manually..

class GOOGLEDOCS:
    """Map of Composio's GOOGLEDOCS toolkit."""

    slug: str = "googledocs"

    class tools:
        DELETE_PARAGRAPH_BULLETS = "GOOGLEDOCS_DELETE_PARAGRAPH_BULLETS"
        UPDATE_DOCUMENT_SECTION_MARKDOWN = "GOOGLEDOCS_UPDATE_DOCUMENT_SECTION_MARKDOWN"
        CREATE_FOOTNOTE = "GOOGLEDOCS_CREATE_FOOTNOTE"
        REPLACE_IMAGE = "GOOGLEDOCS_REPLACE_IMAGE"
        LIST_SPREADSHEET_CHARTS_ACTION = "GOOGLEDOCS_LIST_SPREADSHEET_CHARTS_ACTION"
        CREATE_NAMED_RANGE = "GOOGLEDOCS_CREATE_NAMED_RANGE"
        SEARCH_DOCUMENTS = "GOOGLEDOCS_SEARCH_DOCUMENTS"
        UPDATE_DOCUMENT_STYLE = "GOOGLEDOCS_UPDATE_DOCUMENT_STYLE"
        CREATE_DOCUMENT_MARKDOWN = "GOOGLEDOCS_CREATE_DOCUMENT_MARKDOWN"
        UPDATE_TABLE_ROW_STYLE = "GOOGLEDOCS_UPDATE_TABLE_ROW_STYLE"
        GET_DOCUMENT_BY_ID = "GOOGLEDOCS_GET_DOCUMENT_BY_ID"
        CREATE_PARAGRAPH_BULLETS = "GOOGLEDOCS_CREATE_PARAGRAPH_BULLETS"
        DELETE_NAMED_RANGE = "GOOGLEDOCS_DELETE_NAMED_RANGE"
        INSERT_INLINE_IMAGE = "GOOGLEDOCS_INSERT_INLINE_IMAGE"
        DELETE_CONTENT_RANGE = "GOOGLEDOCS_DELETE_CONTENT_RANGE"
        CREATE_FOOTER = "GOOGLEDOCS_CREATE_FOOTER"
        REPLACE_ALL_TEXT = "GOOGLEDOCS_REPLACE_ALL_TEXT"
        DELETE_FOOTER = "GOOGLEDOCS_DELETE_FOOTER"
        CREATE_DOCUMENT = "GOOGLEDOCS_CREATE_DOCUMENT"
        UNMERGE_TABLE_CELLS = "GOOGLEDOCS_UNMERGE_TABLE_CELLS"
        CREATE_HEADER = "GOOGLEDOCS_CREATE_HEADER"
        DELETE_TABLE = "GOOGLEDOCS_DELETE_TABLE"
        DELETE_TABLE_ROW = "GOOGLEDOCS_DELETE_TABLE_ROW"
        INSERT_TABLE_ACTION = "GOOGLEDOCS_INSERT_TABLE_ACTION"
        GET_CHARTS_FROM_SPREADSHEET = "GOOGLEDOCS_GET_CHARTS_FROM_SPREADSHEET"
        DELETE_TABLE_COLUMN = "GOOGLEDOCS_DELETE_TABLE_COLUMN"
        INSERT_TABLE_COLUMN = "GOOGLEDOCS_INSERT_TABLE_COLUMN"
        UPDATE_DOCUMENT_MARKDOWN = "GOOGLEDOCS_UPDATE_DOCUMENT_MARKDOWN"
        UPDATE_EXISTING_DOCUMENT = "GOOGLEDOCS_UPDATE_EXISTING_DOCUMENT"
        INSERT_TEXT_ACTION = "GOOGLEDOCS_INSERT_TEXT_ACTION"
        DELETE_HEADER = "GOOGLEDOCS_DELETE_HEADER"
        COPY_DOCUMENT = "GOOGLEDOCS_COPY_DOCUMENT"
        INSERT_PAGE_BREAK = "GOOGLEDOCS_INSERT_PAGE_BREAK"

    class triggers:
        DOCUMENT_DELETED_TRIGGER = {
          "config": {
            "description": "Configuration for Google Docs document deleted trigger.",
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "max_results": {
                "anyOf": [{
                    "maximum": 1000,
                    "minimum": 1,
                    "type": "integer"
                  }, {
                    "type": "null"
                  }],
                "default": 10,
                "description": "Maximum number of documents to check in each poll (1-1000)",
                "title": "Max Results"
              },
              "query": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Optional search query to filter documents. Leave empty to monitor all documents for deletion.",
                "examples": ["name contains 'report'", "fullText contains 'draft'"],
                "title": "Query"
              }
            },
            "title": "DocumentDeletedConfig",
            "type": "object"
          },
          "description": "Triggers when an existing Google Doc is deleted (moved to trash).\n    This trigger monitors Google Docs and fires when documents are trashed.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - This trigger monitors Google Docs for documents moved to trash (deleted).\n    - You can optionally provide a search query to filter which documents to monitor.\n    - The trigger will detect when a document's trashed status changes from false to true.\n    - Use max_results to control how many documents to check in each poll (default: 10).\n    ",
          "name": "Document Deleted",
          "payload": {
            "$defs": {
              "GoogleDocSchema": {
                "description": "Schema for a Google Doc.",
                "properties": {
                  "createdTime": {
                    "description": "Creation time in ISO format",
                    "title": "Createdtime",
                    "type": "string"
                  },
                  "id": {
                    "description": "Unique identifier of the document",
                    "title": "Id",
                    "type": "string"
                  },
                  "lastModifyingUser": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Information about the last user who modified the document",
                    "title": "Lastmodifyinguser"
                  },
                  "mimeType": {
                    "description": "MIME type of the document",
                    "title": "Mimetype",
                    "type": "string"
                  },
                  "modifiedTime": {
                    "description": "Last modification time in ISO format",
                    "title": "Modifiedtime",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the document",
                    "title": "Name",
                    "type": "string"
                  },
                  "owners": {
                    "anyOf": [{
                        "items": {
                          "additionalProperties": True,
                          "type": "object"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of document owners",
                    "title": "Owners"
                  },
                  "shared": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is shared",
                    "title": "Shared"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the document in bytes",
                    "title": "Size"
                  },
                  "starred": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is starred",
                    "title": "Starred"
                  },
                  "trashed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is in trash",
                    "title": "Trashed"
                  },
                  "webViewLink": {
                    "description": "Link to view the document in browser",
                    "title": "Webviewlink",
                    "type": "string"
                  }
                },
                "required": ["id", "name", "mimeType", "createdTime", "modifiedTime", "webViewLink"],
                "title": "GoogleDocSchema",
                "type": "object"
              }
            },
            "description": "Payload for Google Docs document deleted event.",
            "properties": {
              "document": {
                "additionalProperties": False,
                "description": "The deleted Google document",
                "properties": {
                  "createdTime": {
                    "description": "Creation time in ISO format",
                    "title": "Created Time",
                    "type": "string"
                  },
                  "id": {
                    "description": "Unique identifier of the document",
                    "title": "Id",
                    "type": "string"
                  },
                  "lastModifyingUser": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Information about the last user who modified the document",
                    "title": "Last Modifying User"
                  },
                  "mimeType": {
                    "description": "MIME type of the document",
                    "title": "Mime Type",
                    "type": "string"
                  },
                  "modifiedTime": {
                    "description": "Last modification time in ISO format",
                    "title": "Modified Time",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the document",
                    "title": "Name",
                    "type": "string"
                  },
                  "owners": {
                    "anyOf": [{
                        "items": {
                          "additionalProperties": True,
                          "type": "object"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of document owners",
                    "title": "Owners"
                  },
                  "shared": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is shared",
                    "title": "Shared"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the document in bytes",
                    "title": "Size"
                  },
                  "starred": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is starred",
                    "title": "Starred"
                  },
                  "trashed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is in trash",
                    "title": "Trashed"
                  },
                  "webViewLink": {
                    "description": "Link to view the document in browser",
                    "title": "Web View Link",
                    "type": "string"
                  }
                },
                "required": ["id", "name", "mimeType", "createdTime", "modifiedTime", "webViewLink"],
                "title": "Document",
                "type": "object"
              },
              "event_type": {
                "default": "document_deleted",
                "description": "Type of event that occurred",
                "title": "Event Type",
                "type": "string"
              }
            },
            "required": ["document"],
            "title": "DocumentDeletedPayload",
            "type": "object"
          },
          "slug": "GOOGLEDOCS_DOCUMENT_DELETED_TRIGGER",
          "type": "poll"
        }
        DOCUMENT_UPDATED_TRIGGER = {
          "config": {
            "description": "Configuration for Google Docs document updated trigger.",
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "max_results": {
                "anyOf": [{
                    "maximum": 1000,
                    "minimum": 1,
                    "type": "integer"
                  }, {
                    "type": "null"
                  }],
                "default": 10,
                "description": "Maximum number of documents to check in each poll (1-1000)",
                "title": "Max Results"
              },
              "query": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Optional search query to filter documents. Leave empty to monitor all documents.",
                "examples": ["name contains 'report'", "fullText contains 'status'"],
                "title": "Query"
              }
            },
            "title": "DocumentUpdatedConfig",
            "type": "object"
          },
          "description": "Triggers when an existing Google Doc is updated or modified.\n    This trigger monitors Google Docs and fires when documents are updated.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - This trigger monitors Google Docs for updates to existing documents.\n    - You can optionally provide a search query to filter which documents to monitor.\n    - The trigger will detect modifications based on the document's modifiedTime.\n    - Use max_results to control how many documents to check in each poll (default: 10).\n    ",
          "name": "Document Updated",
          "payload": {
            "$defs": {
              "GoogleDocSchema": {
                "description": "Schema for a Google Doc.",
                "properties": {
                  "createdTime": {
                    "description": "Creation time in ISO format",
                    "title": "Createdtime",
                    "type": "string"
                  },
                  "id": {
                    "description": "Unique identifier of the document",
                    "title": "Id",
                    "type": "string"
                  },
                  "lastModifyingUser": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Information about the last user who modified the document",
                    "title": "Lastmodifyinguser"
                  },
                  "mimeType": {
                    "description": "MIME type of the document",
                    "title": "Mimetype",
                    "type": "string"
                  },
                  "modifiedTime": {
                    "description": "Last modification time in ISO format",
                    "title": "Modifiedtime",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the document",
                    "title": "Name",
                    "type": "string"
                  },
                  "owners": {
                    "anyOf": [{
                        "items": {
                          "additionalProperties": True,
                          "type": "object"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of document owners",
                    "title": "Owners"
                  },
                  "shared": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is shared",
                    "title": "Shared"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the document in bytes",
                    "title": "Size"
                  },
                  "starred": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is starred",
                    "title": "Starred"
                  },
                  "trashed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is in trash",
                    "title": "Trashed"
                  },
                  "webViewLink": {
                    "description": "Link to view the document in browser",
                    "title": "Webviewlink",
                    "type": "string"
                  }
                },
                "required": ["id", "name", "mimeType", "createdTime", "modifiedTime", "webViewLink"],
                "title": "GoogleDocSchema",
                "type": "object"
              }
            },
            "description": "Payload for Google Docs document updated event.",
            "properties": {
              "document": {
                "additionalProperties": False,
                "description": "The updated Google document",
                "properties": {
                  "createdTime": {
                    "description": "Creation time in ISO format",
                    "title": "Created Time",
                    "type": "string"
                  },
                  "id": {
                    "description": "Unique identifier of the document",
                    "title": "Id",
                    "type": "string"
                  },
                  "lastModifyingUser": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Information about the last user who modified the document",
                    "title": "Last Modifying User"
                  },
                  "mimeType": {
                    "description": "MIME type of the document",
                    "title": "Mime Type",
                    "type": "string"
                  },
                  "modifiedTime": {
                    "description": "Last modification time in ISO format",
                    "title": "Modified Time",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the document",
                    "title": "Name",
                    "type": "string"
                  },
                  "owners": {
                    "anyOf": [{
                        "items": {
                          "additionalProperties": True,
                          "type": "object"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of document owners",
                    "title": "Owners"
                  },
                  "shared": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is shared",
                    "title": "Shared"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the document in bytes",
                    "title": "Size"
                  },
                  "starred": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is starred",
                    "title": "Starred"
                  },
                  "trashed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is in trash",
                    "title": "Trashed"
                  },
                  "webViewLink": {
                    "description": "Link to view the document in browser",
                    "title": "Web View Link",
                    "type": "string"
                  }
                },
                "required": ["id", "name", "mimeType", "createdTime", "modifiedTime", "webViewLink"],
                "title": "Document",
                "type": "object"
              },
              "event_type": {
                "default": "document_updated",
                "description": "Type of event that occurred",
                "title": "Event Type",
                "type": "string"
              }
            },
            "required": ["document"],
            "title": "DocumentUpdatedPayload",
            "type": "object"
          },
          "slug": "GOOGLEDOCS_DOCUMENT_UPDATED_TRIGGER",
          "type": "poll"
        }
        FOLDER_CREATED_TRIGGER = {
          "config": {
            "description": "Configuration for Google Drive folder created trigger.",
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "max_results": {
                "anyOf": [{
                    "maximum": 1000,
                    "minimum": 1,
                    "type": "integer"
                  }, {
                    "type": "null"
                  }],
                "default": 10,
                "description": "Maximum number of folders to check in each poll (1-1000)",
                "title": "Max Results"
              }
            },
            "title": "FolderCreatedConfig",
            "type": "object"
          },
          "description": "Triggers when a new folder is created in the root folder of Google Drive.\n    This trigger monitors Google Drive and fires when new folders are detected in the root directory.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - This trigger monitors Google Drive for newly created folders in the root directory.\n    - Only folders created directly in the root folder (My Drive) will trigger this event.\n    - The trigger will detect folders created after the trigger is set up.\n    - Use max_results to control how many folders to check in each poll (default: 10).\n    - Folders in trash are automatically excluded from monitoring.\n    ",
          "name": "New Folder Created in Root",
          "payload": {
            "$defs": {
              "GoogleFolderSchema": {
                "description": "Schema for a Google Drive folder.",
                "properties": {
                  "createdTime": {
                    "description": "Creation time in ISO format",
                    "title": "Createdtime",
                    "type": "string"
                  },
                  "id": {
                    "description": "Unique identifier of the folder",
                    "title": "Id",
                    "type": "string"
                  },
                  "mimeType": {
                    "description": "MIME type of the folder",
                    "title": "Mimetype",
                    "type": "string"
                  },
                  "modifiedTime": {
                    "description": "Last modification time in ISO format",
                    "title": "Modifiedtime",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the folder",
                    "title": "Name",
                    "type": "string"
                  },
                  "owners": {
                    "anyOf": [{
                        "items": {
                          "additionalProperties": True,
                          "type": "object"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of folder owners",
                    "title": "Owners"
                  },
                  "parents": {
                    "anyOf": [{
                        "items": {
                          "type": "string"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of parent folder IDs",
                    "title": "Parents"
                  },
                  "shared": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the folder is shared",
                    "title": "Shared"
                  },
                  "starred": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the folder is starred",
                    "title": "Starred"
                  },
                  "trashed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the folder is in trash",
                    "title": "Trashed"
                  },
                  "webViewLink": {
                    "description": "Link to view the folder in browser",
                    "title": "Webviewlink",
                    "type": "string"
                  }
                },
                "required": ["id", "name", "mimeType", "createdTime", "modifiedTime", "webViewLink"],
                "title": "GoogleFolderSchema",
                "type": "object"
              }
            },
            "description": "Payload for Google Drive folder created event.",
            "properties": {
              "event_type": {
                "default": "folder_created",
                "description": "Type of event that occurred",
                "title": "Event Type",
                "type": "string"
              },
              "folder": {
                "additionalProperties": False,
                "description": "The newly created Google Drive folder",
                "properties": {
                  "createdTime": {
                    "description": "Creation time in ISO format",
                    "title": "Created Time",
                    "type": "string"
                  },
                  "id": {
                    "description": "Unique identifier of the folder",
                    "title": "Id",
                    "type": "string"
                  },
                  "mimeType": {
                    "description": "MIME type of the folder",
                    "title": "Mime Type",
                    "type": "string"
                  },
                  "modifiedTime": {
                    "description": "Last modification time in ISO format",
                    "title": "Modified Time",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the folder",
                    "title": "Name",
                    "type": "string"
                  },
                  "owners": {
                    "anyOf": [{
                        "items": {
                          "additionalProperties": True,
                          "type": "object"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of folder owners",
                    "title": "Owners"
                  },
                  "parents": {
                    "anyOf": [{
                        "items": {
                          "type": "string"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of parent folder IDs",
                    "title": "Parents"
                  },
                  "shared": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the folder is shared",
                    "title": "Shared"
                  },
                  "starred": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the folder is starred",
                    "title": "Starred"
                  },
                  "trashed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the folder is in trash",
                    "title": "Trashed"
                  },
                  "webViewLink": {
                    "description": "Link to view the folder in browser",
                    "title": "Web View Link",
                    "type": "string"
                  }
                },
                "required": ["id", "name", "mimeType", "createdTime", "modifiedTime", "webViewLink"],
                "title": "Folder",
                "type": "object"
              }
            },
            "required": ["folder"],
            "title": "GoogleFolderPayload",
            "type": "object"
          },
          "slug": "GOOGLEDOCS_FOLDER_CREATED_TRIGGER",
          "type": "poll"
        }
        PAGE_ADDED_TRIGGER = {
          "config": {
            "description": "Configuration for Google Docs page added trigger.",
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "max_results": {
                "anyOf": [{
                    "maximum": 1000,
                    "minimum": 1,
                    "type": "integer"
                  }, {
                    "type": "null"
                  }],
                "default": 10,
                "description": "Maximum number of documents to check in each poll (1-1000)",
                "title": "Max Results"
              },
              "query": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Optional search query to filter documents. Can search by name (name contains 'report'), full text content (fullText contains 'important'), or use complex queries with operators like 'and', 'or', 'not'. Leave empty to monitor all documents.",
                "examples": ["name contains 'report'", "fullText contains 'important'", "name contains 'project' and fullText contains 'status'"],
                "title": "Query"
              }
            },
            "title": "PageAddedConfig",
            "type": "object"
          },
          "description": "Triggers when a new Google Doc is added/created.\n    This trigger monitors Google Docs and fires when new documents are detected.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - This trigger monitors Google Docs for newly created documents.\n    - You can optionally provide a search query to filter which documents to monitor.\n    - The trigger will detect documents created after the trigger is set up.\n    - Use max_results to control how many documents to check in each poll (default: 10).\n    - Examples of search queries:\n      - name contains 'report' - Monitor documents with 'report' in the name\n      - fullText contains 'important' - Monitor documents containing the word 'important'\n      - Leave query empty to monitor all new documents\n    ",
          "name": "New Document Added",
          "payload": {
            "$defs": {
              "GoogleDocSchema": {
                "description": "Schema for a Google Doc.",
                "properties": {
                  "createdTime": {
                    "description": "Creation time in ISO format",
                    "title": "Createdtime",
                    "type": "string"
                  },
                  "id": {
                    "description": "Unique identifier of the document",
                    "title": "Id",
                    "type": "string"
                  },
                  "lastModifyingUser": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Information about the last user who modified the document",
                    "title": "Lastmodifyinguser"
                  },
                  "mimeType": {
                    "description": "MIME type of the document",
                    "title": "Mimetype",
                    "type": "string"
                  },
                  "modifiedTime": {
                    "description": "Last modification time in ISO format",
                    "title": "Modifiedtime",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the document",
                    "title": "Name",
                    "type": "string"
                  },
                  "owners": {
                    "anyOf": [{
                        "items": {
                          "additionalProperties": True,
                          "type": "object"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of document owners",
                    "title": "Owners"
                  },
                  "shared": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is shared",
                    "title": "Shared"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the document in bytes",
                    "title": "Size"
                  },
                  "starred": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is starred",
                    "title": "Starred"
                  },
                  "trashed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is in trash",
                    "title": "Trashed"
                  },
                  "webViewLink": {
                    "description": "Link to view the document in browser",
                    "title": "Webviewlink",
                    "type": "string"
                  }
                },
                "required": ["id", "name", "mimeType", "createdTime", "modifiedTime", "webViewLink"],
                "title": "GoogleDocSchema",
                "type": "object"
              }
            },
            "description": "Payload for Google Docs page added event.",
            "properties": {
              "document": {
                "additionalProperties": False,
                "description": "The newly added Google document",
                "properties": {
                  "createdTime": {
                    "description": "Creation time in ISO format",
                    "title": "Created Time",
                    "type": "string"
                  },
                  "id": {
                    "description": "Unique identifier of the document",
                    "title": "Id",
                    "type": "string"
                  },
                  "lastModifyingUser": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Information about the last user who modified the document",
                    "title": "Last Modifying User"
                  },
                  "mimeType": {
                    "description": "MIME type of the document",
                    "title": "Mime Type",
                    "type": "string"
                  },
                  "modifiedTime": {
                    "description": "Last modification time in ISO format",
                    "title": "Modified Time",
                    "type": "string"
                  },
                  "name": {
                    "description": "Name of the document",
                    "title": "Name",
                    "type": "string"
                  },
                  "owners": {
                    "anyOf": [{
                        "items": {
                          "additionalProperties": True,
                          "type": "object"
                        },
                        "type": "array"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "List of document owners",
                    "title": "Owners"
                  },
                  "shared": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is shared",
                    "title": "Shared"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the document in bytes",
                    "title": "Size"
                  },
                  "starred": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is starred",
                    "title": "Starred"
                  },
                  "trashed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the document is in trash",
                    "title": "Trashed"
                  },
                  "webViewLink": {
                    "description": "Link to view the document in browser",
                    "title": "Web View Link",
                    "type": "string"
                  }
                },
                "required": ["id", "name", "mimeType", "createdTime", "modifiedTime", "webViewLink"],
                "title": "Document",
                "type": "object"
              },
              "event_type": {
                "default": "document_added",
                "description": "Type of event that occurred",
                "title": "Event Type",
                "type": "string"
              }
            },
            "required": ["document"],
            "title": "GoogleDocPayload",
            "type": "object"
          },
          "slug": "GOOGLEDOCS_PAGE_ADDED_TRIGGER",
          "type": "poll"
        }
