# Auto-generated by Composio CLI. Do not modify manually..

class GUMROAD:
    """Map of Composio's GUMROAD toolkit."""

    slug: str = "gumroad"

    class tools:
        SUBSCRIBE_TO_RESOURCE = "GUMROAD_SUBSCRIBE_TO_RESOURCE"
        GET_USER = "GUMROAD_GET_USER"
        GET_RESOURCE_SUBSCRIPTIONS = "GUMROAD_GET_RESOURCE_SUBSCRIPTIONS"
        GET_SALES = "GUMROAD_GET_SALES"
        UNSUBSCRIBE_FROM_RESOURCE = "GUMROAD_UNSUBSCRIBE_FROM_RESOURCE"

    class triggers:
        pass
