# Auto-generated by Composio CLI. Do not modify manually..

class HONEYBADGER:
    """Map of Composio's HONEYBADGER toolkit."""

    slug: str = "honeybadger"

    class tools:
        UPLOAD_SOURCE_MAP = "HONEYBADGER_UPLOAD_SOURCE_MAP"
        REPORT_EXCEPTION = "HONEYBADGER_REPORT_EXCEPTION"
        REPORT_CHECK_IN = "HONEYBADGER_REPORT_CHECK_IN"
        UPLOAD_FILE_TO_S3 = "HONEYBADGER_UPLOAD_FILE_TO_S3"
        REPORT_DEPLOYMENT = "HONEYBADGER_REPORT_DEPLOYMENT"
        REPORT_EVENT = "HONEYBADGER_REPORT_EVENT"

    class triggers:
        pass
