# Auto-generated by Composio CLI. Do not modify manually..

class HUMANITIX:
    """Map of Composio's HUMANITIX toolkit."""

    slug: str = "humanitix"

    class tools:
        GET_EVENTS = "HUMANITIX_GET_EVENTS"
        GET_TAGS = "HUMANITIX_GET_TAGS"
        GET_EVENT = "HUMANITIX_GET_EVENT"

    class triggers:
        pass
