# Auto-generated by Composio CLI. Do not modify manually..

class IMEJIS_IO:
    """Map of Composio's IMEJIS_IO toolkit."""

    slug: str = "imejis_io"

    class tools:
        LIST_DESIGNS = "IMEJIS_IO_LIST_DESIGNS"

    class triggers:
        pass
