# Auto-generated by Composio CLI. Do not modify manually..

class INSTACART:
    """Map of Composio's INSTACART toolkit."""

    slug: str = "instacart"

    class tools:
        CREATE_RECIPE_PAGE = "INSTACART_CREATE_RECIPE_PAGE"
        GET_NEARBY_RETAILERS = "INSTACART_GET_NEARBY_RETAILERS"
        CREATE_SHOPPING_LIST_PAGE = "INSTACART_CREATE_SHOPPING_LIST_PAGE"

    class triggers:
        pass
