# Auto-generated by Composio CLI. Do not modify manually..

class IP2LOCATION_IO:
    """Map of Composio's IP2LOCATION_IO toolkit."""

    slug: str = "ip2location_io"

    class tools:
        DOMAIN_WHOIS = "IP2LOCATION_IO_DOMAIN_WHOIS"
        IP2_WHOIS_HOSTED_DOMAIN = "IP2LOCATION_IO_IP2_WHOIS_HOSTED_DOMAIN"
        BULK_IP_GEOLOCATION = "IP2LOCATION_IO_BULK_IP_GEOLOCATION"
        GET_API_KEY = "IP2LOCATION_IO_GET_API_KEY"

    class triggers:
        pass
