# Auto-generated by Composio CLI. Do not modify manually..

class IPINFO_IO:
    """Map of Composio's IPINFO_IO toolkit."""

    slug: str = "ipinfo_io"

    class tools:
        BATCH_LITE_LOOKUP = "IPINFO_IO_BATCH_LITE_LOOKUP"
        GET_PRIVACY_DETAILS = "IPINFO_IO_GET_PRIVACY_DETAILS"
        GET_ABUSE_CONTACT = "IPINFO_IO_GET_ABUSE_CONTACT"
        GET_COMPANY_INFO = "IPINFO_IO_GET_COMPANY_INFO"
        GET_IP_INFO = "IPINFO_IO_GET_IP_INFO"
        GET_CARRIER_INFO = "IPINFO_IO_GET_CARRIER_INFO"
        BATCH_LOOKUP = "IPINFO_IO_BATCH_LOOKUP"

    class triggers:
        pass
