# Auto-generated by Composio CLI. Do not modify manually..

class JOTFORM:
    """Map of Composio's JOTFORM toolkit."""

    slug: str = "jotform"

    class tools:
        GET_USER_SETTINGS = "JOTFORM_GET_USER_SETTINGS"
        GET_USER_FORMS = "JOTFORM_GET_USER_FORMS"
        GET_SYSTEM_PLAN = "JOTFORM_GET_SYSTEM_PLAN"
        GET_USER_FOLDERS = "JOTFORM_GET_USER_FOLDERS"
        GET_USER_HISTORY = "JOTFORM_GET_USER_HISTORY"
        GET_USER_DETAILS = "JOTFORM_GET_USER_DETAILS"

    class triggers:
        pass
