# Auto-generated by Composio CLI. Do not modify manually..

class KRAKEN_IO:
    """Map of Composio's KRAKEN_IO toolkit."""

    slug: str = "kraken_io"

    class tools:
        PRESERVE_METADATA = "KRAKEN_IO_PRESERVE_METADATA"
        CHECK_USER_STATUS = "KRAKEN_IO_CHECK_USER_STATUS"
        SANDBOX_UPLOAD = "KRAKEN_IO_SANDBOX_UPLOAD"
        OPTIMIZE_IMAGE_URL = "KRAKEN_IO_OPTIMIZE_IMAGE_URL"

    class triggers:
        pass
