# Auto-generated by Composio CLI. Do not modify manually..

class LANGBASE:
    """Map of Composio's LANGBASE toolkit."""

    slug: str = "langbase"

    class tools:
        MEMORY_DELETE = "LANGBASE_MEMORY_DELETE"
        MEMORY_CREATE = "LANGBASE_MEMORY_CREATE"
        MEMORY_LIST = "LANGBASE_MEMORY_LIST"
        CHUNKER_SPLIT_CONTENT = "LANGBASE_CHUNKER_SPLIT_CONTENT"
        LIST_THREAD_MESSAGES = "LANGBASE_LIST_THREAD_MESSAGES"
        DOCUMENT_LIST = "LANGBASE_DOCUMENT_LIST"
        PIPE_CREATE = "LANGBASE_PIPE_CREATE"
        PIPE_LIST = "LANGBASE_PIPE_LIST"
        CREATE_THREAD = "LANGBASE_CREATE_THREAD"
        GET_THREAD = "LANGBASE_GET_THREAD"

    class triggers:
        pass
