# Auto-generated by Composio CLI. Do not modify manually..

class LEADOKU:
    """Map of Composio's LEADOKU toolkit."""

    slug: str = "leadoku"

    class tools:
        GET_NEW_CONNECTIONS = "LEADOKU_GET_NEW_CONNECTIONS"

    class triggers:
        pass
