# Auto-generated by Composio CLI. Do not modify manually..

class LESSONSPACE:
    """Map of Composio's LESSONSPACE toolkit."""

    slug: str = "lessonspace"

    class tools:
        GET_ORGANISATION_DETAILS = "LESSONSPACE_GET_ORGANISATION_DETAILS"
        CREATE_DEMO_SPACE = "LESSONSPACE_CREATE_DEMO_SPACE"
        LAUNCH_SPACE = "LESSONSPACE_LAUNCH_SPACE"
        GET_ORGANISATION_SESSION_LIST = "LESSONSPACE_GET_ORGANISATION_SESSION_LIST"

    class triggers:
        pass
