# Auto-generated by Composio CLI. Do not modify manually..

class LINEAR:
    """Map of Composio's LINEAR toolkit."""

    slug: str = "linear"

    class tools:
        GET_CYCLES_BY_TEAM_ID = "LINEAR_GET_CYCLES_BY_TEAM_ID"
        LIST_LINEAR_TEAMS = "LINEAR_LIST_LINEAR_TEAMS"
        CREATE_LINEAR_PROJECT = "LINEAR_CREATE_LINEAR_PROJECT"
        LIST_LINEAR_PROJECTS = "LINEAR_LIST_LINEAR_PROJECTS"
        REMOVE_REACTION = "LINEAR_REMOVE_REACTION"
        LIST_ISSUES_BY_TEAM_ID = "LINEAR_LIST_ISSUES_BY_TEAM_ID"
        LIST_LINEAR_STATES = "LINEAR_LIST_LINEAR_STATES"
        LIST_LINEAR_USERS = "LINEAR_LIST_LINEAR_USERS"
        CREATE_LINEAR_ATTACHMENT = "LINEAR_CREATE_LINEAR_ATTACHMENT"
        GET_LINEAR_ISSUE = "LINEAR_GET_LINEAR_ISSUE"
        UPDATE_ISSUE = "LINEAR_UPDATE_ISSUE"
        GET_LINEAR_PROJECT = "LINEAR_GET_LINEAR_PROJECT"
        LIST_ISSUE_DRAFTS = "LINEAR_LIST_ISSUE_DRAFTS"
        CREATE_COMMENT_REACTION = "LINEAR_CREATE_COMMENT_REACTION"
        CREATE_LINEAR_LABEL = "LINEAR_CREATE_LINEAR_LABEL"
        GET_ALL_LINEAR_TEAMS = "LINEAR_GET_ALL_LINEAR_TEAMS"
        GET_CURRENT_USER = "LINEAR_GET_CURRENT_USER"
        LIST_LINEAR_CYCLES = "LINEAR_LIST_LINEAR_CYCLES"
        CREATE_LINEAR_ISSUE_DETAILS = "LINEAR_CREATE_LINEAR_ISSUE_DETAILS"
        CREATE_LINEAR_ISSUE = "LINEAR_CREATE_LINEAR_ISSUE"
        MANAGE_DRAFT = "LINEAR_MANAGE_DRAFT"
        GET_ATTACHMENTS = "LINEAR_GET_ATTACHMENTS"
        REMOVE_ISSUE_LABEL = "LINEAR_REMOVE_ISSUE_LABEL"
        CREATE_LINEAR_COMMENT = "LINEAR_CREATE_LINEAR_COMMENT"
        LIST_LINEAR_LABELS = "LINEAR_LIST_LINEAR_LABELS"
        UPDATE_LINEAR_COMMENT = "LINEAR_UPDATE_LINEAR_COMMENT"
        LIST_LINEAR_ISSUES = "LINEAR_LIST_LINEAR_ISSUES"
        DELETE_LINEAR_ISSUE = "LINEAR_DELETE_LINEAR_ISSUE"
        RUN_QUERY_OR_MUTATION = "LINEAR_RUN_QUERY_OR_MUTATION"
        UPDATE_LINEAR_PROJECT = "LINEAR_UPDATE_LINEAR_PROJECT"

    class triggers:
        COMMENT_EVENT_TRIGGER = {
          "config": {
            "properties": {
              "team_id": {
                "description": "ID of the team to filter issues by",
                "title": "Team Id",
                "type": "string"
              }
            },
            "required": ["team_id"],
            "title": "LinearTriggerConfig",
            "type": "object"
          },
          "description": "Triggered when a comment is received.",
          "instructions": "",
          "name": "Comment Received Trigger",
          "payload": {
            "properties": {
              "action": {
                "description": "Action that triggered the webhook",
                "title": "Action",
                "type": "string"
              },
              "data": {
                "additionalProperties": True,
                "description": "Data of the issue",
                "title": "Data",
                "type": "object"
              },
              "type": {
                "description": "Type of the issue",
                "title": "Type",
                "type": "string"
              },
              "url": {
                "description": "URL of the issue",
                "title": "Url",
                "type": "string"
              }
            },
            "required": ["action", "type", "url", "data"],
            "title": "LinearPayloadSchema",
            "type": "object"
          },
          "slug": "LINEAR_COMMENT_EVENT_TRIGGER",
          "type": "webhook"
        }
        ISSUE_CREATED_TRIGGER = {
          "config": {
            "properties": {
              "team_id": {
                "description": "ID of the team to filter issues by",
                "title": "Team Id",
                "type": "string"
              }
            },
            "required": ["team_id"],
            "title": "LinearTriggerConfig",
            "type": "object"
          },
          "description": "Triggered when a new issue is created.",
          "instructions": "",
          "name": "Issue Created Trigger",
          "payload": {
            "properties": {
              "action": {
                "description": "Action that triggered the webhook",
                "title": "Action",
                "type": "string"
              },
              "data": {
                "additionalProperties": True,
                "description": "Data of the issue",
                "title": "Data",
                "type": "object"
              },
              "type": {
                "description": "Type of the issue",
                "title": "Type",
                "type": "string"
              },
              "url": {
                "description": "URL of the issue",
                "title": "Url",
                "type": "string"
              }
            },
            "required": ["action", "type", "url", "data"],
            "title": "LinearPayloadSchema",
            "type": "object"
          },
          "slug": "LINEAR_ISSUE_CREATED_TRIGGER",
          "type": "webhook"
        }
        ISSUE_UPDATED_TRIGGER = {
          "config": {
            "properties": {
              "team_id": {
                "description": "ID of the team to filter issues by",
                "title": "Team Id",
                "type": "string"
              }
            },
            "required": ["team_id"],
            "title": "LinearTriggerConfig",
            "type": "object"
          },
          "description": "Triggered when an issue is updated. For example labels are changed, issue status is changed, etc.",
          "instructions": "",
          "name": "Issue Updated Trigger",
          "payload": {
            "properties": {
              "action": {
                "description": "Action that triggered the webhook",
                "title": "Action",
                "type": "string"
              },
              "data": {
                "additionalProperties": True,
                "description": "Data of the issue",
                "title": "Data",
                "type": "object"
              },
              "type": {
                "description": "Type of the issue",
                "title": "Type",
                "type": "string"
              },
              "url": {
                "description": "URL of the issue",
                "title": "Url",
                "type": "string"
              }
            },
            "required": ["action", "type", "url", "data"],
            "title": "LinearPayloadSchema",
            "type": "object"
          },
          "slug": "LINEAR_ISSUE_UPDATED_TRIGGER",
          "type": "webhook"
        }
