# Auto-generated by Composio CLI. Do not modify manually..

class LINGUAPOP:
    """Map of Composio's LINGUAPOP toolkit."""

    slug: str = "linguapop"

    class tools:
        FETCH_AVAILABLE_LANGUAGES = "LINGUAPOP_FETCH_AVAILABLE_LANGUAGES"

    class triggers:
        pass
