# Auto-generated by Composio CLI. Do not modify manually..

class LOGO_DEV:
    """Map of Composio's LOGO_DEV toolkit."""

    slug: str = "logo_dev"

    class tools:
        GET_LOGO_IMAGE = "LOGO_DEV_GET_LOGO_IMAGE"
        SEARCH_BRAND = "LOGO_DEV_SEARCH_BRAND"

    class triggers:
        pass
