# Auto-generated by Composio CLI. Do not modify manually..

class MAILSOFTLY:
    """Map of Composio's MAILSOFTLY toolkit."""

    slug: str = "mailsoftly"

    class tools:
        AUTHENTICATE_FIRM = "MAILSOFTLY_AUTHENTICATE_FIRM"

    class triggers:
        pass
