# Auto-generated by Composio CLI. Do not modify manually..

class MAILBOXLAYER:
    """Map of Composio's MAILBOXLAYER toolkit."""

    slug: str = "mailboxlayer"

    class tools:
        CHECK_EMAIL = "MAILBOXLAYER_CHECK_EMAIL"

    class triggers:
        pass
