# Auto-generated by Composio CLI. Do not modify manually..

class MAPULUS:
    """Map of Composio's MAPULUS toolkit."""

    slug: str = "mapulus"

    class tools:
        LIST_MAPS = "MAPULUS_LIST_MAPS"
        GET_MAP_DETAILS = "MAPULUS_GET_MAP_DETAILS"
        FIND_LOCATION_WITH_EXTERNAL_ID = "MAPULUS_FIND_LOCATION_WITH_EXTERNAL_ID"
        LIST_LOCATIONS = "MAPULUS_LIST_LOCATIONS"

    class triggers:
        pass
