# Auto-generated by Composio CLI. Do not modify manually..

class MEM:
    """Map of Composio's MEM toolkit."""

    slug: str = "mem"

    class tools:
        READ_NOTE = "MEM_READ_NOTE"
        DELETE_NOTE = "MEM_DELETE_NOTE"
        DELETE_COLLECTION = "MEM_DELETE_COLLECTION"
        CREATE_NOTE = "MEM_CREATE_NOTE"
        CREATE_COLLECTION = "MEM_CREATE_COLLECTION"

    class triggers:
        pass
