# Auto-generated by Composio CLI. Do not modify manually..

class MEMBERSTACK:
    """Map of Composio's MEMBERSTACK toolkit."""

    slug: str = "memberstack"

    class tools:
        DELETE_MEMBER = "MEMBERSTACK_DELETE_MEMBER"
        UPDATE_MEMBER = "MEMBERSTACK_UPDATE_MEMBER"
        REMOVE_FREE_PLAN = "MEMBERSTACK_REMOVE_FREE_PLAN"
        LIST_MEMBERS = "MEMBERSTACK_LIST_MEMBERS"
        LIST_PLANS = "MEMBERSTACK_LIST_PLANS"
        CREATE_MEMBER = "MEMBERSTACK_CREATE_MEMBER"
        GET_MEMBER = "MEMBERSTACK_GET_MEMBER"

    class triggers:
        pass
