# Auto-generated by Composio CLI. Do not modify manually..

class MOONCLERK:
    """Map of Composio's MOONCLERK toolkit."""

    slug: str = "moonclerk"

    class tools:
        LIST_DISCOUNTS = "MOONCLERK_LIST_DISCOUNTS"
        LIST_SUBSCRIPTIONS = "MOONCLERK_LIST_SUBSCRIPTIONS"
        LIST_FORMS = "MOONCLERK_LIST_FORMS"
        LIST_PAYMENTS = "MOONCLERK_LIST_PAYMENTS"
        LIST_CUSTOMERS = "MOONCLERK_LIST_CUSTOMERS"

    class triggers:
        pass
