# Auto-generated by Composio CLI. Do not modify manually..

class NEWS_API:
    """Map of Composio's NEWS_API toolkit."""

    slug: str = "news_api"

    class tools:
        GET_EVERYTHING = "NEWS_API_GET_EVERYTHING"
        GET_SOURCES = "NEWS_API_GET_SOURCES"
        GET_TOP_HEADLINES = "NEWS_API_GET_TOP_HEADLINES"

    class triggers:
        pass
