# Auto-generated by Composio CLI. Do not modify manually..

class NGROK:
    """Map of Composio's NGROK toolkit."""

    slug: str = "ngrok"

    class tools:
        LIST_IP_POLICY_RULES = "NGROK_LIST_IP_POLICY_RULES"
        DELETE_API_KEY = "NGROK_DELETE_API_KEY"
        LIST_HTTPS_EDGES = "NGROK_LIST_HTTPS_EDGES"
        LIST_IP_RESTRICTIONS = "NGROK_LIST_IP_RESTRICTIONS"
        LIST_TUNNELS = "NGROK_LIST_TUNNELS"
        LIST_ENDPOINTS = "NGROK_LIST_ENDPOINTS"
        CREATE_API_KEY = "NGROK_CREATE_API_KEY"
        LIST_API_KEYS = "NGROK_LIST_API_KEYS"
        GET_IP_RESTRICTIONS = "NGROK_GET_IP_RESTRICTIONS"

    class triggers:
        pass
