# Auto-generated by Composio CLI. Do not modify manually..

class ONE_DRIVE:
    """Map of Composio's ONE_DRIVE toolkit."""

    slug: str = "one_drive"

    class tools:
        LIST_ROOT_DRIVE_CHANGES = "ONE_DRIVE_LIST_ROOT_DRIVE_CHANGES"
        MOVE_ITEM = "ONE_DRIVE_MOVE_ITEM"
        ONEDRIVE_FIND_FOLDER = "ONE_DRIVE_ONEDRIVE_FIND_FOLDER"
        UPDATE_FILE_CONTENT = "ONE_DRIVE_UPDATE_FILE_CONTENT"
        LIST_DRIVE_ITEM_ACTIVITIES = "ONE_DRIVE_LIST_DRIVE_ITEM_ACTIVITIES"
        LIST_SITE_DRIVE_ITEMS_DELTA = "ONE_DRIVE_LIST_SITE_DRIVE_ITEMS_DELTA"
        LIST_SUBSCRIPTIONS = "ONE_DRIVE_LIST_SUBSCRIPTIONS"
        GET_SHAREPOINT_LIST_ITEMS = "ONE_DRIVE_GET_SHAREPOINT_LIST_ITEMS"
        GET_ITEM_VERSIONS = "ONE_DRIVE_GET_ITEM_VERSIONS"
        GET_DRIVE_ITEM_BY_SHARING_URL = "ONE_DRIVE_GET_DRIVE_ITEM_BY_SHARING_URL"
        LIST_SITE_LISTS = "ONE_DRIVE_LIST_SITE_LISTS"
        GET_RECENT_ITEMS = "ONE_DRIVE_GET_RECENT_ITEMS"
        GET_SHARED_ITEMS = "ONE_DRIVE_GET_SHARED_ITEMS"
        ONEDRIVE_CREATE_FOLDER = "ONE_DRIVE_ONEDRIVE_CREATE_FOLDER"
        LIST_DRIVES = "ONE_DRIVE_LIST_DRIVES"
        ONEDRIVE_CREATE_TEXT_FILE = "ONE_DRIVE_ONEDRIVE_CREATE_TEXT_FILE"
        COPY_ITEM = "ONE_DRIVE_COPY_ITEM"
        GET_DRIVE = "ONE_DRIVE_GET_DRIVE"
        DELETE_ITEM = "ONE_DRIVE_DELETE_ITEM"
        UPDATE_DRIVE_ITEM_METADATA = "ONE_DRIVE_UPDATE_DRIVE_ITEM_METADATA"
        GET_SITE_PAGE_CONTENT = "ONE_DRIVE_GET_SITE_PAGE_CONTENT"
        ONEDRIVE_UPLOAD_FILE = "ONE_DRIVE_ONEDRIVE_UPLOAD_FILE"
        GET_ITEM = "ONE_DRIVE_GET_ITEM"
        GET_QUOTA = "ONE_DRIVE_GET_QUOTA"
        SEARCH_ITEMS = "ONE_DRIVE_SEARCH_ITEMS"
        GET_ITEM_PERMISSIONS = "ONE_DRIVE_GET_ITEM_PERMISSIONS"
        ONEDRIVE_LIST_ITEMS = "ONE_DRIVE_ONEDRIVE_LIST_ITEMS"
        GET_SITE_DETAILS = "ONE_DRIVE_GET_SITE_DETAILS"
        LIST_SHAREPOINT_LIST_ITEMS_DELTA = "ONE_DRIVE_LIST_SHAREPOINT_LIST_ITEMS_DELTA"
        LIST_SITE_SUBSITES = "ONE_DRIVE_LIST_SITE_SUBSITES"
        ONEDRIVE_FIND_FILE = "ONE_DRIVE_ONEDRIVE_FIND_FILE"
        LIST_SITE_COLUMNS = "ONE_DRIVE_LIST_SITE_COLUMNS"
        LIST_FOLDER_CHILDREN = "ONE_DRIVE_LIST_FOLDER_CHILDREN"
        PREVIEW_DRIVE_ITEM = "ONE_DRIVE_PREVIEW_DRIVE_ITEM"
        CREATE_LINK = "ONE_DRIVE_CREATE_LINK"
        DOWNLOAD_FILE = "ONE_DRIVE_DOWNLOAD_FILE"
        GET_ITEM_THUMBNAILS = "ONE_DRIVE_GET_ITEM_THUMBNAILS"
        INVITE_USER_TO_DRIVE_ITEM = "ONE_DRIVE_INVITE_USER_TO_DRIVE_ITEM"

    class triggers:
        BASE_TRIGGER = {
          "config": {
            "properties": {
              "drive_path": {
                "default": "/",
                "description": "The path in OneDrive to monitor for changes. Default is root.",
                "title": "Drive Path",
                "type": "string"
              },
              "include_deleted": {
                "default": True,
                "description": "Whether to include deleted items in the changes",
                "title": "Include Deleted",
                "type": "boolean"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "OneDriveChangeConfig",
            "type": "object"
          },
          "description": "Base trigger for OneDrive changes using Gmail-style state management.\n    Subclasses override `filter_changes(...)` to extract only the relevant items.",
          "instructions": "",
          "name": "Onedrivebasetrigger",
          "payload": {
            "$defs": {
              "OneDriveItemSchema": {
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "OneDriveItemSchema",
                "type": "object"
              }
            },
            "description": "Payload model for OneDrive change events.",
            "properties": {
              "event_type": {
                "description": "Type of change event (created, modified, deleted)",
                "title": "Event Type",
                "type": "string"
              },
              "item": {
                "additionalProperties": False,
                "description": "The OneDrive item that changed",
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "Item",
                "type": "object"
              }
            },
            "required": ["item", "event_type"],
            "title": "OneDriveChangePayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_BASE_TRIGGER",
          "type": "poll"
        }
        FILE_CREATED_TRIGGER = {
          "config": {
            "properties": {
              "drive_path": {
                "default": "/",
                "description": "The path in OneDrive to monitor for changes. Default is root.",
                "title": "Drive Path",
                "type": "string"
              },
              "include_deleted": {
                "default": True,
                "description": "Whether to include deleted items in the changes",
                "title": "Include Deleted",
                "type": "boolean"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "OneDriveChangeConfig",
            "type": "object"
          },
          "description": "Triggers when a new file is created in OneDrive.\n    Uses Gmail-style state management for reliable duplicate prevention.",
          "instructions": "\n    **Instructions for Setting Up the Trigger:**\n\n    - Ensure that OneDrive API access is configured for your account.\n    - This trigger will monitor for newly created files in your OneDrive.\n    - Use `include_folders` to also detect folder creation events.\n    - The trigger uses timestamp filtering and duplicate prevention like Gmail triggers.\n    ",
          "name": "OneDrive File Created Trigger",
          "payload": {
            "$defs": {
              "OneDriveItemSchema": {
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "OneDriveItemSchema",
                "type": "object"
              }
            },
            "description": "Payload model for OneDrive change events.",
            "properties": {
              "event_type": {
                "description": "Type of change event (created, modified, deleted)",
                "title": "Event Type",
                "type": "string"
              },
              "item": {
                "additionalProperties": False,
                "description": "The OneDrive item that changed",
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "Item",
                "type": "object"
              }
            },
            "required": ["item", "event_type"],
            "title": "OneDriveChangePayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_FILE_CREATED_TRIGGER",
          "type": "poll"
        }
        FILE_UPDATED = {
          "config": {
            "description": "Configuration for OneDrive File Updated trigger.",
            "properties": {
              "drive_path": {
                "default": "/",
                "description": "The path in OneDrive to monitor for file updates. Use '/' for root or a subpath like 'Documents/Reports'.",
                "title": "Drive Path",
                "type": "string"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "FileUpdatedConfig",
            "type": "object"
          },
          "description": "Trigger that fires when a OneDrive file's content or metadata changes.\n    Returns file ID, last modified time, and modifier info.",
          "instructions": "Monitors your OneDrive for file updates in the specified path. Configure 'drive_path' to a folder path (e.g., '/','Documents', 'Documents/Reports'). On the first run, the trigger initializes state and returns no events.",
          "name": "File Updated",
          "payload": {
            "description": "Payload returned when a file is updated.",
            "properties": {
              "file_id": {
                "description": "The ID of the updated file",
                "title": "File Id",
                "type": "string"
              },
              "last_modified_time": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The ISO8601 timestamp when the file was last modified",
                "title": "Last Modified Time"
              },
              "modified_by": {
                "anyOf": [{
                    "additionalProperties": True,
                    "type": "object"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Information about who last modified the file",
                "title": "Modified By"
              }
            },
            "required": ["file_id"],
            "title": "FileUpdatedPayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_FILE_UPDATED",
          "type": "poll"
        }
        FOLDER_CREATED_TRIGGER = {
          "config": {
            "properties": {
              "drive_path": {
                "default": "/",
                "description": "The path in OneDrive to monitor for changes. Default is root.",
                "title": "Drive Path",
                "type": "string"
              },
              "include_deleted": {
                "default": True,
                "description": "Whether to include deleted items in the changes",
                "title": "Include Deleted",
                "type": "boolean"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "OneDriveChangeConfig",
            "type": "object"
          },
          "description": "Triggers when a new folder is created in OneDrive.\n    Uses Gmail-style state management for reliable duplicate prevention.",
          "instructions": "",
          "name": "OneDrive Folder Created Trigger",
          "payload": {
            "$defs": {
              "OneDriveItemSchema": {
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "OneDriveItemSchema",
                "type": "object"
              }
            },
            "description": "Payload model for OneDrive change events.",
            "properties": {
              "event_type": {
                "description": "Type of change event (created, modified, deleted)",
                "title": "Event Type",
                "type": "string"
              },
              "item": {
                "additionalProperties": False,
                "description": "The OneDrive item that changed",
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "Item",
                "type": "object"
              }
            },
            "required": ["item", "event_type"],
            "title": "OneDriveChangePayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_FOLDER_CREATED_TRIGGER",
          "type": "poll"
        }
        ITEM_DELETED_TRIGGER = {
          "config": {
            "properties": {
              "drive_path": {
                "default": "/",
                "description": "The path in OneDrive to monitor for changes. Default is root.",
                "title": "Drive Path",
                "type": "string"
              },
              "include_deleted": {
                "default": True,
                "description": "Whether to include deleted items in the changes",
                "title": "Include Deleted",
                "type": "boolean"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "OneDriveChangeConfig",
            "type": "object"
          },
          "description": "Triggers when a file or folder is deleted in OneDrive.\n    Uses Gmail-style state management for reliable duplicate prevention.",
          "instructions": "",
          "name": "OneDrive Item Deleted Trigger",
          "payload": {
            "$defs": {
              "OneDriveItemSchema": {
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "OneDriveItemSchema",
                "type": "object"
              }
            },
            "description": "Payload model for OneDrive change events.",
            "properties": {
              "event_type": {
                "description": "Type of change event (created, modified, deleted)",
                "title": "Event Type",
                "type": "string"
              },
              "item": {
                "additionalProperties": False,
                "description": "The OneDrive item that changed",
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "Item",
                "type": "object"
              }
            },
            "required": ["item", "event_type"],
            "title": "OneDriveChangePayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_ITEM_DELETED_TRIGGER",
          "type": "poll"
        }
        ITEM_MOVED_OR_RENAMED_TRIGGER = {
          "config": {
            "description": "Configuration for OneDrive Item Moved or Renamed trigger.",
            "properties": {
              "drive_path": {
                "default": "/",
                "description": "The path in OneDrive to monitor for moves/renames. Default is root.",
                "title": "Drive Path",
                "type": "string"
              },
              "include_files": {
                "default": True,
                "description": "Whether to include files in move/rename detection.",
                "title": "Include Files",
                "type": "boolean"
              },
              "include_folders": {
                "default": True,
                "description": "Whether to include folders in move/rename detection.",
                "title": "Include Folders",
                "type": "boolean"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "ItemMovedRenamedConfig",
            "type": "object"
          },
          "description": "Triggers when a file or folder is moved to a different path or renamed in OneDrive.\n    Includes both old and new path/name data in the payload.",
          "instructions": "\n    This trigger monitors OneDrive for items that are moved to a different folder path or renamed.\n\n    - Configure drive_path to scope monitoring to a specific folder (default is root \"/\").\n    - Choose whether to include files and/or folders via include_files/include_folders.\n    - The payload contains old and new name/path values for precise change handling.\n    ",
          "name": "Item Moved or Renamed",
          "payload": {
            "properties": {
              "event_type": {
                "description": "Event type: renamed, moved, or moved_and_renamed",
                "title": "Event Type",
                "type": "string"
              },
              "item_id": {
                "description": "The unique identifier of the item",
                "title": "Item Id",
                "type": "string"
              },
              "item_type": {
                "description": "Type of the item: file or folder",
                "title": "Item Type",
                "type": "string"
              },
              "new_name": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Current name of the item",
                "title": "New Name"
              },
              "new_path": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Current parentReference.path of the item",
                "title": "New Path"
              },
              "old_name": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Previous name of the item",
                "title": "Old Name"
              },
              "old_path": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Previous parentReference.path of the item",
                "title": "Old Path"
              },
              "payload": {
                "additionalProperties": True,
                "description": "Full OneDrive payload",
                "title": "Payload",
                "type": "object"
              },
              "web_url": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Web URL of the item",
                "title": "Web Url"
              }
            },
            "required": ["item_id", "item_type", "event_type"],
            "title": "ItemMovedRenamedPayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_ITEM_MOVED_OR_RENAMED_TRIGGER",
          "type": "poll"
        }
        ITEM_UPDATED_TRIGGER = {
          "config": {
            "properties": {
              "drive_path": {
                "default": "/",
                "description": "The path in OneDrive to monitor for changes. Default is root.",
                "title": "Drive Path",
                "type": "string"
              },
              "include_deleted": {
                "default": True,
                "description": "Whether to include deleted items in the changes",
                "title": "Include Deleted",
                "type": "boolean"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "OneDriveChangeConfig",
            "type": "object"
          },
          "description": "Triggers when an existing file or folder is modified in OneDrive.\n    Uses Gmail-style state management and only detects actual modifications, not new creations.",
          "instructions": "",
          "name": "OneDrive Item Updated Trigger",
          "payload": {
            "$defs": {
              "OneDriveItemSchema": {
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "OneDriveItemSchema",
                "type": "object"
              }
            },
            "description": "Payload model for OneDrive change events.",
            "properties": {
              "event_type": {
                "description": "Type of change event (created, modified, deleted)",
                "title": "Event Type",
                "type": "string"
              },
              "item": {
                "additionalProperties": False,
                "description": "The OneDrive item that changed",
                "properties": {
                  "created_time": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Creation timestamp",
                    "title": "Created Time"
                  },
                  "deleted": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": False,
                    "description": "Whether the item was deleted",
                    "title": "Deleted"
                  },
                  "item_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The ID of the item",
                    "title": "Item Id"
                  },
                  "last_modified": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Last modified timestamp",
                    "title": "Last Modified"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the item",
                    "title": "Name"
                  },
                  "payload": {
                    "additionalProperties": True,
                    "default": {},
                    "description": "The full item payload from OneDrive",
                    "title": "Payload",
                    "type": "object"
                  },
                  "size": {
                    "anyOf": [{
                        "type": "integer"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Size of the item in bytes",
                    "title": "Size"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The type of the item (file or folder)",
                    "title": "Type"
                  },
                  "web_url": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The web URL of the item",
                    "title": "Web Url"
                  }
                },
                "title": "Item",
                "type": "object"
              }
            },
            "required": ["item", "event_type"],
            "title": "OneDriveChangePayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_ITEM_UPDATED_TRIGGER",
          "type": "poll"
        }
        NEW_VERSION_CREATED_TRIGGER = {
          "config": {
            "description": "Configuration for monitoring versions of a specific OneDrive file.",
            "properties": {
              "drive_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The unique identifier of the drive. Optional; defaults to /me if not provided.",
                "title": "Drive Id"
              },
              "group_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The unique identifier of the group. Mutually exclusive with other scope IDs.",
                "title": "Group Id"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "item_id": {
                "description": "The unique identifier of the OneDrive file to monitor.",
                "title": "Item Id",
                "type": "string"
              },
              "site_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The unique identifier of the site. Mutually exclusive with other scope IDs.",
                "title": "Site Id"
              },
              "user_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The unique identifier of the user. Mutually exclusive with other scope IDs.",
                "title": "User Id"
              }
            },
            "required": ["item_id"],
            "title": "OneDriveNewVersionConfig",
            "type": "object"
          },
          "description": "Trigger that fires when a new version of a specified OneDrive file is created.",
          "instructions": "Monitors a specific OneDrive file for new versions. Provide the file's item_id (and optionally drive/group/site/user scope). On the first run (last_synced_at == 0), no events are emitted; the state initializes.",
          "name": "New Version Created",
          "payload": {
            "properties": {
              "item_id": {
                "description": "The ID of the OneDrive file.",
                "title": "Item Id",
                "type": "string"
              },
              "modified_time": {
                "description": "The ISO 8601 timestamp of when this version was last modified.",
                "title": "Modified Time",
                "type": "string"
              },
              "version_number": {
                "description": "The version number/ID as returned by Microsoft Graph (e.g., '2.0').",
                "title": "Version Number",
                "type": "string"
              }
            },
            "required": ["item_id", "version_number", "modified_time"],
            "title": "OneDriveNewVersionPayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_NEW_VERSION_CREATED_TRIGGER",
          "type": "poll"
        }
        SHARING_PERMISSION_CHANGED_TRIGGER = {
          "config": {
            "properties": {
              "drive_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Drive ID if monitoring an item outside the signed-in user's default drive.",
                "title": "Drive Id"
              },
              "group_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Group ID if the item resides in a group's drive.",
                "title": "Group Id"
              },
              "include_role_updates": {
                "default": False,
                "description": "If true, the trigger will also fire when roles are changed on an existing permission (e.g., from read to write).",
                "title": "Include Role Updates",
                "type": "boolean"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "item_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The unique identifier of the OneDrive item to monitor for permission changes.",
                "title": "Item Id"
              },
              "item_path": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Alternative to item_id. Path relative to drive root in the form ':/path/to/item:/'",
                "examples": [":/Documents/Report.docx:/"],
                "title": "Item Path"
              },
              "site_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "SharePoint Site ID if the item resides in a site's drive.",
                "title": "Site Id"
              },
              "user_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "User ID if the item resides in a specific user's drive.",
                "title": "User Id"
              }
            },
            "title": "PermissionChangeConfig",
            "type": "object"
          },
          "description": "Sharing Permission Added or Removed",
          "instructions": "Monitor a specific OneDrive item for sharing permission changes. Provide the item_id (or item_path with drive context). On first run, the trigger initializes state and emits no events. On subsequent polls, it detects permissions added or removed. Optionally, enable include_role_updates to also detect role changes.",
          "name": "Sharing Permission Added or Removed",
          "payload": {
            "$defs": {
              "PermissionIdentity": {
                "properties": {
                  "displayName": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Display name of the identity, if available",
                    "title": "Displayname"
                  },
                  "id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The unique identifier of the identity",
                    "title": "Id"
                  },
                  "loginName": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Login name (primarily for SharePoint site users)",
                    "title": "Loginname"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Type of grantee (user, group, siteUser, application, device)",
                    "title": "Type"
                  }
                },
                "title": "PermissionIdentity",
                "type": "object"
              }
            },
            "properties": {
              "affected_identities": {
                "description": "Users/groups/apps affected by this change",
                "items": {
                  "properties": {
                    "displayName": {
                      "anyOf": [{
                          "type": "string"
                        }, {
                          "type": "null"
                        }],
                      "default": None,
                      "description": "Display name of the identity, if available",
                      "title": "Display Name"
                    },
                    "id": {
                      "anyOf": [{
                          "type": "string"
                        }, {
                          "type": "null"
                        }],
                      "default": None,
                      "description": "The unique identifier of the identity",
                      "title": "Id"
                    },
                    "loginName": {
                      "anyOf": [{
                          "type": "string"
                        }, {
                          "type": "null"
                        }],
                      "default": None,
                      "description": "Login name (primarily for SharePoint site users)",
                      "title": "Login Name"
                    },
                    "type": {
                      "anyOf": [{
                          "type": "string"
                        }, {
                          "type": "null"
                        }],
                      "default": None,
                      "description": "Type of grantee (user, group, siteUser, application, device)",
                      "title": "Type"
                    }
                  },
                  "title": "PermissionIdentity",
                  "type": "object"
                },
                "title": "Affected Identities",
                "type": "array"
              },
              "event_type": {
                "description": "permission_added | permission_removed | permission_updated",
                "title": "Event Type",
                "type": "string"
              },
              "item_id": {
                "description": "The OneDrive item ID whose sharing changed",
                "title": "Item Id",
                "type": "string"
              },
              "link": {
                "anyOf": [{
                    "additionalProperties": True,
                    "type": "object"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Sharing link details, if any",
                "title": "Link"
              },
              "permission_id": {
                "description": "The permission ID involved in the change",
                "title": "Permission Id",
                "type": "string"
              },
              "previous_roles": {
                "anyOf": [{
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The roles before the change (for updated)",
                "title": "Previous Roles"
              },
              "roles": {
                "anyOf": [{
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "The roles after the change (for added/updated)",
                "title": "Roles"
              }
            },
            "required": ["item_id", "permission_id", "event_type"],
            "title": "PermissionChangePayload",
            "type": "object"
          },
          "slug": "ONE_DRIVE_SHARING_PERMISSION_CHANGED_TRIGGER",
          "type": "poll"
        }
