# Auto-generated by Composio CLI. Do not modify manually..

class PASSCREATOR:
    """Map of Composio's PASSCREATOR toolkit."""

    slug: str = "passcreator"

    class tools:
        LIST_PASSES = "PASSCREATOR_LIST_PASSES"
        CHECK_PASS_EXISTENCE = "PASSCREATOR_CHECK_PASS_EXISTENCE"
        LIST_PASS_TEMPLATES = "PASSCREATOR_LIST_PASS_TEMPLATES"

    class triggers:
        pass
