# Auto-generated by Composio CLI. Do not modify manually..

class PDF4ME:
    """Map of Composio's PDF4ME toolkit."""

    slug: str = "pdf4me"

    class tools:
        CONVERT_TO_PDF = "PDF4ME_CONVERT_TO_PDF"

    class triggers:
        pass
