# Auto-generated by Composio CLI. Do not modify manually..

class PDF_API_IO:
    """Map of Composio's PDF_API_IO toolkit."""

    slug: str = "pdf_api_io"

    class tools:
        LIST_TEMPLATES = "PDF_API_IO_LIST_TEMPLATES"

    class triggers:
        pass
