# Auto-generated by Composio CLI. Do not modify manually..

class PDFLESS:
    """Map of Composio's PDFLESS toolkit."""

    slug: str = "pdfless"

    class tools:
        LIST_DOCUMENT_TEMPLATES = "PDFLESS_LIST_DOCUMENT_TEMPLATES"

    class triggers:
        pass
