# Auto-generated by Composio CLI. Do not modify manually..

class PLATERECOGNIZER:
    """Map of Composio's PLATERECOGNIZER toolkit."""

    slug: str = "platerecognizer"

    class tools:
        SNAPSHOT_GET_STATISTICS = "PLATERECOGNIZER_SNAPSHOT_GET_STATISTICS"

    class triggers:
        pass
