# Auto-generated by Composio CLI. Do not modify manually..

class PLISIO:
    """Map of Composio's PLISIO toolkit."""

    slug: str = "plisio"

    class tools:
        GET_TRANSACTIONS = "PLISIO_GET_TRANSACTIONS"
        GET_WITHDRAWALS = "PLISIO_GET_WITHDRAWALS"
        GET_OPERATIONS = "PLISIO_GET_OPERATIONS"
        GET_FEE_PLANS = "PLISIO_GET_FEE_PLANS"
        GET_BALANCE = "PLISIO_GET_BALANCE"
        GET_BALANCES = "PLISIO_GET_BALANCES"

    class triggers:
        pass
