# Auto-generated by Composio CLI. Do not modify manually..

class PROJECT_BUBBLE:
    """Map of Composio's PROJECT_BUBBLE toolkit."""

    slug: str = "project_bubble"

    class tools:
        DATA_API_GET_OBJECTS = "PROJECT_BUBBLE_DATA_API_GET_OBJECTS"
        DATA_API_GET_DATA_TYPE_FIELDS = "PROJECT_BUBBLE_DATA_API_GET_DATA_TYPE_FIELDS"
        DATA_API_GET_RECORD = "PROJECT_BUBBLE_DATA_API_GET_RECORD"

    class triggers:
        pass
