# Auto-generated by Composio CLI. Do not modify manually..

class PROOFLY:
    """Map of Composio's PROOFLY toolkit."""

    slug: str = "proofly"

    class tools:
        GET_CAMPAIGNS = "PROOFLY_GET_CAMPAIGNS"
        GET_ACTIVITY_LOGS = "PROOFLY_GET_ACTIVITY_LOGS"
        GET_USER = "PROOFLY_GET_USER"

    class triggers:
        pass
