# Auto-generated by Composio CLI. Do not modify manually..

class RAFFLYS:
    """Map of Composio's RAFFLYS toolkit."""

    slug: str = "rafflys"

    class tools:
        LIST_PROMOTIONS = "RAFFLYS_LIST_PROMOTIONS"
        GET_CURRENT_USER = "RAFFLYS_GET_CURRENT_USER"

    class triggers:
        pass
