# Auto-generated by Composio CLI. Do not modify manually..

class RE_AMAZE:
    """Map of Composio's RE_AMAZE toolkit."""

    slug: str = "re_amaze"

    class tools:
        GET_REPORTS_TAGS = "RE_AMAZE_GET_REPORTS_TAGS"
        GET_RESPONSE_TEMPLATES = "RE_AMAZE_GET_RESPONSE_TEMPLATES"

    class triggers:
        pass
