# Auto-generated by Composio CLI. Do not modify manually..

class REFINER:
    """Map of Composio's REFINER toolkit."""

    slug: str = "refiner"

    class tools:
        GET_RESPONSES = "REFINER_GET_RESPONSES"
        TRACK_EVENT = "REFINER_TRACK_EVENT"
        GET_FORMS = "REFINER_GET_FORMS"
        GET_SEGMENTS = "REFINER_GET_SEGMENTS"
        GET_CONTACT = "REFINER_GET_CONTACT"
        UPDATE_CONTACT = "REFINER_UPDATE_CONTACT"
        GET_ACCOUNT_INFO = "REFINER_GET_ACCOUNT_INFO"
        GET_CONTACTS = "REFINER_GET_CONTACTS"
        DELETE_CONTACT = "REFINER_DELETE_CONTACT"
        GET_REPORTING = "REFINER_GET_REPORTING"

    class triggers:
        pass
