# Auto-generated by Composio CLI. Do not modify manually..

class ROOTLY:
    """Map of Composio's ROOTLY toolkit."""

    slug: str = "rootly"

    class tools:
        LIST_ACTION_ITEMS = "ROOTLY_LIST_ACTION_ITEMS"
        DELETE_ACTION_ITEM = "ROOTLY_DELETE_ACTION_ITEM"
        GET_ACTION_ITEM = "ROOTLY_GET_ACTION_ITEM"

    class triggers:
        pass
