# Auto-generated by Composio CLI. Do not modify manually..

class ROUTE4ME:
    """Map of Composio's ROUTE4ME toolkit."""

    slug: str = "route4me"

    class tools:
        SET_DESTINATION_STATUS = "ROUTE4ME_SET_DESTINATION_STATUS"
        GET_VEHICLE = "ROUTE4ME_GET_VEHICLE"

    class triggers:
        pass
