# Auto-generated by Composio CLI. Do not modify manually..

class SALESFORCE:
    """Map of Composio's SALESFORCE toolkit."""

    slug: str = "salesforce"

    class tools:
        LOG_CALL = "SALESFORCE_LOG_CALL"
        SEARCH_CONTACTS = "SALESFORCE_SEARCH_CONTACTS"
        SERVICE_CLOUD_RESYNC_CHASITOR_STATE = "SALESFORCE_SERVICE_CLOUD_RESYNC_CHASITOR_STATE"
        SERVICE_CLOUD_GET_CASE_RECORD = "SALESFORCE_SERVICE_CLOUD_GET_CASE_RECORD"
        SERVICE_CLOUD_GENERATE_SIGNED_JWT_ASSERTION = "SALESFORCE_SERVICE_CLOUD_GENERATE_SIGNED_JWT_ASSERTION"
        SERVICE_CLOUD_SEND_CUSTOM_EVENT = "SALESFORCE_SERVICE_CLOUD_SEND_CUSTOM_EVENT"
        SERVICE_CLOUD_QUERY_SOQL = "SALESFORCE_SERVICE_CLOUD_QUERY_SOQL"
        SERVICE_CLOUD_GET_LIVE_AGENT_API_VERSION = "SALESFORCE_SERVICE_CLOUD_GET_LIVE_AGENT_API_VERSION"
        SERVICE_CLOUD_END_CHAT_SESSION = "SALESFORCE_SERVICE_CLOUD_END_CHAT_SESSION"
        SERVICE_CLOUD_CHASITOR_SNEAK_PEEK = "SALESFORCE_SERVICE_CLOUD_CHASITOR_SNEAK_PEEK"
        SERVICE_CLOUD_VISITOR_SENSITIVE_DATA_RULE = "SALESFORCE_SERVICE_CLOUD_VISITOR_SENSITIVE_DATA_RULE"
        SERVICE_CLOUD_RETRIEVE_SALESFORCE_USERNAME = "SALESFORCE_SERVICE_CLOUD_RETRIEVE_SALESFORCE_USERNAME"
        SERVICE_CLOUD_GET_CHAT_MESSAGES = "SALESFORCE_SERVICE_CLOUD_GET_CHAT_MESSAGES"
        SERVICE_CLOUD_COMPOSITE_REQUEST = "SALESFORCE_SERVICE_CLOUD_COMPOSITE_REQUEST"
        SERVICE_CLOUD_DESCRIBE_S_OBJECT = "SALESFORCE_SERVICE_CLOUD_DESCRIBE_S_OBJECT"
        CREATE_NEW_CONTACT_WITH_JSON_HEADER = "SALESFORCE_CREATE_NEW_CONTACT_WITH_JSON_HEADER"
        UPDATE_A_RECORD = "SALESFORCE_UPDATE_A_RECORD"
        SERVICE_CLOUD_UPLOAD_FILE_TO_S3 = "SALESFORCE_SERVICE_CLOUD_UPLOAD_FILE_TO_S3"
        SERVICE_CLOUD_DELETE_CASE_RECORD = "SALESFORCE_SERVICE_CLOUD_DELETE_CASE_RECORD"
        SERVICE_CLOUD_RETRIEVE_CONNECTED_APP_PRIVATE_KEY = "SALESFORCE_SERVICE_CLOUD_RETRIEVE_CONNECTED_APP_PRIVATE_KEY"
        SERVICE_CLOUD_GENERATE_REQUEST_ID = "SALESFORCE_SERVICE_CLOUD_GENERATE_REQUEST_ID"
        SERVICE_CLOUD_COMPOSITE_BATCH = "SALESFORCE_SERVICE_CLOUD_COMPOSITE_BATCH"
        SERVICE_CLOUD_COMPOSITE_SOBJECT_TREE = "SALESFORCE_SERVICE_CLOUD_COMPOSITE_SOBJECT_TREE"
        SERVICE_CLOUD_CREATE_CASE_RECORD = "SALESFORCE_SERVICE_CLOUD_CREATE_CASE_RECORD"
        SERVICE_CLOUD_SET_BREADCRUMB = "SALESFORCE_SERVICE_CLOUD_SET_BREADCRUMB"
        SERVICE_CLOUD_DESCRIBE_CASE_S_OBJECT = "SALESFORCE_SERVICE_CLOUD_DESCRIBE_CASE_S_OBJECT"
        SERVICE_CLOUD_QUERY_ALL_SOQL = "SALESFORCE_SERVICE_CLOUD_QUERY_ALL_SOQL"
        SERVICE_CLOUD_UPSERT_CASE_RECORD = "SALESFORCE_SERVICE_CLOUD_UPSERT_CASE_RECORD"
        SERVICE_CLOUD_LIST_EINSTEIN_BOTS = "SALESFORCE_SERVICE_CLOUD_LIST_EINSTEIN_BOTS"
        SERVICE_CLOUD_AGENT_SENSITIVE_DATA_RULE_TRIGGERED = "SALESFORCE_SERVICE_CLOUD_AGENT_SENSITIVE_DATA_RULE_TRIGGERED"
        SERVICE_CLOUD_RECONNECT_CHAT_SESSION = "SALESFORCE_SERVICE_CLOUD_RECONNECT_CHAT_SESSION"
        QUERY_REPORT = "SALESFORCE_QUERY_REPORT"
        GET_LIST_VIEW_RECORDS_PER_API_NAME = "SALESFORCE_GET_LIST_VIEW_RECORDS_PER_API_NAME"
        QUICK_ACTIONS = "SALESFORCE_QUICK_ACTIONS"
        GET_NOTE = "SALESFORCE_GET_NOTE"
        DELETE_ACCOUNT = "SALESFORCE_DELETE_ACCOUNT"
        PARAMETERIZED_SEARCH_POST = "SALESFORCE_PARAMETERIZED_SEARCH_POST"
        DELETE_CONTACT = "SALESFORCE_DELETE_CONTACT"
        GET_COMPACT_LAYOUTS = "SALESFORCE_GET_COMPACT_LAYOUTS"
        CREATE_CAMPAIGN = "SALESFORCE_CREATE_CAMPAIGN"
        POST_UI_API_RECORDS = "SALESFORCE_POST_UI_API_RECORDS"
        GET_LIST_VIEW_RECORDS_PER_ID = "SALESFORCE_GET_LIST_VIEW_RECORDS_PER_ID"
        GET_UI_API_LIST_INFO_RECENT = "SALESFORCE_GET_UI_API_LIST_INFO_RECENT"
        UPDATE_LEAD = "SALESFORCE_UPDATE_LEAD"
        REMOVE_NOTE_OBJECT_BY_ID = "SALESFORCE_REMOVE_NOTE_OBJECT_BY_ID"
        RETRIEVE_OPPORTUNITY_BY_ID_WITH_OPTIONAL_FIELDS = "SALESFORCE_RETRIEVE_OPPORTUNITY_BY_ID_WITH_OPTIONAL_FIELDS"
        GET_ALL_FIELDS_FOR_OBJECT = "SALESFORCE_GET_ALL_FIELDS_FOR_OBJECT"
        POST_COMPOSITE_SOBJECTS_SOBJECT = "SALESFORCE_POST_COMPOSITE_SOBJECTS_SOBJECT"
        S_OBJECT_ROWS_DELETE = "SALESFORCE_S_OBJECT_ROWS_DELETE"
        DELETE_LEAD = "SALESFORCE_DELETE_LEAD"
        UPDATE_OPPORTUNITY_BY_ID = "SALESFORCE_UPDATE_OPPORTUNITY_BY_ID"
        FETCH_MODIFIED_OR_UNMODIFIED_SOBJECTS = "SALESFORCE_FETCH_MODIFIED_OR_UNMODIFIED_SOBJECTS"
        RETRIEVE_CONTACT_INFO_WITH_STANDARD_RESPONSES = "SALESFORCE_RETRIEVE_CONTACT_INFO_WITH_STANDARD_RESPONSES"
        UPSERT_S_OBJECT_BY_EXTERNAL_ID = "SALESFORCE_UPSERT_S_OBJECT_BY_EXTERNAL_ID"
        FILE_INFORMATION = "SALESFORCE_FILE_INFORMATION"
        UPDATE_LIST_VIEW_PREFERENCES = "SALESFORCE_UPDATE_LIST_VIEW_PREFERENCES"
        SEARCH_SUGGEST_TITLE_MATCHES = "SALESFORCE_SEARCH_SUGGEST_TITLE_MATCHES"
        POST_UI_API_RELATED_LIST_RECORDS_CONTACTS = "SALESFORCE_POST_UI_API_RELATED_LIST_RECORDS_CONTACTS"
        GET_UIAPI_LIST_INFO_ACCOUNT_SEARCH_RESULT = "SALESFORCE_GET_UIAPI_LIST_INFO_ACCOUNT_SEARCH_RESULT"
        GET_UI_API_RECORDS_BATCH = "SALESFORCE_GET_UI_API_RECORDS_BATCH"
        CREATE_TASK = "SALESFORCE_CREATE_TASK"
        DELETE_NOTE = "SALESFORCE_DELETE_NOTE"
        GET_MOST_RECENTLY_USED_LIST_VIEW_RECORDS = "SALESFORCE_GET_MOST_RECENTLY_USED_LIST_VIEW_RECORDS"
        GET_API = "SALESFORCE_GET_API"
        UPDATE_RELATED_LIST_PREFERENCES = "SALESFORCE_UPDATE_RELATED_LIST_PREFERENCES"
        GET_DASHBOARD = "SALESFORCE_GET_DASHBOARD"
        GET_NOTE_BY_ID_WITH_FIELDS = "SALESFORCE_GET_NOTE_BY_ID_WITH_FIELDS"
        GET_LEAD = "SALESFORCE_GET_LEAD"
        CREATE_A_RECORD = "SALESFORCE_CREATE_A_RECORD"
        COMPOSITE_GRAPH_ACTION = "SALESFORCE_COMPOSITE_GRAPH_ACTION"
        GET_UI_API_RECORD_UI = "SALESFORCE_GET_UI_API_RECORD_UI"
        GET_JOB_UNPROCESSED_RECORD_RESULTS = "SALESFORCE_GET_JOB_UNPROCESSED_RECORD_RESULTS"
        LIST_CONTACTS = "SALESFORCE_LIST_CONTACTS"
        ADD_OPPORTUNITY_LINE_ITEM = "SALESFORCE_ADD_OPPORTUNITY_LINE_ITEM"
        GET_S_OBJECTS = "SALESFORCE_GET_S_OBJECTS"
        GET_PHOTO_ACTIONS = "SALESFORCE_GET_PHOTO_ACTIONS"
        DELETE_OPPORTUNITY = "SALESFORCE_DELETE_OPPORTUNITY"
        ASSOCIATE_CONTACT_TO_ACCOUNT = "SALESFORCE_ASSOCIATE_CONTACT_TO_ACCOUNT"
        UPDATE_TASK = "SALESFORCE_UPDATE_TASK"
        EXECUTE_SOQL_QUERY = "SALESFORCE_EXECUTE_SOQL_QUERY"
        REMOVE_A_SPECIFIC_CONTACT_BY_ID = "SALESFORCE_REMOVE_A_SPECIFIC_CONTACT_BY_ID"
        CUSTOM_INVOCABLE_ACTIONS = "SALESFORCE_CUSTOM_INVOCABLE_ACTIONS"
        GET_S_OBJECTS_UPDATED = "SALESFORCE_GET_S_OBJECTS_UPDATED"
        S_OBJECT_APPROVAL_LAYOUTS = "SALESFORCE_S_OBJECT_APPROVAL_LAYOUTS"
        GET_LIST_VIEW_FOR_AN_OBJECT = "SALESFORCE_GET_LIST_VIEW_FOR_AN_OBJECT"
        LIST_LEADS = "SALESFORCE_LIST_LEADS"
        SOBJECT_TREE = "SALESFORCE_SOBJECT_TREE"
        CREATE_LEAD = "SALESFORCE_CREATE_LEAD"
        GET_JOB_QUERY_RESULT = "SALESFORCE_GET_JOB_QUERY_RESULT"
        FILE_SHARES = "SALESFORCE_FILE_SHARES"
        POST_COMPOSITE_SOBJECTS = "SALESFORCE_POST_COMPOSITE_SOBJECTS"
        GET_CHATTER_RESOURCES = "SALESFORCE_GET_CHATTER_RESOURCES"
        POST_PARAMETERIZED_SEARCH = "SALESFORCE_POST_PARAMETERIZED_SEARCH"
        HEAD_APPMENU_SALESFORCE1 = "SALESFORCE_HEAD_APPMENU_SALESFORCE1"
        HEAD_SOBJECTS_GLOBAL_DESCRIBE_LAYOUTS = "SALESFORCE_HEAD_SOBJECTS_GLOBAL_DESCRIBE_LAYOUTS"
        HEAD_ACTIONS_STANDARD = "SALESFORCE_HEAD_ACTIONS_STANDARD"
        GET_THEME = "SALESFORCE_GET_THEME"
        DELETE_A_LEAD_OBJECT_BY_ITS_ID = "SALESFORCE_DELETE_A_LEAD_OBJECT_BY_ITS_ID"
        GET_UI_API_APPS_USER_NAV_ITEMS = "SALESFORCE_GET_UI_API_APPS_USER_NAV_ITEMS"
        HEAD_SOBJECT_QUICK_ACTION_DEFAULT_VALUES = "SALESFORCE_HEAD_SOBJECT_QUICK_ACTION_DEFAULT_VALUES"
        SEARCH = "SALESFORCE_SEARCH"
        GET_S_OBJECTS_DESCRIBE_LAYOUTS_RECORD_TYPE_ID = "SALESFORCE_GET_S_OBJECTS_DESCRIBE_LAYOUTS_RECORD_TYPE_ID"
        GET_S_OBJECT_QUICK_ACTION_DEFAULT_VALUES = "SALESFORCE_GET_S_OBJECT_QUICK_ACTION_DEFAULT_VALUES"
        GET_UIAPI_LIST_INFO_ACCOUNT_RECENT = "SALESFORCE_GET_UIAPI_LIST_INFO_ACCOUNT_RECENT"
        RETRIEVE_ACCOUNT_DATA_AND_ERROR_RESPONSES = "SALESFORCE_RETRIEVE_ACCOUNT_DATA_AND_ERROR_RESPONSES"
        UPDATE_OPPORTUNITY = "SALESFORCE_UPDATE_OPPORTUNITY"
        ADD_CONTACT_TO_CAMPAIGN = "SALESFORCE_ADD_CONTACT_TO_CAMPAIGN"
        GET_SOBJECT_APPROVAL_LAYOUTS = "SALESFORCE_GET_SOBJECT_APPROVAL_LAYOUTS"
        CLOSE_OR_ABORT_A_JOB = "SALESFORCE_CLOSE_OR_ABORT_A_JOB"
        GET_CHILD_RECORDS = "SALESFORCE_GET_CHILD_RECORDS"
        GET_COMPOSITE_RESOURCES = "SALESFORCE_GET_COMPOSITE_RESOURCES"
        GET_REPORT_INSTANCE = "SALESFORCE_GET_REPORT_INSTANCE"
        HEAD_PROCESS_RULES_S_OBJECT = "SALESFORCE_HEAD_PROCESS_RULES_S_OBJECT"
        SEARCH_SUGGESTED_QUERIES = "SALESFORCE_SEARCH_SUGGESTED_QUERIES"
        DELETE_CAMPAIGN = "SALESFORCE_DELETE_CAMPAIGN"
        CLONE_RECORD = "SALESFORCE_CLONE_RECORD"
        GET_UI_API_RECORDS_BATCH_RECORDIDS = "SALESFORCE_GET_UI_API_RECORDS_BATCH_RECORDIDS"
        GET_UI_API_ACTIONS_RECORD_RELATED_LIST = "SALESFORCE_GET_UI_API_ACTIONS_RECORD_RELATED_LIST"
        GET_A_DIRECTORY_OF_SUPPORTED_OBJECTS = "SALESFORCE_GET_A_DIRECTORY_OF_SUPPORTED_OBJECTS"
        GET_REPORT = "SALESFORCE_GET_REPORT"
        POST_COMPOSITE_TREE_SOBJECTNAME = "SALESFORCE_POST_COMPOSITE_TREE_SOBJECTNAME"
        GET_FILE_CONTENT = "SALESFORCE_GET_FILE_CONTENT"
        GET_CONSENT = "SALESFORCE_GET_CONSENT"
        LIST_ACCOUNTS = "SALESFORCE_LIST_ACCOUNTS"
        LIST_OPPORTUNITIES = "SALESFORCE_LIST_OPPORTUNITIES"
        UPDATE_ACCOUNT = "SALESFORCE_UPDATE_ACCOUNT"
        CREATE_NOTE_RECORD_WITH_CONTENT_TYPE_HEADER = "SALESFORCE_CREATE_NOTE_RECORD_WITH_CONTENT_TYPE_HEADER"
        HEAD_SOBJECTS_USER_PASSWORD = "SALESFORCE_HEAD_SOBJECTS_USER_PASSWORD"
        QUERY = "SALESFORCE_QUERY"
        GET_LOOKUP_FIELD_SUGGESTIONS = "SALESFORCE_GET_LOOKUP_FIELD_SUGGESTIONS"
        GET_USER_PASSWORD_EXPIRATION_STATUS = "SALESFORCE_GET_USER_PASSWORD_EXPIRATION_STATUS"
        POST_COMPOSITE_GRAPH = "SALESFORCE_POST_COMPOSITE_GRAPH"
        PARAMETERIZED_SEARCH = "SALESFORCE_PARAMETERIZED_SEARCH"
        UPDATE_A_FAVORITE = "SALESFORCE_UPDATE_A_FAVORITE"
        GET_SOBJECT_RELATIONSHIP = "SALESFORCE_GET_SOBJECT_RELATIONSHIP"
        UPDATE_LEAD_BY_ID_WITH_JSON_PAYLOAD = "SALESFORCE_UPDATE_LEAD_BY_ID_WITH_JSON_PAYLOAD"
        CREATE_OPPORTUNITY_RECORD = "SALESFORCE_CREATE_OPPORTUNITY_RECORD"
        GET_RECORD_EDIT_PAGE_ACTIONS = "SALESFORCE_GET_RECORD_EDIT_PAGE_ACTIONS"
        LIST_ANALYTICS_TEMPLATES = "SALESFORCE_LIST_ANALYTICS_TEMPLATES"
        ADD_LEAD_TO_CAMPAIGN = "SALESFORCE_ADD_LEAD_TO_CAMPAIGN"
        SEARCH_LEADS = "SALESFORCE_SEARCH_LEADS"
        GET_ACCOUNT = "SALESFORCE_GET_ACCOUNT"
        SEND_MASS_EMAIL = "SALESFORCE_SEND_MASS_EMAIL"
        HEAD_SOBJECTS_QUICK_ACTION = "SALESFORCE_HEAD_SOBJECTS_QUICK_ACTION"
        CREATE_LEAD_WITH_SPECIFIED_CONTENT_TYPE = "SALESFORCE_CREATE_LEAD_WITH_SPECIFIED_CONTENT_TYPE"
        GET_LIST_VIEW_METADATA_PER_API_NAME = "SALESFORCE_GET_LIST_VIEW_METADATA_PER_API_NAME"
        GET_JOB_INFO_QUERY = "SALESFORCE_GET_JOB_INFO_QUERY"
        GET_LAST_SELECTED_APP = "SALESFORCE_GET_LAST_SELECTED_APP"
        COMPLETE_TASK = "SALESFORCE_COMPLETE_TASK"
        CREATE_ACCOUNT = "SALESFORCE_CREATE_ACCOUNT"
        REMOVE_OPPORTUNITY_BY_ID = "SALESFORCE_REMOVE_OPPORTUNITY_BY_ID"
        GET_LIMITS = "SALESFORCE_GET_LIMITS"
        LIST_DASHBOARDS = "SALESFORCE_LIST_DASHBOARDS"
        GET_UIAPIMRU_LIST_INFO_ACCOUNT = "SALESFORCE_GET_UIAPIMRU_LIST_INFO_ACCOUNT"
        PATCH_UI_API_RECORDS = "SALESFORCE_PATCH_UI_API_RECORDS"
        HEAD_ACTIONS_CUSTOM = "SALESFORCE_HEAD_ACTIONS_CUSTOM"
        RETRIEVE_LEAD_BY_ID = "SALESFORCE_RETRIEVE_LEAD_BY_ID"
        APPLY_LEAD_ASSIGNMENT_RULES = "SALESFORCE_APPLY_LEAD_ASSIGNMENT_RULES"
        GET_CAMPAIGN = "SALESFORCE_GET_CAMPAIGN"
        UPDATE_CAMPAIGN = "SALESFORCE_UPDATE_CAMPAIGN"
        SET_USER_PASSWORD = "SALESFORCE_SET_USER_PASSWORD"
        REMOVE_FROM_CAMPAIGN = "SALESFORCE_REMOVE_FROM_CAMPAIGN"
        SOBJECT_COLLECTIONS_DELETE = "SALESFORCE_SOBJECT_COLLECTIONS_DELETE"
        DELETE_FILE = "SALESFORCE_DELETE_FILE"
        PATCH_COMPOSITE_SOBJECTS = "SALESFORCE_PATCH_COMPOSITE_SOBJECTS"
        CLONE_OPPORTUNITY_WITH_PRODUCTS = "SALESFORCE_CLONE_OPPORTUNITY_WITH_PRODUCTS"
        LIST_PRICEBOOKS = "SALESFORCE_LIST_PRICEBOOKS"
        GET_AN_APP = "SALESFORCE_GET_AN_APP"
        GET_JOB_FAILED_RECORD_RESULTS = "SALESFORCE_GET_JOB_FAILED_RECORD_RESULTS"
        UPLOAD_FILE = "SALESFORCE_UPLOAD_FILE"
        GET_CONTACT = "SALESFORCE_GET_CONTACT"
        GET_S_OBJECT_RECORD = "SALESFORCE_GET_S_OBJECT_RECORD"
        GET_S_OBJECT_BY_EXTERNAL_ID = "SALESFORCE_GET_S_OBJECT_BY_EXTERNAL_ID"
        SEND_EMAIL_FROM_TEMPLATE = "SALESFORCE_SEND_EMAIL_FROM_TEMPLATE"
        SEARCH_ACCOUNTS = "SALESFORCE_SEARCH_ACCOUNTS"
        S_OBJECT_USER_PASSWORD = "SALESFORCE_S_OBJECT_USER_PASSWORD"
        SEARCH_OPPORTUNITIES = "SALESFORCE_SEARCH_OPPORTUNITIES"
        EXECUTE_SOSL_SEARCH = "SALESFORCE_EXECUTE_SOSL_SEARCH"
        SOBJECT_PLATFORMACTION = "SALESFORCE_SOBJECT_PLATFORMACTION"
        LIST_REPORTS = "SALESFORCE_LIST_REPORTS"
        UPDATE_ACCOUNT_OBJECT_BY_ID = "SALESFORCE_UPDATE_ACCOUNT_OBJECT_BY_ID"
        GET_A_BATCH_OF_RECORDS = "SALESFORCE_GET_A_BATCH_OF_RECORDS"
        SEARCH_NOTES = "SALESFORCE_SEARCH_NOTES"
        STANDARD_INVOCABLE_ACTIONS = "SALESFORCE_STANDARD_INVOCABLE_ACTIONS"
        SEARCH_RESULT_LAYOUTS = "SALESFORCE_SEARCH_RESULT_LAYOUTS"
        HEAD_QUICK_ACTIONS = "SALESFORCE_HEAD_QUICK_ACTIONS"
        GET_ALL_CUSTOM_OBJECTS = "SALESFORCE_GET_ALL_CUSTOM_OBJECTS"
        LIST_NOTES = "SALESFORCE_LIST_NOTES"
        GET_QUICK_ACTIONS = "SALESFORCE_GET_QUICK_ACTIONS"
        GET_MRU_LIST_VIEW_METADATA = "SALESFORCE_GET_MRU_LIST_VIEW_METADATA"
        CREATE_NOTE = "SALESFORCE_CREATE_NOTE"
        DELETE_SOBJECT = "SALESFORCE_DELETE_SOBJECT"
        GET_SEARCH_LAYOUT = "SALESFORCE_GET_SEARCH_LAYOUT"
        GET_SOBJECTS_SOBJECT_DESCRIBE_APPROVALLAYOUTS = "SALESFORCE_GET_SOBJECTS_SOBJECT_DESCRIBE_APPROVALLAYOUTS"
        RETRIEVE_SPECIFIC_CAMPAIGN_OBJECT_DETAILS = "SALESFORCE_RETRIEVE_SPECIFIC_CAMPAIGN_OBJECT_DETAILS"
        GET_APPS = "SALESFORCE_GET_APPS"
        LIST_VIEW_RESULTS = "SALESFORCE_LIST_VIEW_RESULTS"
        MASS_TRANSFER_OWNERSHIP = "SALESFORCE_MASS_TRANSFER_OWNERSHIP"
        LOG_EMAIL_ACTIVITY = "SALESFORCE_LOG_EMAIL_ACTIVITY"
        REMOVE_CAMPAIGN_OBJECT_BY_ID = "SALESFORCE_REMOVE_CAMPAIGN_OBJECT_BY_ID"
        GET_LIST_VIEW_RESULTS = "SALESFORCE_GET_LIST_VIEW_RESULTS"
        RETRIEVE_OPPORTUNITIES_DATA = "SALESFORCE_RETRIEVE_OPPORTUNITIES_DATA"
        POST_SOBJECT_QUICK_ACTIONS = "SALESFORCE_POST_SOBJECT_QUICK_ACTIONS"
        QUERY_CONTACTS_BY_NAME = "SALESFORCE_QUERY_CONTACTS_BY_NAME"
        GET_RELATED_LIST_ACTIONS = "SALESFORCE_GET_RELATED_LIST_ACTIONS"
        CREATE_CAMPAIGN_RECORD_VIA_POST = "SALESFORCE_CREATE_CAMPAIGN_RECORD_VIA_POST"
        RUN_REPORT = "SALESFORCE_RUN_REPORT"
        GET_CONSENT_ACTION = "SALESFORCE_GET_CONSENT_ACTION"
        GET_LIMITS_RECORDCOUNT = "SALESFORCE_GET_LIMITS_RECORDCOUNT"
        UPDATE_NOTE = "SALESFORCE_UPDATE_NOTE"
        REMOVE_ACCOUNT_BY_UNIQUE_IDENTIFIER = "SALESFORCE_REMOVE_ACCOUNT_BY_UNIQUE_IDENTIFIER"
        GET_GLOBAL_ACTIONS = "SALESFORCE_GET_GLOBAL_ACTIONS"
        GET_RELATED_LIST_PREFS_BATCH = "SALESFORCE_GET_RELATED_LIST_PREFS_BATCH"
        CREATE_OPPORTUNITY = "SALESFORCE_CREATE_OPPORTUNITY"
        GET_SEARCH_RESULT_LAYOUTS = "SALESFORCE_GET_SEARCH_RESULT_LAYOUTS"
        GET_SOBJECT_LISTVIEWS = "SALESFORCE_GET_SOBJECT_LISTVIEWS"
        TOOLING_QUERY = "SALESFORCE_TOOLING_QUERY"
        GET_SUPPORT_KNOWLEDGE_ARTICLES = "SALESFORCE_GET_SUPPORT_KNOWLEDGE_ARTICLES"
        SEND_EMAIL = "SALESFORCE_SEND_EMAIL"
        RETRIEVE_NOTE_OBJECT_INFORMATION = "SALESFORCE_RETRIEVE_NOTE_OBJECT_INFORMATION"
        RETRIEVE_LEAD_DATA_WITH_VARIOUS_RESPONSES = "SALESFORCE_RETRIEVE_LEAD_DATA_WITH_VARIOUS_RESPONSES"
        POST_SOBJECTS_SOBJECT_ID = "SALESFORCE_POST_SOBJECTS_SOBJECT_ID"
        GET_OPPORTUNITY = "SALESFORCE_GET_OPPORTUNITY"
        SEARCH_CAMPAIGNS = "SALESFORCE_SEARCH_CAMPAIGNS"
        GET_SUPPORT = "SALESFORCE_GET_SUPPORT"
        UPDATE_CONTACT_BY_ID = "SALESFORCE_UPDATE_CONTACT_BY_ID"
        GET_S_OBJECT_COLLECTIONS = "SALESFORCE_GET_S_OBJECT_COLLECTIONS"
        UPDATE_SPECIFIC_NOTE_BY_ID = "SALESFORCE_UPDATE_SPECIFIC_NOTE_BY_ID"
        UPDATE_CAMPAIGN_BY_ID_WITH_JSON = "SALESFORCE_UPDATE_CAMPAIGN_BY_ID_WITH_JSON"
        SOBJECT_COLLECTIONS_CREATE = "SALESFORCE_SOBJECT_COLLECTIONS_CREATE"
        FETCH_ACCOUNT_BY_ID_WITH_QUERY = "SALESFORCE_FETCH_ACCOUNT_BY_ID_WITH_QUERY"
        GET_UIAPI_LIST_INFO_ACCOUNT_ALL_ACCOUNTS = "SALESFORCE_GET_UIAPI_LIST_INFO_ACCOUNT_ALL_ACCOUNTS"
        GET_PARAMETERIZEDSEARCH = "SALESFORCE_GET_PARAMETERIZEDSEARCH"
        RETRIEVE_SPECIFIC_CONTACT_BY_ID = "SALESFORCE_RETRIEVE_SPECIFIC_CONTACT_BY_ID"
        SEARCH_TASKS = "SALESFORCE_SEARCH_TASKS"
        LIST_EMAIL_TEMPLATES = "SALESFORCE_LIST_EMAIL_TEMPLATES"
        GET_ALL_NAVIGATION_ITEMS = "SALESFORCE_GET_ALL_NAVIGATION_ITEMS"
        GET_DATA_UIAPI_ACTIONS_LIST_VIEW = "SALESFORCE_GET_DATA_UIAPI_ACTIONS_LIST_VIEW"
        PATCH_S_OBJECT_BY_ID = "SALESFORCE_PATCH_S_OBJECT_BY_ID"
        GET_UI_API_MRU_LIST_RECORDS_ACCOUNT = "SALESFORCE_GET_UI_API_MRU_LIST_RECORDS_ACCOUNT"
        ACCOUNT_CREATION_WITH_CONTENT_TYPE_OPTION = "SALESFORCE_ACCOUNT_CREATION_WITH_CONTENT_TYPE_OPTION"
        GET_ORG_LIMITS = "SALESFORCE_GET_ORG_LIMITS"
        RUN_SOQL_QUERY = "SALESFORCE_RUN_SOQL_QUERY"
        GET_UI_API_ACTIONS_LOOKUP_ACCOUNT = "SALESFORCE_GET_UI_API_ACTIONS_LOOKUP_ACCOUNT"
        GET_UIAPI_RELATED_LIST_PREFERENCES = "SALESFORCE_GET_UIAPI_RELATED_LIST_PREFERENCES"
        GET_SOBJECT_QUICK_ACTION_DEFAULT_VALUES = "SALESFORCE_GET_SOBJECT_QUICK_ACTION_DEFAULT_VALUES"
        GET_UIAPI_ACTIONS_MRU_LIST_ACCOUNT = "SALESFORCE_GET_UIAPI_ACTIONS_MRU_LIST_ACCOUNT"
        UPDATE_CONTACT = "SALESFORCE_UPDATE_CONTACT"
        POST_UIAPI_LOOKUPS_CASE_CONTACT_ID = "SALESFORCE_POST_UIAPI_LOOKUPS_CASE_CONTACT_ID"
        GET_PICKLIST_VALUES_BY_RECORD_TYPE = "SALESFORCE_GET_PICKLIST_VALUES_BY_RECORD_TYPE"
        GET_S_OBJECT_LIST_VIEW = "SALESFORCE_GET_S_OBJECT_LIST_VIEW"
        CREATE_CONTACT = "SALESFORCE_CREATE_CONTACT"
        DELETE_JOB_QUERY = "SALESFORCE_DELETE_JOB_QUERY"
        DESCRIBE_GLOBAL = "SALESFORCE_DESCRIBE_GLOBAL"
        RETRIEVE_CAMPAIGN_DATA_WITH_ERROR_HANDLING = "SALESFORCE_RETRIEVE_CAMPAIGN_DATA_WITH_ERROR_HANDLING"
        GET_JOB_SUCCESSFUL_RECORD_RESULTS = "SALESFORCE_GET_JOB_SUCCESSFUL_RECORD_RESULTS"
        UPLOAD_JOB_DATA = "SALESFORCE_UPLOAD_JOB_DATA"
        SOBJECT_ROWS_UPDATE = "SALESFORCE_SOBJECT_ROWS_UPDATE"
        LIST_PRICEBOOK_ENTRIES = "SALESFORCE_LIST_PRICEBOOK_ENTRIES"
        GET_LIST_VIEW_METADATA_BATCH = "SALESFORCE_GET_LIST_VIEW_METADATA_BATCH"
        QUERY_ALL = "SALESFORCE_QUERY_ALL"
        LIST_CAMPAIGNS = "SALESFORCE_LIST_CAMPAIGNS"
        GET_USER_INFO = "SALESFORCE_GET_USER_INFO"
        GET_UIAPI_LOOKUPS_OPPORTUNITY_ACCOUNT_ID = "SALESFORCE_GET_UIAPI_LOOKUPS_OPPORTUNITY_ACCOUNT_ID"
        POST_UIAPI_LOOKUPS_OPPORTUNITY_ACCOUNT_ID = "SALESFORCE_POST_UIAPI_LOOKUPS_OPPORTUNITY_ACCOUNT_ID"

    class triggers:
        ACCOUNT_CREATED_OR_UPDATED_TRIGGER = {
          "config": {
            "description": "Configuration for Salesforce Account created or updated trigger.",
            "properties": {
              "additional_filter": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Optional additional SOQL filter to AND with LastModifiedDate condition. Example: Industry = 'Technology'",
                "title": "Additional Filter"
              },
              "fields": {
                "anyOf": [{
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Optional list of Account fields to include in the payload. If not provided, a set of common key fields is returned.",
                "title": "Fields"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "max_records": {
                "default": 100,
                "description": "Maximum number of accounts to check in each poll (1-1000)",
                "maximum": 1000,
                "minimum": 1,
                "title": "Max Records",
                "type": "integer"
              }
            },
            "title": "AccountCreatedOrUpdatedConfig",
            "type": "object"
          },
          "description": "Triggers when an Account is created or updated in Salesforce.\n    Uses LastModifiedDate high-watermark to capture both creations and updates.",
          "instructions": "This trigger monitors Salesforce Accounts and fires when an Account is created or updated. You can optionally supply an additional SOQL filter (e.g., Industry = 'Technology'). On the very first run, the trigger initializes without emitting historical records.",
          "name": "Account Created or Updated",
          "payload": {
            "$defs": {
              "AccountSchema": {
                "description": "Schema for a Salesforce Account.",
                "properties": {
                  "account_number": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Account Number",
                    "title": "Account Number"
                  },
                  "billing_city": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Billing city",
                    "title": "Billing City"
                  },
                  "billing_country": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Billing country",
                    "title": "Billing Country"
                  },
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the Account was created (ISO8601)",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the Account",
                    "title": "Id",
                    "type": "string"
                  },
                  "industry": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Industry of the Account",
                    "title": "Industry"
                  },
                  "last_modified_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the Account was last modified (ISO8601)",
                    "title": "Last Modified Date"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the Account",
                    "title": "Name"
                  },
                  "owner_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Owner ID",
                    "title": "Owner Id"
                  },
                  "phone": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Main phone number",
                    "title": "Phone"
                  },
                  "raw_fields": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Raw Salesforce fields as returned by SOQL for extensibility",
                    "title": "Raw Fields"
                  },
                  "shipping_city": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Shipping city",
                    "title": "Shipping City"
                  },
                  "shipping_country": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Shipping country",
                    "title": "Shipping Country"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Type of the Account",
                    "title": "Type"
                  },
                  "website": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Website URL",
                    "title": "Website"
                  }
                },
                "required": ["id"],
                "title": "AccountSchema",
                "type": "object"
              }
            },
            "description": "Payload for Account created or updated event.",
            "properties": {
              "account": {
                "additionalProperties": False,
                "description": "The Account record",
                "properties": {
                  "account_number": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Account Number",
                    "title": "Account Number"
                  },
                  "billing_city": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Billing city",
                    "title": "Billing City"
                  },
                  "billing_country": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Billing country",
                    "title": "Billing Country"
                  },
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the Account was created (ISO8601)",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the Account",
                    "title": "Id",
                    "type": "string"
                  },
                  "industry": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Industry of the Account",
                    "title": "Industry"
                  },
                  "last_modified_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the Account was last modified (ISO8601)",
                    "title": "Last Modified Date"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The name of the Account",
                    "title": "Name"
                  },
                  "owner_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Owner ID",
                    "title": "Owner Id"
                  },
                  "phone": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Main phone number",
                    "title": "Phone"
                  },
                  "raw_fields": {
                    "anyOf": [{
                        "additionalProperties": True,
                        "type": "object"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Raw Salesforce fields as returned by SOQL for extensibility",
                    "title": "Raw Fields"
                  },
                  "shipping_city": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Shipping city",
                    "title": "Shipping City"
                  },
                  "shipping_country": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Shipping country",
                    "title": "Shipping Country"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Type of the Account",
                    "title": "Type"
                  },
                  "website": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Website URL",
                    "title": "Website"
                  }
                },
                "required": ["id"],
                "title": "Account",
                "type": "object"
              },
              "event_type": {
                "default": "account_created_or_updated",
                "description": "Type of Salesforce Account event",
                "title": "Event Type",
                "type": "string"
              }
            },
            "required": ["account"],
            "title": "AccountChangePayload",
            "type": "object"
          },
          "slug": "SALESFORCE_ACCOUNT_CREATED_OR_UPDATED_TRIGGER",
          "type": "poll"
        }
        CONTACT_UPDATED_TRIGGER = {
          "config": {
            "description": "Configuration for Salesforce Contact Updated trigger.",
            "properties": {
              "fields_to_watch": {
                "anyOf": [{
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": ["FirstName", "LastName", "Name", "Email", "Phone", "Title", "Department", "AccountId", "MailingStreet", "MailingCity", "MailingState", "MailingPostalCode", "MailingCountry"],
                "description": "List of Contact fields to monitor for changes. Only changes in these fields will be emitted in the payload.",
                "title": "Fields To Watch"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "max_batch_size": {
                "default": 100,
                "description": "Maximum number of updated contacts to fetch per poll (LIMIT).",
                "maximum": 2000,
                "minimum": 1,
                "title": "Max Batch Size",
                "type": "integer"
              }
            },
            "title": "ContactUpdatedConfig",
            "type": "object"
          },
          "description": "Triggers when an existing Salesforce Contact record is modified.\n    Emits changed fields alongside relevant timestamps.",
          "instructions": "Monitors Salesforce Contacts and fires when an existing record is modified. Configure optional fields_to_watch to control which fields are diffed. On the first run (when last_synced_at == 0), the trigger initializes state without emitting any events.",
          "name": "Contact Updated",
          "payload": {
            "description": "Payload emitted when a Salesforce Contact is updated.",
            "properties": {
              "changed_fields": {
                "additionalProperties": {
                  "additionalProperties": True,
                  "type": "object"
                },
                "description": "Mapping of field name to {old, new} values",
                "title": "Changed Fields",
                "type": "object"
              },
              "contact_id": {
                "description": "The ID of the updated contact",
                "title": "Contact Id",
                "type": "string"
              },
              "event_type": {
                "default": "contact_updated",
                "description": "Type of event",
                "title": "Event Type",
                "type": "string"
              },
              "last_modified_date": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "LastModifiedDate timestamp of the record",
                "title": "Last Modified Date"
              },
              "system_modstamp": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "SystemModstamp timestamp of the record",
                "title": "System Modstamp"
              }
            },
            "required": ["contact_id", "changed_fields"],
            "title": "ContactUpdatedPayload",
            "type": "object"
          },
          "slug": "SALESFORCE_CONTACT_UPDATED_TRIGGER",
          "type": "poll"
        }
        GENERIC_S_OBJECT_RECORD_UPDATED_TRIGGER = {
          "config": {
            "description": "Configuration for Salesforce generic record updated trigger.",
            "properties": {
              "fields_to_monitor": {
                "anyOf": [{
                    "items": {
                      "type": "string"
                    },
                    "type": "array"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "List of field API names to include in the payload when a record is updated. If omitted, only metadata like Id, SystemModstamp, and LastModifiedDate will be returned.",
                "title": "Fields To Monitor"
              },
              "filter": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Optional SOQL filter expression to further restrict which records to monitor. Example: OwnerId = '005XXXXXXXXXXXX' AND IsDeleted = false",
                "title": "Filter"
              },
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "max_results": {
                "anyOf": [{
                    "maximum": 2000,
                    "minimum": 1,
                    "type": "integer"
                  }, {
                    "type": "null"
                  }],
                "default": 200,
                "description": "Maximum number of records to fetch per poll (1-2000).",
                "title": "Max Results"
              },
              "sobject_name": {
                "description": "The API name of the Salesforce SObject to monitor (e.g., Account, Contact, Lead)",
                "title": "Sobject Name",
                "type": "string"
              }
            },
            "required": ["sobject_name"],
            "title": "GenericRecordUpdatedConfig",
            "type": "object"
          },
          "description": "Triggers when monitored fields change on any Salesforce SObject. You specify the SObject type\n    and which field values should be returned in the payload. The trigger uses SystemModstamp to\n    detect changes regardless of which specific field changed.",
          "instructions": "This trigger monitors any Salesforce SObject for updates using SystemModstamp. Configure it with:\n- sobject_name: The target SObject API name (e.g., Account, Contact, Lead).\n- fields_to_monitor: Optional list of field API names to include in the payload.\n- filter: Optional additional SOQL filter (e.g., OwnerId = '005...' AND IsDeleted = false).\nOn first run (when last_synced_at = 0), the trigger initializes and returns no events. Subsequent polls return records updated after the last sync time.",
          "name": "Record Updated (Generic SObject)",
          "payload": {
            "description": "Payload for a generic Salesforce SObject update event.",
            "properties": {
              "event_type": {
                "default": "record_updated",
                "description": "Type of event emitted for the generic SObject update",
                "title": "Event Type",
                "type": "string"
              },
              "id": {
                "description": "The record ID",
                "title": "Id",
                "type": "string"
              },
              "last_modified_date": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "LastModifiedDate value of the record at the time of update",
                "title": "Last Modified Date"
              },
              "monitored_values": {
                "additionalProperties": True,
                "description": "A dictionary of monitored field values at the time of the update",
                "title": "Monitored Values",
                "type": "object"
              },
              "sobject": {
                "description": "The SObject type that was updated",
                "title": "Sobject",
                "type": "string"
              },
              "system_modstamp": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "SystemModstamp value of the record at the time of update",
                "title": "System Modstamp"
              }
            },
            "required": ["sobject", "id"],
            "title": "UpdatedRecordPayload",
            "type": "object"
          },
          "slug": "SALESFORCE_GENERIC_S_OBJECT_RECORD_UPDATED_TRIGGER",
          "type": "poll"
        }
        NEW_CONTACT_TRIGGER = {
          "config": {
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "NewContactConfig",
            "type": "object"
          },
          "description": "Triggers when a new Contact is Created in Salesforce.",
          "instructions": "",
          "name": "New Contact Trigger",
          "payload": {
            "$defs": {
              "ContactSchema": {
                "description": "Schema for a Salesforce contact.",
                "properties": {
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the contact was created",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the contact",
                    "title": "Id",
                    "type": "string"
                  },
                  "name": {
                    "description": "The name of the contact",
                    "title": "Name",
                    "type": "string"
                  }
                },
                "required": ["id", "name"],
                "title": "ContactSchema",
                "type": "object"
              }
            },
            "description": "Payload model for Salesforce contact events.",
            "properties": {
              "contact": {
                "additionalProperties": False,
                "description": "The Salesforce contact that was created",
                "properties": {
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the contact was created",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the contact",
                    "title": "Id",
                    "type": "string"
                  },
                  "name": {
                    "description": "The name of the contact",
                    "title": "Name",
                    "type": "string"
                  }
                },
                "required": ["id", "name"],
                "title": "Contact",
                "type": "object"
              },
              "event_type": {
                "default": "new_contact",
                "description": "Type of Salesforce contact event",
                "title": "Event Type",
                "type": "string"
              }
            },
            "required": ["contact"],
            "title": "ContactPayload",
            "type": "object"
          },
          "slug": "SALESFORCE_NEW_CONTACT_TRIGGER",
          "type": "poll"
        }
        NEW_LEAD_TRIGGER = {
          "config": {
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              }
            },
            "title": "NewLeadConfigSchema",
            "type": "object"
          },
          "description": "Triggers when a new Lead is created in Salesforce.",
          "instructions": "",
          "name": "New Lead Trigger",
          "payload": {
            "$defs": {
              "LeadSchema": {
                "description": "Schema for a Salesforce lead.",
                "properties": {
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the lead was created",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the lead",
                    "title": "Id",
                    "type": "string"
                  },
                  "name": {
                    "description": "The name of the lead",
                    "title": "Name",
                    "type": "string"
                  }
                },
                "required": ["id", "name"],
                "title": "LeadSchema",
                "type": "object"
              }
            },
            "description": "Payload model for Salesforce lead events.",
            "properties": {
              "event_type": {
                "default": "new_lead",
                "description": "Type of Salesforce lead event",
                "title": "Event Type",
                "type": "string"
              },
              "lead": {
                "additionalProperties": False,
                "description": "The Salesforce lead that was created",
                "properties": {
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the lead was created",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the lead",
                    "title": "Id",
                    "type": "string"
                  },
                  "name": {
                    "description": "The name of the lead",
                    "title": "Name",
                    "type": "string"
                  }
                },
                "required": ["id", "name"],
                "title": "Lead",
                "type": "object"
              }
            },
            "required": ["lead"],
            "title": "LeadPayload",
            "type": "object"
          },
          "slug": "SALESFORCE_NEW_LEAD_TRIGGER",
          "type": "poll"
        }
        NEW_OR_UPDATED_OPPORTUNITY_TRIGGER = {
          "config": {
            "description": "Configuration for Salesforce New or Updated Opportunity trigger.",
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "max_results": {
                "default": 200,
                "description": "Maximum number of records to fetch per poll (1-2000).",
                "maximum": 2000,
                "minimum": 1,
                "title": "Max Results",
                "type": "integer"
              },
              "stage_name": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Optional StageName to filter opportunities by. When provided, only opportunities with this StageName will be returned.",
                "examples": ["Prospecting", "Qualification", "Needs Analysis", "Value Proposition", "Id. Decision Makers", "Perception Analysis", "Proposal/Price Quote", "Negotiation/Review", "Closed Won", "Closed Lost"],
                "title": "Stage Name"
              }
            },
            "title": "NewOrUpdatedOpportunityConfig",
            "type": "object"
          },
          "description": "Triggers when a Salesforce Opportunity is created or updated.",
          "instructions": "This trigger polls Salesforce Opportunities and fires when new opportunities are created or existing ones are updated. Optionally filter by a specific StageName. Configure max_results to control page size. On first run (when last_synced_at is 0), the trigger initializes sync and returns no events to avoid backfilling old records.",
          "name": "New or Updated Opportunity",
          "payload": {
            "$defs": {
              "OpportunitySchema": {
                "description": "Schema for a Salesforce Opportunity.",
                "properties": {
                  "account_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related Account Id",
                    "title": "Account Id"
                  },
                  "amount": {
                    "anyOf": [{
                        "type": "number"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Opportunity amount",
                    "title": "Amount"
                  },
                  "close_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Expected close date in YYYY-MM-DD format",
                    "title": "Close Date"
                  },
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the record was created",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the opportunity",
                    "title": "Id",
                    "type": "string"
                  },
                  "last_modified_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the record was last modified",
                    "title": "Last Modified Date"
                  },
                  "lead_source": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Lead Source",
                    "title": "Lead Source"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Opportunity name",
                    "title": "Name"
                  },
                  "probability": {
                    "anyOf": [{
                        "type": "number"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Probability of closing (0-100)",
                    "title": "Probability"
                  },
                  "stage_name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Stage of the opportunity",
                    "title": "Stage Name"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Type of opportunity",
                    "title": "Type"
                  }
                },
                "required": ["id"],
                "title": "OpportunitySchema",
                "type": "object"
              }
            },
            "description": "Payload model for Salesforce opportunity events.",
            "properties": {
              "event_type": {
                "default": "opportunity_created_or_updated",
                "description": "Type of Salesforce opportunity event",
                "title": "Event Type",
                "type": "string"
              },
              "opportunity": {
                "additionalProperties": False,
                "description": "The Salesforce Opportunity that was created or updated",
                "properties": {
                  "account_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related Account Id",
                    "title": "Account Id"
                  },
                  "amount": {
                    "anyOf": [{
                        "type": "number"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Opportunity amount",
                    "title": "Amount"
                  },
                  "close_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Expected close date in YYYY-MM-DD format",
                    "title": "Close Date"
                  },
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the record was created",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the opportunity",
                    "title": "Id",
                    "type": "string"
                  },
                  "last_modified_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "When the record was last modified",
                    "title": "Last Modified Date"
                  },
                  "lead_source": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Lead Source",
                    "title": "Lead Source"
                  },
                  "name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Opportunity name",
                    "title": "Name"
                  },
                  "probability": {
                    "anyOf": [{
                        "type": "number"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Probability of closing (0-100)",
                    "title": "Probability"
                  },
                  "stage_name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Stage of the opportunity",
                    "title": "Stage Name"
                  },
                  "type": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Type of opportunity",
                    "title": "Type"
                  }
                },
                "required": ["id"],
                "title": "Opportunity",
                "type": "object"
              }
            },
            "required": ["opportunity"],
            "title": "OpportunityPayload",
            "type": "object"
          },
          "slug": "SALESFORCE_NEW_OR_UPDATED_OPPORTUNITY_TRIGGER",
          "type": "poll"
        }
        TASK_CREATED_OR_COMPLETED_TRIGGER = {
          "config": {
            "description": "Configuration for Salesforce Task Created or Completed trigger.",
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "limit": {
                "default": 50,
                "description": "Maximum number of tasks to retrieve per poll",
                "maximum": 2000,
                "minimum": 1,
                "title": "Limit",
                "type": "integer"
              },
              "status": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Filter tasks by exact Status (e.g., 'Not Started', 'In Progress', 'Completed')",
                "examples": ["Completed", "In Progress", "Not Started"],
                "title": "Status"
              },
              "subject": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "Filter tasks where Subject contains this text (partial match)",
                "examples": ["Follow up", "Call", "Meeting"],
                "title": "Subject"
              }
            },
            "title": "TaskCreatedOrCompletedConfig",
            "type": "object"
          },
          "description": "Triggers when a Task is created or when its status changes to Completed in Salesforce.\n    Supports optional filtering by task Status or Subject.",
          "instructions": "\n    This trigger monitors Salesforce Tasks and fires when:\n    - A new Task record is created\n    - A Task's status changes to Completed (or IsClosed becomes true)\n\n    Optional filters:\n    - status: Only include tasks with this Status\n    - subject: Only include tasks whose Subject contains this text\n\n    Note: On the very first run, the trigger initializes sync state and returns no events.\n    ",
          "name": "Task Created or Completed",
          "payload": {
            "$defs": {
              "TaskSchema": {
                "description": "Schema for a Salesforce Task.",
                "properties": {
                  "activity_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The due date of the task (ActivityDate)",
                    "title": "Activity Date"
                  },
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "ISO datetime when the task was created",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the task",
                    "title": "Id",
                    "type": "string"
                  },
                  "is_closed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the task is closed/completed",
                    "title": "Is Closed"
                  },
                  "last_modified_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "ISO datetime when the task was last modified",
                    "title": "Last Modified Date"
                  },
                  "owner_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Owner ID of the task",
                    "title": "Owner Id"
                  },
                  "owner_name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Owner name of the task",
                    "title": "Owner Name"
                  },
                  "priority": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Priority of the task",
                    "title": "Priority"
                  },
                  "status": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Status of the task",
                    "title": "Status"
                  },
                  "subject": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Subject of the task",
                    "title": "Subject"
                  },
                  "what_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related record (WhatId)",
                    "title": "What Id"
                  },
                  "what_name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related record name (What.Name)",
                    "title": "What Name"
                  },
                  "who_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related contact/lead (WhoId)",
                    "title": "Who Id"
                  },
                  "who_name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related contact/lead name (Who.Name)",
                    "title": "Who Name"
                  }
                },
                "required": ["id"],
                "title": "TaskSchema",
                "type": "object"
              }
            },
            "description": "Payload model for Salesforce Task events.",
            "properties": {
              "event_type": {
                "description": "Type of event: 'task_created' or 'task_completed'",
                "title": "Event Type",
                "type": "string"
              },
              "task": {
                "additionalProperties": False,
                "description": "The Salesforce task involved in the event",
                "properties": {
                  "activity_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "The due date of the task (ActivityDate)",
                    "title": "Activity Date"
                  },
                  "created_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "ISO datetime when the task was created",
                    "title": "Created Date"
                  },
                  "id": {
                    "description": "The ID of the task",
                    "title": "Id",
                    "type": "string"
                  },
                  "is_closed": {
                    "anyOf": [{
                        "type": "boolean"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Whether the task is closed/completed",
                    "title": "Is Closed"
                  },
                  "last_modified_date": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "ISO datetime when the task was last modified",
                    "title": "Last Modified Date"
                  },
                  "owner_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Owner ID of the task",
                    "title": "Owner Id"
                  },
                  "owner_name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Owner name of the task",
                    "title": "Owner Name"
                  },
                  "priority": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Priority of the task",
                    "title": "Priority"
                  },
                  "status": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Status of the task",
                    "title": "Status"
                  },
                  "subject": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Subject of the task",
                    "title": "Subject"
                  },
                  "what_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related record (WhatId)",
                    "title": "What Id"
                  },
                  "what_name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related record name (What.Name)",
                    "title": "What Name"
                  },
                  "who_id": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related contact/lead (WhoId)",
                    "title": "Who Id"
                  },
                  "who_name": {
                    "anyOf": [{
                        "type": "string"
                      }, {
                        "type": "null"
                      }],
                    "default": None,
                    "description": "Related contact/lead name (Who.Name)",
                    "title": "Who Name"
                  }
                },
                "required": ["id"],
                "title": "Task",
                "type": "object"
              }
            },
            "required": ["task", "event_type"],
            "title": "TaskEventPayload",
            "type": "object"
          },
          "slug": "SALESFORCE_TASK_CREATED_OR_COMPLETED_TRIGGER",
          "type": "poll"
        }
