# Auto-generated by Composio CLI. Do not modify manually..

class SENDLOOP:
    """Map of Composio's SENDLOOP toolkit."""

    slug: str = "sendloop"

    class tools:
        LIST_SUBSCRIBERS = "SENDLOOP_LIST_SUBSCRIBERS"
        GET_ACCOUNT_INFO = "SENDLOOP_GET_ACCOUNT_INFO"
        LIST_LISTS = "SENDLOOP_LIST_LISTS"
        LIST_CAMPAIGNS = "SENDLOOP_LIST_CAMPAIGNS"
        GET_OVERALL_LIST_REPORT = "SENDLOOP_GET_OVERALL_LIST_REPORT"

    class triggers:
        pass
