# Auto-generated by Composio CLI. Do not modify manually..

class SENSIBO:
    """Map of Composio's SENSIBO toolkit."""

    slug: str = "sensibo"

    class tools:
        GET_ALL_DEVICES = "SENSIBO_GET_ALL_DEVICES"

    class triggers:
        pass
