# Auto-generated by Composio CLI. Do not modify manually..

class SERVICENOW:
    """Map of Composio's SERVICENOW toolkit."""

    slug: str = "servicenow"

    class tools:
        ATTACH_FILE_TO_RECORD = "SERVICENOW_ATTACH_FILE_TO_RECORD"
        FIND_FILE = "SERVICENOW_FIND_FILE"
        DELETE_A_RECORD = "SERVICENOW_DELETE_A_RECORD"
        CREATE_A_RECORD = "SERVICENOW_CREATE_A_RECORD"
        GET_RECORDS = "SERVICENOW_GET_RECORDS"

    class triggers:
        pass
