# Auto-generated by Composio CLI. Do not modify manually..

class SIDETRACKER:
    """Map of Composio's SIDETRACKER toolkit."""

    slug: str = "sidetracker"

    class tools:
        GET_LISTS = "SIDETRACKER_GET_LISTS"
        GET_LIST_DETAILS = "SIDETRACKER_GET_LIST_DETAILS"

    class triggers:
        pass
