# Auto-generated by Composio CLI. Do not modify manually..

class SIGNPATH:
    """Map of Composio's SIGNPATH toolkit."""

    slug: str = "signpath"

    class tools:
        LIST_CERTIFICATES = "SIGNPATH_LIST_CERTIFICATES"
        RETRIEVE_SIGNING_POLICY_DETAILS = "SIGNPATH_RETRIEVE_SIGNING_POLICY_DETAILS"
        LIST_PROJECTS = "SIGNPATH_LIST_PROJECTS"
        RETRIEVE_SYSTEM_INFO = "SIGNPATH_RETRIEVE_SYSTEM_INFO"

    class triggers:
        pass
