# Auto-generated by Composio CLI. Do not modify manually..

class SIGNATURELY:
    """Map of Composio's SIGNATURELY toolkit."""

    slug: str = "signaturely"

    class tools:
        LIST_DOCUMENTS = "SIGNATURELY_LIST_DOCUMENTS"
        LIST_TEMPLATES = "SIGNATURELY_LIST_TEMPLATES"

    class triggers:
        pass
