# Auto-generated by Composio CLI. Do not modify manually..

class SIMPLESAT:
    """Map of Composio's SIMPLESAT toolkit."""

    slug: str = "simplesat"

    class tools:
        CREATE_OR_UPDATE_TEAM_MEMBER = "SIMPLESAT_CREATE_OR_UPDATE_TEAM_MEMBER"
        CREATE_OR_UPDATE_CUSTOMER = "SIMPLESAT_CREATE_OR_UPDATE_CUSTOMER"

    class triggers:
        pass
