# Auto-generated by Composio CLI. Do not modify manually..

class SMARTPROXY:
    """Map of Composio's SMARTPROXY toolkit."""

    slug: str = "smartproxy"

    class tools:
        LIST_ENDPOINTS_AND_PORTS = "SMARTPROXY_LIST_ENDPOINTS_AND_PORTS"
        GET_API_KEY = "SMARTPROXY_GET_API_KEY"

    class triggers:
        pass
