# Auto-generated by Composio CLI. Do not modify manually..

class SNOWFLAKE_BASIC:
    """Map of Composio's SNOWFLAKE_BASIC toolkit."""

    slug: str = "snowflake_basic"

    class tools:
        SHOW_DATABASES = "SNOWFLAKE_BASIC_SHOW_DATABASES"
        DESCRIBE_TABLE = "SNOWFLAKE_BASIC_DESCRIBE_TABLE"
        SHOW_SCHEMAS = "SNOWFLAKE_BASIC_SHOW_SCHEMAS"
        SHOW_TABLES = "SNOWFLAKE_BASIC_SHOW_TABLES"
        RUN_QUERY = "SNOWFLAKE_BASIC_RUN_QUERY"
        EXPLORE_COLUMNS = "SNOWFLAKE_BASIC_EXPLORE_COLUMNS"

    class triggers:
        pass
