# Auto-generated by Composio CLI. Do not modify manually..

class SSLMATE_CERT_SPOTTER_API:
    """Map of Composio's SSLMATE_CERT_SPOTTER_API toolkit."""

    slug: str = "sslmate_cert_spotter_api"

    class tools:
        RETRIEVE_WEBHOOK = "SSLMATE_CERT_SPOTTER_API_RETRIEVE_WEBHOOK"
        LIST_MONITORED_DOMAINS = "SSLMATE_CERT_SPOTTER_API_LIST_MONITORED_DOMAINS"
        CERTSPOTTER_GET_EVENT = "SSLMATE_CERT_SPOTTER_API_CERTSPOTTER_GET_EVENT"

    class triggers:
        pass
