# Auto-generated by Composio CLI. Do not modify manually..

class SURVEY_MONKEY:
    """Map of Composio's SURVEY_MONKEY toolkit."""

    slug: str = "survey_monkey"

    class tools:
        DELETE_SURVEY = "SURVEY_MONKEY_DELETE_SURVEY"
        CREATE_SURVEY = "SURVEY_MONKEY_CREATE_SURVEY"
        GET_RESPONSES = "SURVEY_MONKEY_GET_RESPONSES"
        GET_SURVEY_DETAILS = "SURVEY_MONKEY_GET_SURVEY_DETAILS"
        GET_GROUPS = "SURVEY_MONKEY_GET_GROUPS"
        GET_CONTACTS = "SURVEY_MONKEY_GET_CONTACTS"
        GET_SURVEYS = "SURVEY_MONKEY_GET_SURVEYS"
        GET_COLLECTORS = "SURVEY_MONKEY_GET_COLLECTORS"

    class triggers:
        pass
