# Auto-generated by Composio CLI. Do not modify manually..

class TEXTCORTEX:
    """Map of Composio's TEXTCORTEX toolkit."""

    slug: str = "textcortex"

    class tools:
        GENERATE_EMAIL = "TEXTCORTEX_GENERATE_EMAIL"
        SUMMARIZE_TEXT = "TEXTCORTEX_SUMMARIZE_TEXT"

    class triggers:
        pass
