# Auto-generated by Composio CLI. Do not modify manually..

class TIMELINK:
    """Map of Composio's TIMELINK toolkit."""

    slug: str = "timelink"

    class tools:
        DELETE_PERSON = "TIMELINK_DELETE_PERSON"

    class triggers:
        pass
