# Auto-generated by Composio CLI. Do not modify manually..

class TODOIST:
    """Map of Composio's TODOIST toolkit."""

    slug: str = "todoist"

    class tools:
        GET_ACTIVE_TASK = "TODOIST_GET_ACTIVE_TASK"
        CREATE_TASK = "TODOIST_CREATE_TASK"
        UPDATE_PROJECT = "TODOIST_UPDATE_PROJECT"
        CLOSE_TASK = "TODOIST_CLOSE_TASK"
        GET_SINGLE_SECTION = "TODOIST_GET_SINGLE_SECTION"
        ADD_WORKSPACE = "TODOIST_ADD_WORKSPACE"
        CREATE_LABEL = "TODOIST_CREATE_LABEL"
        GET_BACKUPS = "TODOIST_GET_BACKUPS"
        GET_PROJECT = "TODOIST_GET_PROJECT"
        GET_LABEL = "TODOIST_GET_LABEL"
        GET_SECTION = "TODOIST_GET_SECTION"
        ARCHIVE_PROJECT = "TODOIST_ARCHIVE_PROJECT"
        LIST_ARCHIVED_WORKSPACE_PROJECTS = "TODOIST_LIST_ARCHIVED_WORKSPACE_PROJECTS"
        DELETE_PERSONAL_LABEL = "TODOIST_DELETE_PERSONAL_LABEL"
        GET_SPECIAL_BACKUPS = "TODOIST_GET_SPECIAL_BACKUPS"
        UNARCHIVE_PROJECT = "TODOIST_UNARCHIVE_PROJECT"
        UPDATE_TASK = "TODOIST_UPDATE_TASK"
        GET_ALL_SECTIONS = "TODOIST_GET_ALL_SECTIONS"
        GET_ALL_TASKS = "TODOIST_GET_ALL_TASKS"
        GET_ALL_PERSONAL_LABELS = "TODOIST_GET_ALL_PERSONAL_LABELS"
        GET_ALL_COMMENTS = "TODOIST_GET_ALL_COMMENTS"
        DELETE_SECTION = "TODOIST_DELETE_SECTION"
        CREATE_SECTION = "TODOIST_CREATE_SECTION"
        DELETE_PROJECT = "TODOIST_DELETE_PROJECT"
        LIST_PENDING_WORKSPACE_INVITATIONS = "TODOIST_LIST_PENDING_WORKSPACE_INVITATIONS"
        RENAME_SHARED_LABELS = "TODOIST_RENAME_SHARED_LABELS"
        GET_COMMENT = "TODOIST_GET_COMMENT"
        GET_SHARED_LABELS = "TODOIST_GET_SHARED_LABELS"
        GET_PROJECT_COLLABORATORS = "TODOIST_GET_PROJECT_COLLABORATORS"
        GET_ALL_PROJECTS = "TODOIST_GET_ALL_PROJECTS"
        CREATE_COMMENT = "TODOIST_CREATE_COMMENT"
        GET_ALL_COLLABORATORS = "TODOIST_GET_ALL_COLLABORATORS"
        CREATE_PROJECT = "TODOIST_CREATE_PROJECT"
        LIST_FILTERS = "TODOIST_LIST_FILTERS"
        UPDATE_COMMENT = "TODOIST_UPDATE_COMMENT"
        UPDATE_PERSONAL_LABEL = "TODOIST_UPDATE_PERSONAL_LABEL"
        UPDATE_SECTION = "TODOIST_UPDATE_SECTION"
        DELETE_TASK = "TODOIST_DELETE_TASK"
        GET_PERSONAL_LABEL = "TODOIST_GET_PERSONAL_LABEL"
        DELETE_LABEL = "TODOIST_DELETE_LABEL"
        UPDATE_LABEL = "TODOIST_UPDATE_LABEL"
        REMOVE_SHARED_LABELS = "TODOIST_REMOVE_SHARED_LABELS"
        GET_TASK = "TODOIST_GET_TASK"
        REOPEN_TASK = "TODOIST_REOPEN_TASK"

    class triggers:
        NEW_TASK_CREATED = {
          "config": {
            "properties": {
              "interval": {
                "default": 1,
                "description": "Periodic Interval to Check for Updates & Send a Trigger in Minutes",
                "title": "Interval",
                "type": "number"
              },
              "project_id": {
                "anyOf": [{
                    "type": "string"
                  }, {
                    "type": "null"
                  }],
                "default": None,
                "description": "(Optional) Filter new tasks by project ID.",
                "title": "Project Id"
              }
            },
            "title": "NewTaskConfig",
            "type": "object"
          },
          "description": "Trigger when a new task is added to Todoist.",
          "instructions": "\n    Triggers when a new task is created in your Todoist account.\n\n    If you provide a project_id, only tasks in that project will trigger the event.\n    You can get your project ID by retrieving all projects using the Get All Projects action.\n    ",
          "name": "New Task Created",
          "payload": {
            "properties": {
              "event_type": {
                "default": "task_added",
                "description": "Type of event",
                "title": "Event Type",
                "type": "string"
              },
              "task": {
                "additionalProperties": True,
                "description": "The Todoist task object",
                "title": "Task",
                "type": "object"
              }
            },
            "required": ["task"],
            "title": "TaskPayload",
            "type": "object"
          },
          "slug": "TODOIST_NEW_TASK_CREATED",
          "type": "poll"
        }
