# Auto-generated by Composio CLI. Do not modify manually..

class TOMBA:
    """Map of Composio's TOMBA toolkit."""

    slug: str = "tomba"

    class tools:
        KEYS_DELETE = "TOMBA_KEYS_DELETE"
        LEADS_LIST = "TOMBA_LEADS_LIST"
        LISTS_LIST = "TOMBA_LISTS_LIST"
        LISTS_UPDATE = "TOMBA_LISTS_UPDATE"
        LEADS_CREATE = "TOMBA_LEADS_CREATE"
        ATTRIBUTES_LIST = "TOMBA_ATTRIBUTES_LIST"
        LISTS_DELETE = "TOMBA_LISTS_DELETE"
        DOMAIN_STATUS = "TOMBA_DOMAIN_STATUS"
        USAGE_STATS = "TOMBA_USAGE_STATS"
        KEYS_LIST = "TOMBA_KEYS_LIST"

    class triggers:
        pass
