# Auto-generated by Composio CLI. Do not modify manually..

class U301:
    """Map of Composio's U301 toolkit."""

    slug: str = "u301"

    class tools:
        SHORTEN_LINK = "U301_SHORTEN_LINK"

    class triggers:
        pass
