# Auto-generated by Composio CLI. Do not modify manually..

class UPDOWN_IO:
    """Map of Composio's UPDOWN_IO toolkit."""

    slug: str = "updown_io"

    class tools:
        LIST_NODES = "UPDOWN_IO_LIST_NODES"
        LIST_NODE_IPS = "UPDOWN_IO_LIST_NODE_IPS"
        LIST_NODE_IPV6 = "UPDOWN_IO_LIST_NODE_IPV6"
        LIST_NODE_IPV4 = "UPDOWN_IO_LIST_NODE_IPV4"

    class triggers:
        pass
