# Auto-generated by Composio CLI. Do not modify manually..

class VESTABOARD:
    """Map of Composio's VESTABOARD toolkit."""

    slug: str = "vestaboard"

    class tools:
        SUBSCRIPTION_API_SEND_MESSAGE = "VESTABOARD_SUBSCRIPTION_API_SEND_MESSAGE"
        LIST_SUBSCRIPTIONS = "VESTABOARD_LIST_SUBSCRIPTIONS"

    class triggers:
        pass
