# Auto-generated by Composio CLI. Do not modify manually..

class WACHETE:
    """Map of Composio's WACHETE toolkit."""

    slug: str = "wachete"

    class tools:
        GET_FOLDER_CONTENT = "WACHETE_GET_FOLDER_CONTENT"
        LIST_NOTIFICATIONS = "WACHETE_LIST_NOTIFICATIONS"
        CREATE_WATCHER = "WACHETE_CREATE_WATCHER"
        DELETE_WATCHER = "WACHETE_DELETE_WATCHER"
        LIST_WATCHERS = "WACHETE_LIST_WATCHERS"

    class triggers:
        pass
