# Auto-generated by Composio CLI. Do not modify manually..

class WEBSCRAPING_AI:
    """Map of Composio's WEBSCRAPING_AI toolkit."""

    slug: str = "webscraping_ai"

    class tools:
        ACCOUNT_INFO = "WEBSCRAPING_AI_ACCOUNT_INFO"
        GET_RENDERED_HTML = "WEBSCRAPING_AI_GET_RENDERED_HTML"
        GET_HTML = "WEBSCRAPING_AI_GET_HTML"
        GET_TEXT = "WEBSCRAPING_AI_GET_TEXT"

    class triggers:
        pass
