# Auto-generated by Composio CLI. Do not modify manually..

class WINSTON_AI:
    """Map of Composio's WINSTON_AI toolkit."""

    slug: str = "winston_ai"

    class tools:
        AI_TEXT_DETECTION = "WINSTON_AI_AI_TEXT_DETECTION"
        TEXT_COMPARE = "WINSTON_AI_TEXT_COMPARE"
        PLAGIARISM_DETECTION = "WINSTON_AI_PLAGIARISM_DETECTION"

    class triggers:
        pass
