# Auto-generated by Composio CLI. Do not modify manually..

class WIT_AI:
    """Map of Composio's WIT_AI toolkit."""

    slug: str = "wit_ai"

    class tools:
        GET_APP = "WIT_AI_GET_APP"
        GET_TRAITS = "WIT_AI_GET_TRAITS"
        GET_INTENT = "WIT_AI_GET_INTENT"
        CREATE_APP = "WIT_AI_CREATE_APP"
        GET_MESSAGE = "WIT_AI_GET_MESSAGE"
        GET_INTENTS = "WIT_AI_GET_INTENTS"
        PUT_APP = "WIT_AI_PUT_APP"
        CREATE_TRAIT = "WIT_AI_CREATE_TRAIT"
        DELETE_APP = "WIT_AI_DELETE_APP"
        GET_TRAIT = "WIT_AI_GET_TRAIT"

    class triggers:
        pass
