# Auto-generated by Composio CLI. Do not modify manually..

class ZOHO_INVOICE:
    """Map of Composio's ZOHO_INVOICE toolkit."""

    slug: str = "zoho_invoice"

    class tools:
        LIST_ITEMS = "ZOHO_INVOICE_LIST_ITEMS"
        LIST_CONTACTS = "ZOHO_INVOICE_LIST_CONTACTS"
        GET_ITEM = "ZOHO_INVOICE_GET_ITEM"
        LIST_EXPENSES = "ZOHO_INVOICE_LIST_EXPENSES"
        LIST_PAYMENTS = "ZOHO_INVOICE_LIST_PAYMENTS"
        LIST_INVOICES = "ZOHO_INVOICE_LIST_INVOICES"

    class triggers:
        pass
