# Auto-generated by Composio CLI. Do not modify manually..

class ZYLVIE:
    """Map of Composio's ZYLVIE toolkit."""

    slug: str = "zylvie"

    class tools:
        GET_AUTHENTICATING_USER = "ZYLVIE_GET_AUTHENTICATING_USER"
        CREATE_PRODUCT = "ZYLVIE_CREATE_PRODUCT"
        UNSUBSCRIBE_WEBHOOK = "ZYLVIE_UNSUBSCRIBE_WEBHOOK"

    class triggers:
        pass
